Repository ROCm/MIVisionX, pull requests merged in 2019-10, with the labels that each got.

#182 Mobilenet-v1 onnx model support
  amd_openvx/openvx/ago/ago_util.cpp
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  amd_openvx_extensions/amd_nn/include/vx_amd_nn.h
  amd_openvx_extensions/amd_nn/src/cast_layer.cpp
  amd_openvx_extensions/amd_nn/src/kernels.cpp
  amd_openvx_extensions/amd_nn/src/kernels.h
  model_compiler/python/nnir.py
  model_compiler/python/nnir_to_openvx.py
  model_compiler/python/onnx_to_nnir.py
Labels: enhancement

#151 OpenVX Bug Fix
  amd_openvx/openvx/ago/ago_haf_cpu_arithmetic.cpp
  amd_openvx/openvx/ago/ago_haf_cpu_canny.cpp
  amd_openvx/openvx/ago/ago_haf_cpu_color_convert.cpp
  amd_openvx/openvx/ago/ago_haf_cpu_geometric.cpp
Labels: bugfix

#190 Adding internal processing thread to Rali
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/include/internal_publishKernels.h
  amd_openvx_extensions/amd_rpp/include/kernels_rpp.h
  amd_openvx_extensions/amd_rpp/include/vx_ext_rpp.h
  amd_openvx_extensions/amd_rpp/source/copy.cpp
  amd_openvx_extensions/amd_rpp/source/internal_publishKernels.cpp
  amd_openvx_extensions/amd_rpp/source/kernel_rpp.cpp
  apps/augmentation_unittest/augmentation_unittests.cpp
  apps/rali_unittests/rali_unittests.cpp
  rali/include/image.h
  rali/include/master_graph.h
  rali/include/node_copy.h
  rali/include/ring_buffer.h
  rali/python/rali.py
  rali/source/circular_buffer.cpp
  rali/source/image.cpp
  rali/source/master_graph.cpp
  rali/source/node_copy.cpp
  rali/source/rali_api_data_loaders.cpp
  rali/source/rali_api_info.cpp
  rali/source/ring_buffer.cpp
Labels: enhancement

#192 MIVisionX - 1.4 Release Fix
  README.md
  rali/CMakeLists.txt
Labels: For ROCm Release, enhancement

#197 Fixed python's RALI parameter API
  rali/python/rali_parameter.py
Labels: enhancement

#200 Enable SLES Build
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  apps/CMakeLists.txt
Labels: updates

#199 Added loop parameter to RALI to go through the images in a loop.
  apps/rali_unittests/rali_unittests.cpp
  rali/include/decoder.h
  rali/include/decoder_factory.h
  rali/include/file_source_reader.h
  rali/include/image_loader_multi_thread.h
  rali/include/image_loader_single_thread.h
  rali/include/image_read_and_decode.h
  rali/include/image_source_evaluator.h
  rali/include/loader_module.h
  rali/include/node_jpeg_file_source.h
  rali/include/rali_api_data_loaders.h
  rali/include/reader.h
  rali/include/reader_factory.h
  rali/include/video_loader_module.h
  rali/python/rali.py
  rali/python/rali_lib.py
  rali/source/decoder_factory.cpp
  rali/source/file_source_reader.cpp
  rali/source/image_loader_multi_thread.cpp
  rali/source/image_loader_single_thread.cpp
  rali/source/image_read_and_decode.cpp
  rali/source/image_source_evaluator.cpp
  rali/source/node_jpeg_file_source.cpp
  rali/source/rali_api_data_loaders.cpp
  rali/source/reader_factory.cpp
  rali/source/video_loader_module.cpp
Labels: enhancement

#201 Fixed bugs,
  apps/image_augmentation/image_augmentation.cpp
  rali/include/commons.h
  rali/include/image_loader_single_thread.h
  rali/include/log.h
  rali/include/parameter_random.h
  rali/source/image_loader_single_thread.cpp
  rali/source/parameter_factory.cpp
  rali/source/rali_api.cpp
Labels: bugfix
