Repository ROCm/MIVisionX, pull requests merged in 2019-04, with the labels that each got.

#71 Classifier App for winML
  apps/README.md
  apps/mivisonx_winml_classifier/README.md
  apps/mivisonx_winml_classifier/classifier.cpp
  apps/mivisonx_winml_classifier/cvui.h
  apps/mivisonx_winml_classifier/images/MIVisionX-ImageClassification-WinML.png
  apps/mivisonx_winml_classifier/images/MIVisionX-ImageClassification.png
  apps/mivisonx_winml_classifier/winml_classifier.sln
  apps/mivisonx_winml_classifier/winml_classifier.vcxproj
  apps/mivisonx_winml_classifier/winml_classifier.vcxproj.filters
Labels: New Feature

#74 Bug fix for onnx_to_nnir
  model_compiler/python/onnx_to_nnir.py
Labels: bugfix

#75 Folder Name Correction
  apps/README.md
  apps/mivisionx_winml_classifier/README.md
  apps/mivisionx_winml_classifier/classifier.cpp
  apps/mivisionx_winml_classifier/cvui.h
  apps/mivisionx_winml_classifier/images/MIVisionX-ImageClassification-WinML.png
  apps/mivisionx_winml_classifier/images/MIVisionX-ImageClassification.png
  apps/mivisionx_winml_classifier/winml_classifier.sln
  apps/mivisionx_winml_classifier/winml_classifier.vcxproj
  apps/mivisionx_winml_classifier/winml_classifier.vcxproj.filters
Labels: bugfix

#80 API Fix
  apps/mivisionx_winml_yolov2/MIVisionX_winml_YoloV2.sln
  apps/mivisionx_winml_yolov2/MIVisionX_winml_YoloV2.vcxproj
  apps/mivisionx_winml_yolov2/README.md
  apps/mivisionx_winml_yolov2/source/AnnieYoloDetect.cpp
  apps/mivisionx_winml_yolov2/source/main.cpp
Labels: bugfix

#81 OpenVX Classifier App for Linux
  apps/README.md
  apps/mivisionx_openvx_classifier/CMakeLists.txt
  apps/mivisionx_openvx_classifier/README.md
  apps/mivisionx_openvx_classifier/cmake/FindOpenCL.cmake
  apps/mivisionx_openvx_classifier/data/MIVisionX-ImageClassification.png
  apps/mivisionx_openvx_classifier/data/classifier.png
  apps/mivisionx_openvx_classifier/data/labels.txt
  apps/mivisionx_openvx_classifier/data/simple_labels.txt
  apps/mivisionx_openvx_classifier/include/caffeModels.h
  apps/mivisionx_openvx_classifier/include/cvui.h
  apps/mivisionx_openvx_classifier/source/caffeModels.cpp
  apps/mivisionx_openvx_classifier/source/classifier.cpp
Labels: New Feature

#45 Crop Layer
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  amd_openvx_extensions/amd_nn/README.md
  amd_openvx_extensions/amd_nn/include/vx_amd_nn.h
  amd_openvx_extensions/amd_nn/src/crop_layer.cpp
  amd_openvx_extensions/amd_nn/src/kernels.cpp
  amd_openvx_extensions/amd_nn/src/kernels.h
  model_compiler/python/caffe_to_nnir.py
  model_compiler/python/nnir.py
  model_compiler/python/nnir_to_openvx.py
Labels: New Feature, enhancement

#59 Adding support for ONNX operation Reshape(for onnx models v1.1)
  model_compiler/README.md
  model_compiler/python/nnir.py
  model_compiler/python/onnx_to_nnir.py
Labels: For ROCm Release, enhancement

#83 relative path decode for runvx
  utilities/runvx/runvx.cpp
Labels: For ROCm Release, enhancement

#87 Update nnir.py: Reshape Bug Fix
  model_compiler/python/nnir.py
Labels: bugfix

#89 NNEF_to_NNIR Usage Fix
  model_compiler/python/nnef_to_nnir.py
Labels: bugfix

#88 NNEF Documentation
  model_compiler/README.md
Labels: enhancement

#94 Documentation updates
  README.md
  model_compiler/README.md
Labels: enhancement

#86 fixed bug with gdf file name
  utilities/runvx/runvx.cpp
Labels: bugfix

#92 Support for permute, prior box and flatten in model_compiler
  model_compiler/python/caffe_pb2.py
  model_compiler/python/caffe_to_nnir.py
  model_compiler/python/nnir.py
  model_compiler/python/nnir_to_openvx.py
Labels: bugfix, enhancement

#95 Readme fix for 1.2.0
  README.md
  docs/README.md
  model_compiler/README.md
  samples/README.md
  utilities/README.md
  utilities/runvx/runvx.cpp
Labels: enhancement

#91 Crop and resize layer
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  amd_openvx_extensions/amd_nn/README.md
  amd_openvx_extensions/amd_nn/include/vx_amd_nn.h
  amd_openvx_extensions/amd_nn/src/crop_and_resize_layer.cpp
  amd_openvx_extensions/amd_nn/src/kernels.cpp
  amd_openvx_extensions/amd_nn/src/kernels.h
  model_compiler/python/nnir.py
  model_compiler/python/nnir_to_openvx.py
Labels: enhancement

#96 MIVisionX 1.2.0
  CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
Labels: For ROCm Release

#97 Model compiler Updates
  docs/images/modelCompilerFrameWorks.png
  docs/images/modelTrainedFrameWorks.png
  model_compiler/README.md
Labels: enhancement

#103 nnir_to_openvx print
  model_compiler/python/nnir_to_openvx.py
Labels: bugfix
