Repository ROCm/MIVisionX, pull requests merged in 2019-03, with the labels that each got.

#60 Docker Info Updates
  README.md
Labels: enhancement

#61 Travis - Use MIVisionX Docker
  .travis.yml
Labels: enhancement

#62 Adding input_dims to onnx_to_nnir.py
  model_compiler/README.md
  model_compiler/python/onnx_to_nnir.py
Labels: enhancement

#68 Fix for OpenCL Include Linke Error
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  apps/cloud_inference/server_app/CMakeLists.txt
Labels: For ROCm Release

#57 fp16 bug fix for concat and other layers
  amd_openvx_extensions/amd_nn/src/batch_normalization_layer.cpp
  amd_openvx_extensions/amd_nn/src/concat_layer.cpp
  amd_openvx_extensions/amd_nn/src/convolution_layer.cpp
  amd_openvx_extensions/amd_nn/src/deconvolution_layer.cpp
  amd_openvx_extensions/amd_nn/src/fully_connected_layer.cpp
  amd_openvx_extensions/amd_nn/src/scale_layer.cpp
  amd_openvx_extensions/amd_nn/src/slice_layer.cpp
  amd_openvx_extensions/amd_nn/src/upsample_nearest_layer.cpp
Labels: bugfix

#69 WinML local data for Binding
  amd_openvx_extensions/amd_winml/README.md
  amd_openvx_extensions/amd_winml/include/vx_ext_winml.h
  amd_openvx_extensions/amd_winml/include/vx_winml.h
  amd_openvx_extensions/amd_winml/samples/README.md
  amd_openvx_extensions/amd_winml/samples/winML-image-vgg19.gdf
  amd_openvx_extensions/amd_winml/samples/winML-image.gdf
  amd_openvx_extensions/amd_winml/samples/winML-live-emotions.gdf
  amd_openvx_extensions/amd_winml/samples/winML-live-multipleModels.gdf
  amd_openvx_extensions/amd_winml/samples/winML-live.gdf
  amd_openvx_extensions/amd_winml/source/internal_publishKernels.cpp
  amd_openvx_extensions/amd_winml/source/internal_vxNodes.cpp
  amd_openvx_extensions/amd_winml/source/winML_onnxModelNode.cpp
Labels: bugfix
