Repository ROCm/MIVisionX, pull requests merged in 2019-08, with the labels that each got.

#148 add prefix to names for local tensor
  model_compiler/python/nnir.py
Labels: enhancement

#156 fixing top of tree for virtual_tensor value
  model_compiler/python/nnir_to_openvx.py
Labels: bugfix

#157 Documentation Fix
  MIVisionX-setup.py
  README.md
Labels: bugfix

#159 updates mivisionx_openvx_classifier app
  apps/mivisionx_openvx_classifier/include/caffeModels.h
  apps/mivisionx_openvx_classifier/source/caffeModels.cpp
  apps/mivisionx_openvx_classifier/source/classifier.cpp
Labels: bugfix, enhancement
