Repository ROCm/MIVisionX, pull requests merged in 2019-07, with the labels that each got.

#146 Visual Profiler for VX_NN
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  amd_openvx_extensions/amd_nn/src/activation_layer.cpp
  amd_openvx_extensions/amd_nn/src/batch_normalization_layer.cpp
  amd_openvx_extensions/amd_nn/src/convolution_layer.cpp
  amd_openvx_extensions/amd_nn/src/deconvolution_layer.cpp
  amd_openvx_extensions/amd_nn/src/fully_connected_layer.cpp
  amd_openvx_extensions/amd_nn/src/kernels.cpp
  amd_openvx_extensions/amd_nn/src/kernels.h
  amd_openvx_extensions/amd_nn/src/normalization_layer.cpp
  amd_openvx_extensions/amd_nn/src/pooling_layer.cpp
  amd_openvx_extensions/amd_nn/src/profiler.cpp
  amd_openvx_extensions/amd_nn/src/profiler.h
  amd_openvx_extensions/amd_nn/src/profilerEvents.h
  amd_openvx_extensions/amd_nn/src/reshape_layer.cpp
  amd_openvx_extensions/amd_nn/src/scale_layer.cpp
  amd_openvx_extensions/amd_nn/src/softmax_layer.cpp
  amd_openvx_extensions/amd_nn/src/tensor_add.cpp
  amd_openvx_extensions/amd_nn/src/tensor_multiply.cpp
  amd_openvx_extensions/amd_nn/src/tensor_subtract.cpp
Labels: enhancement

#145 fixed bug with multiple stream decoding in copy to output
  amd_openvx_extensions/amd_media/decoder.cpp
Labels: bugfix

#142 fix bug in CBA fusion and added fusion for leaky relu
  amd_openvx_extensions/amd_nn/src/batch_normalization_layer.cpp
  amd_openvx_extensions/amd_nn/src/convolution_layer.cpp
  model_compiler/python/nnir.py
  model_compiler/python/nnir_to_openvx.py
Labels: bugfix

#144 Mobilenet-SSD support
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  amd_openvx_extensions/amd_nn/include/vx_amd_nn.h
  amd_openvx_extensions/amd_nn/src/concat_layer.cpp
  amd_openvx_extensions/amd_nn/src/detection_output.cpp
  amd_openvx_extensions/amd_nn/src/kernels.cpp
  amd_openvx_extensions/amd_nn/src/kernels.h
  amd_openvx_extensions/amd_nn/src/permute_layer.cpp
  amd_openvx_extensions/amd_nn/src/prior_box_layer.cpp
  amd_openvx_extensions/amd_nn/src/softmax_layer.cpp
  model_compiler/python/caffe_to_nnir.py
  model_compiler/python/nnir.py
  model_compiler/python/nnir_to_openvx.py
Labels: bugfix, enhancement

#147 Dump output of layers for debugging
  amd_openvx/openvx/ago/ago_util.cpp
  amd_openvx_extensions/amd_nn/src/activation_layer.cpp
  amd_openvx_extensions/amd_nn/src/batch_normalization_layer.cpp
  amd_openvx_extensions/amd_nn/src/convolution_layer.cpp
  amd_openvx_extensions/amd_nn/src/deconvolution_layer.cpp
  amd_openvx_extensions/amd_nn/src/detection_output.cpp
  amd_openvx_extensions/amd_nn/src/fully_connected_layer.cpp
  amd_openvx_extensions/amd_nn/src/kernels.cpp
  amd_openvx_extensions/amd_nn/src/kernels.h
  amd_openvx_extensions/amd_nn/src/normalization_layer.cpp
  amd_openvx_extensions/amd_nn/src/pooling_layer.cpp
  amd_openvx_extensions/amd_nn/src/reshape_layer.cpp
  amd_openvx_extensions/amd_nn/src/scale_layer.cpp
  amd_openvx_extensions/amd_nn/src/softmax_layer.cpp
  amd_openvx_extensions/amd_nn/src/tensor_add.cpp
  amd_openvx_extensions/amd_nn/src/tensor_subtract.cpp
  model_compiler/python/caffe_to_nnir.py
  model_compiler/python/nnir_to_openvx.py
  model_compiler/python/onnx_to_nnir.py
Labels: enhancement

#149 Fixing bug PR#147
  model_compiler/python/nnir_to_openvx.py
Labels: bugfix

#152 fp16 support for annpython
  model_compiler/python/nnir_to_openvx.py
Labels: enhancement

#153 bug fix for fp16 nnir_to_openvx
  model_compiler/python/nnir_to_openvx.py
Labels: bugfix

#154 VX_NN - Warning Fix
  amd_openvx_extensions/amd_nn/src/permute_layer.cpp
Labels: bugfix
