Repository ROCm/MIVisionX, pull requests merged in 2019-01, with the labels that each got.

#6 MIVisionX Setup Script Fix
  MIVisionX-setup.py
  README.md
Labels: bugfix

#7 Setup script enhancement
  MIVisionX-setup.py
Labels: bugfix

#11 Model Compiler Enhancements
  model_compiler/README.md
  model_compiler/python/caffe_to_nnir.py
  model_compiler/python/nnir_to_nnef.py
  model_compiler/python/nnir_to_openvx.py
  model_compiler/python/onnx_to_nnir.py
Labels: bugfix, enhancement

#12 Model compiler & optimizer
  README.md
  docs/images/modelCompilerWorkflow.png
  model_compiler/README.md
  model_compiler/python/nnir-update.py
  model_compiler/python/nnir_update.py
Labels: enhancement

#17 Documentation upgrades
  README.md
  apps/cloud_inference/README.md
  model_compiler/README.md
Labels: enhancement

#20 MIVisionX webpage updates
  README.md
Labels: enhancement

#22 Traffic Vision Added to apps
  apps/README.md
Labels: enhancement

#16 Error and Warning Fixes
  apps/cloud_inference/client_app/annInferenceApp.py
  model_compiler/python/caffe_to_nnir.py
  model_compiler/python/nnir.py
  toolkit/README.md
  toolkit/analysis_and_visualization/bounding_box/generate-visualization.py
  toolkit/analysis_and_visualization/classification/generate-visualization.py
  toolkit/analysis_and_visualization/classification/utils/sorttable.js
  toolkit/analysis_and_visualization/utils/sorttable.js
  toolkit/data_generator/classification/scripts/imageDataBaseCreator.py
  toolkit/data_generator/classification/scripts/step-2.py
  toolkit/data_generator/classification/scripts/step-3.py
  toolkit/img/summary-boundingBox.png
  toolkit/img/summary-classification.png
Labels: bugfix, enhancement

#30 MIVisionX for Windows 10
  MIVisionX-setup.py
  MIVisionX.sln
  README.md
  amd_openvx/README.md
  amd_openvx/openvx/openvx.vcxproj
  amd_openvx_extensions/README.md
  amd_openvx_extensions/amd_loomsl/README.md
  amd_openvx_extensions/amd_loomsl/vx_loomsl.vcxproj
  amd_openvx_extensions/amd_opencv/README.md
  amd_openvx_extensions/amd_opencv/vx_opencv.vcxproj
  amd_openvx_extensions/amd_opencv/vx_opencv.vcxproj.filters
  utilities/loom_shell/loom_shell.vcxproj
  utilities/runcl/runcl.vcxproj
  utilities/runvx/runvx.vcxproj
Labels: enhancement

#28 add argmax output code for fp16
  model_compiler/python/nnir_to_openvx.py
Labels: enhancement

#33 vx_ext_opencv fix
  amd_openvx_extensions/amd_opencv/include/vx_ext_opencv.h
Labels: bugfix

#32 fixed so that batch norm layer does not convert tensors to FP16
  model_compiler/python/nnir.py
Labels: bugfix
