Repository ROCm/MIVisionX, pull requests merged in 2019-06, with the labels that each got.

#122 MV Compile Module
  MIVisionX-setup.py
  README.md
  amd_openvx/cmake/FindFFmpeg.cmake
  amd_openvx_extensions/CMakeLists.txt
  amd_openvx_extensions/amd_media/CMakeLists.txt
  amd_openvx_extensions/amd_media/decoder.cpp
  amd_openvx_extensions/amd_media/encoder.cpp
  amd_openvx_extensions/amd_media/include/vx_amd_media.h
  amd_openvx_extensions/amd_media/kernels.cpp
  amd_openvx_extensions/amd_media/kernels.h
  docs/images/MIVisionX.png
  model_compiler/python/nnir_to_clib.py
  samples/inference/mv_objdetect/CMakeLists.txt
  samples/inference/mv_objdetect/README.md
  samples/inference/mv_objdetect/mvobjdetect.cpp
  samples/inference/mv_objdetect/visualize.cpp
  samples/inference/mv_objdetect/visualize.h
  samples/model_compiler_samples/README.md
  utilities/CMakeLists.txt
  utilities/mv_deploy/CMakeLists.txt
  utilities/mv_deploy/mv_compile.cpp
  utilities/mv_deploy/mv_extras_postproc.cpp
  utilities/mv_deploy/mv_extras_postproc.h
  utilities/mv_deploy/mvdeploy_api.h
Labels: For ROCm Release, New Feature

#132 NNEF Update
  model_compiler/README.md
  model_compiler/python/nnef_to_nnir.py
  model_compiler/python/nnir.py
  model_compiler/python/nnir_update.py
Labels: For ROCm Release, enhancement

#133 MIVisionX 1.3.0 - Release updates
  README.md
  docs/images/MIVisionX.png
  model_compiler/python/nnir.py
Labels: For ROCm Release

#136 MV Compile - bug fix
  model_compiler/python/nnir_to_clib.py
Labels: bugfix

#143 CMakeList Fix
  CMakeLists.txt
  amd_openvx/CMakeLists.txt
  amd_openvx/openvx/CMakeLists.txt
  amd_openvx_extensions/CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  apps/CMakeLists.txt
  utilities/CMakeLists.txt
  utilities/runvx/CMakeLists.txt
Labels: bugfix
