Repository ROCm/MIVisionX, pull requests merged in 2019-05, with the labels that each got.

#104 Ubuntu 18.04 warnings fix
  amd_openvx/openvx/ago/ago_kernel_api.cpp
  amd_openvx/openvx/ago/ago_util_opencl.cpp
  apps/cloud_inference/server_app/infcom.h
Labels: bugfix

#101 Support for ONNX V1.3
  amd_openvx/openvx/ago/ago_util.cpp
  model_compiler/python/nnir_to_openvx.py
Labels: enhancement, high

#105 adding grouped convolution and updating readme
  amd_openvx/openvx/include/VX/vx_khr_nn.h
  amd_openvx_extensions/amd_nn/README.md
  amd_openvx_extensions/amd_nn/src/convolution_layer.cpp
  model_compiler/README.md
  model_compiler/python/nnir_to_openvx.py
Labels: enhancement

#106 Loom Sample & Readme Updates
  README.md
  amd_openvx_extensions/README.md
  amd_openvx_extensions/amd_loomsl/README.md
  docs/images/loom-1.jpg
  docs/images/loom-2.jpg
  docs/images/loom-3.jpg
  docs/images/loom-4.png
  samples/README.md
  samples/loom_360_stitch/sample-1/loomStitch-sample1-get-data.py
  samples/loom_360_stitch/sample-1/loomStitch-sample1.txt
  samples/loom_360_stitch/sample-2/loomStitch-sample2-get-data.py
  samples/loom_360_stitch/sample-2/loomStitch-sample2.txt
  samples/loom_360_stitch/sample-3/loomStitch-sample3-get-data.py
  samples/loom_360_stitch/sample-3/loomStitch-sample3.txt
Labels: enhancement

#107 Readme updates
  README.md
  amd_openvx/README.md
  amd_openvx_extensions/amd_loomsl/README.md
  amd_openvx_extensions/amd_winml/README.md
  apps/README.md
  docs/images/LOOM_LOGO_250X125.png
  samples/README.md
Labels: enhancement

#108 updates
  MIVisionX-setup.py
  README.md
  amd_openvx_extensions/README.md
  amd_openvx_extensions/amd_loomsl/README.md
Labels: enhancement

#109 YoloV2 Fix
  model_compiler/python/nnir_to_openvx.py
Labels: bugfix

#111 cloud inference updates
  apps/cloud_inference/README.md
  docs/images/client_app-3.png
  docs/images/client_app.png
  docs/images/client_app_1.png
  docs/images/client_app_2.png
Labels: enhancement

#112 Cloud Inference Fix
  apps/cloud_inference/README.md
  apps/cloud_inference/client_app/README.md
  apps/cloud_inference/client_app/infcom.h
  apps/cloud_inference/server_app/CMakeLists.txt
  apps/cloud_inference/server_app/README.md
  apps/cloud_inference/server_app/arguments.cpp
  apps/cloud_inference/server_app/compiler.cpp
  apps/cloud_inference/server_app/inference.cpp
  apps/cloud_inference/server_app/profiler.cpp
  apps/cloud_inference/server_app/profiler.h
Labels: bugfix

#113 Cloud Inference Fix
  apps/cloud_inference/README.md
Labels: enhancement

#114 Cloud Inference - Server Help
  apps/cloud_inference/README.md
  apps/cloud_inference/server_app/README.md
  apps/cloud_inference/server_app/arguments.cpp
Labels: enhancement

#115 Cloud Inference Application - Graphs & Enhancements
  apps/cloud_inference/client_app/annInferenceApp.pro
  apps/cloud_inference/client_app/inference_control.cpp
  apps/cloud_inference/client_app/inference_receiver.cpp
  apps/cloud_inference/client_app/inference_receiver.h
  apps/cloud_inference/client_app/inference_viewer.cpp
  apps/cloud_inference/client_app/inference_viewer.h
  apps/cloud_inference/client_app/perf_chart.cpp
  apps/cloud_inference/client_app/perf_chart.h
  apps/cloud_inference/client_app/perf_chart.ui
  apps/cloud_inference/client_app/perf_graph.ui
  apps/cloud_inference/client_app/qcustomplot.cpp
  apps/cloud_inference/client_app/qcustomplot.h
Labels: bugfix, enhancement

#118 onnx_to_nnir help text fix
  model_compiler/python/onnx_to_nnir.py
Labels: bugfix

#116 fixes group convolution
  amd_openvx/openvx/include/VX/vx_khr_nn.h
  amd_openvx_extensions/amd_nn/src/convolution_layer.cpp
  model_compiler/README.md
  model_compiler/python/nnir_to_openvx.py
Labels: bugfix

#119 Nnef to nnir
  model_compiler/python/nnef_to_nnir.py
Labels: bugfix, enhancement

#121 Setup updates
  MIVisionX-setup.py
Labels: enhancement

#123 NNEF to NNIR - Fix
  model_compiler/python/nnef_to_nnir.py
Labels: enhancement

#124 graph update
  apps/cloud_inference/client_app/perf_chart.cpp
  apps/cloud_inference/client_app/perf_chart.h
  apps/cloud_inference/client_app/perf_chart.ui
Labels: enhancement

#125 Nnef to nnir
  model_compiler/python/nnef_to_nnir.py
Labels: enhancement

#127 Docker & Config updates
  README.md
Labels: updates

#129 RunVX Windows Fix
  utilities/runvx/runvx.cpp
Labels: bugfix

#110 onnx v1.3 reshape bug fix
  model_compiler/python/nnir.py
  model_compiler/python/nnir_to_openvx.py
  model_compiler/python/onnx_to_nnir.py
Labels: bugfix, enhancement
