Repository ROCm/MIVisionX, pull requests merged in 2020-11, with the labels that each got.

#386 ADAT improvements
  toolkit/analysis_and_visualization/classification/.gitignore
  toolkit/analysis_and_visualization/classification/README.md
  toolkit/analysis_and_visualization/classification/assets/scripts/app.js
  toolkit/analysis_and_visualization/classification/assets/scripts/charts.js
  toolkit/analysis_and_visualization/classification/assets/scripts/pagination.js
  toolkit/analysis_and_visualization/classification/assets/styles/simplePagination.css
  toolkit/analysis_and_visualization/classification/assets/styles/style.css
  toolkit/analysis_and_visualization/classification/assets/templates/index.html
  toolkit/analysis_and_visualization/classification/generate-visualization.py
Labels: bugfix, enhancement

#392 CMakeList Fix - Developer help
  CMakeLists.txt
Labels: bugfix

#393 Loom Shell Multi-GPU support
  utilities/loom_shell/loom_shell_util.cpp
Labels: bugfix

#397 windows updates - SLN Updates
  amd_openvx/openvx/openvx.vcxproj
  amd_openvx_extensions/amd_loomsl/kernels/lens_distortion_remap.cpp
  amd_openvx_extensions/amd_loomsl/vx_loomsl.vcxproj
  amd_openvx_extensions/amd_opencv/vx_opencv.vcxproj
  amd_openvx_extensions/amd_winml/vx_winml.vcxproj
  utilities/loom_shell/loom_shell.vcxproj
  utilities/runcl/runcl.vcxproj
  utilities/runvx/runvx.vcxproj
Labels: enhancement
