Repository ROCm/MIVisionX, pull requests merged in 2020-10, with the labels that each got.

#368 RALI - Fix missing lib failure
  CMakeLists.txt
  amd_openvx/openvx/CMakeLists.txt
  rali/rali/CMakeLists.txt
Labels: bugfix

#370 Setup - Boost shared and static lib
  MIVisionX-setup.py
  README.md
Labels: bugfix

#371 OpenVX - fix overflow
  amd_openvx/openvx/ago/ago_haf_cpu_filter.cpp
  amd_openvx/openvx/ago/ago_kernel_api.cpp
  amd_openvx/openvx/ago/ago_util.cpp
  amd_openvx/openvx/api/vx_api.cpp
Labels: bugfix

#357 Ubuntu 20.04 Support
  amd_openvx/openvx/ago/ago_interface.cpp
  amd_openvx/openvx/ago/ago_util.cpp
  amd_openvx/openvx/api/vx_api.cpp
  utilities/runcl/runcl.cpp
  utilities/runvx/vxEngine.cpp
Labels: bugfix, enhancement

#373 Ubuntu 20.04 Support - OpenCL
  amd_openvx/openvx/ago/ago_util_opencl.cpp
  utilities/runcl/runcl.cpp
  utilities/runvx/vxEngine.cpp
Labels: bugfix

#375 Travis - Comprehensive Testing
  .travis.yml
Labels: New Feature, enhancement

#376 Build Level Information
  README.md
  docs/build-levels.md
Labels: enhancement

#377 CMakeList Updates - runVX CPU, Build Level, & OpenCL_SUPPORT
  CMakeLists.txt
  README.md
  amd_openvx/CMakeLists.txt
  amd_openvx/openvx/CMakeLists.txt
  amd_openvx_extensions/CMakeLists.txt
  apps/CMakeLists.txt
  utilities/CMakeLists.txt
  utilities/runvx/CMakeLists.txt
  utilities/runvx/runvx.cpp
  utilities/runvx/vxImage.cpp
  utilities/runvx/vxTensor.cpp
Labels: enhancement

#374 Mcw rali changes
  .vscode/settings.json
  rali/README.md
  rali/rali/include/caffe2_lmdb_record_reader.h
  rali/rali/include/caffe2_meta_data_reader_detection.h
  rali/rali/include/caffe_lmdb_record_reader.h
  rali/rali/include/caffe_meta_data_reader_detection.h
  rali/rali/include/meta_node_ssd_random_crop.h
  rali/rali/include/node.h
  rali/rali/include/node_random_crop.h
  rali/rali/include/node_ssd_random_crop.h
  rali/rali/include/parameter_crop.h
  rali/rali/include/rali_api_meta_data.h
  rali/rali/include/tf_meta_data_reader_detection.h
  rali/rali/source/bounding_box_graph.cpp
  rali/rali/source/caffe2_lmdb_record_reader.cpp
  rali/rali/source/caffe2_meta_data_reader_detection.cpp
  rali/rali/source/caffe_lmdb_record_reader.cpp
  rali/rali/source/caffe_meta_data_reader_detection.cpp
  rali/rali/source/master_graph.cpp
  rali/rali/source/meta_node_crop.cpp
  rali/rali/source/meta_node_crop_resize.cpp
  rali/rali/source/meta_node_resize.cpp
  rali/rali/source/meta_node_resize_crop_mirror.cpp
  rali/rali/source/meta_node_rotate.cpp
  rali/rali/source/meta_node_ssd_random_crop.cpp
  rali/rali/source/node_random_crop.cpp
  rali/rali/source/node_ssd_random_crop.cpp
  rali/rali/source/rali_api_augmentation.cpp
  rali/rali/source/rali_api_meta_data.cpp
  rali/rali/source/ring_buffer.cpp
  rali/rali/source/tf_meta_data_reader_detection.cpp
  rali/rali_pybind/amd/rali/pipeline.py
  rali/rali_pybind/amd/rali/plugin/pytorch.py
  rali/rali_pybind/amd/rali/plugin/tf.py
  rali/rali_pybind/example/coco_pipeline.py
  rali/rali_pybind/example/tf_detection_pipeline.py
  rali/rali_pybind/rali_pybind.cpp
  utilities/CMakeLists.txt
  utilities/rali/rali_unittests/rali_unittests.cpp
Labels: New Feature, enhancement

#379 add README file for amd_media
  amd_openvx_extensions/amd_media/README.md
Labels: enhancement

#381 Media Ext - Fix and additions
  README.md
  amd_openvx_extensions/README.md
  amd_openvx_extensions/amd_media/README.md
Labels: enhancement

#382 Readme - Clean up
  .vscode/settings.json
  README.md
  amd_openvx_extensions/README.md
  amd_openvx_extensions/amd_media/README.md
  docs/build-levels.md
Labels: bugfix

#383 MIVisionX Lite - macOS Support
  CMakeLists.txt
  README.md
  amd_openvx/CMakeLists.txt
  amd_openvx/openvx/CMakeLists.txt
  utilities/CMakeLists.txt
  utilities/runvx/CMakeLists.txt
Labels: enhancement

#385 CMakeLists - Developer Options Info
  CMakeLists.txt
  amd_openvx_extensions/CMakeLists.txt
  apps/CMakeLists.txt
  utilities/CMakeLists.txt
Labels: enhancement

#384 Rr/tf record update
  rali/rali/include/decoder.h
  rali/rali/include/node_image_loader.h
  rali/rali/include/node_image_loader_single_shard.h
  rali/rali/include/rali_api_data_loaders.h
  rali/rali/include/reader.h
  rali/rali/include/tf_meta_data_reader.h
  rali/rali/include/tf_record_reader.h
  rali/rali/source/cifar10_data_reader.cpp
  rali/rali/source/image_read_and_decode.cpp
  rali/rali/source/master_graph.cpp
  rali/rali/source/node_image_loader.cpp
  rali/rali/source/node_image_loader_single_shard.cpp
  rali/rali/source/rali_api_data_loaders.cpp
  rali/rali/source/tf_meta_data_reader.cpp
  rali/rali/source/tf_record_reader.cpp
  rali/rali_pybind/amd/rali/ops.py
  rali/rali_pybind/amd/rali/pipeline.py
  rali/rali_pybind/amd/rali/plugin/pytorch.py
  rali/rali_pybind/amd/rali/plugin/tf.py
  rali/rali_pybind/amd/rali/types.py
  rali/rali_pybind/example/tf_mnistTrainingExample/README.md
  rali/rali_pybind/example/tf_mnistTrainingExample/mnist_tfrecord.py
  rali/rali_pybind/example/tf_mnistTrainingExample/tf_mnist_classification_rali.py
  rali/rali_pybind/example/tf_pipeline.py
  rali/rali_pybind/rali_pybind.cpp
  utilities/rali/rali_dataloader_tf/CMakeLists.txt
  utilities/rali/rali_dataloader_tf/README.md
  utilities/rali/rali_dataloader_tf/rali_dataloader_tf.cpp
Labels: bugfix, enhancement
