Repository ROCm/MIVisionX, pull requests merged in 2020-03, with the labels that each got.

#246 Windows Build - Allow VS Upgrade
  amd_openvx/openvx/ago/ago_platform.h
  amd_openvx_extensions/amd_opencv/vx_opencv.vcxproj
Labels: bugfix

#245 modularizing ADAT code
  toolkit/analysis_and_visualization/classification/generate-visualization.py
Labels: enhancement

#247 MIVisionX Setup - Reinstall & Delete features added
  MIVisionX-setup.py
Labels: enhancement

#248 GA Beacon
  README.md
Labels: enhancement

#251 MIVisionX Setup - Half.hpp fix
  MIVisionX-setup.py
Labels: enhancement

#252 Readme updates
  README.md
Labels: enhancement

#244 added multithreading to RALI performance utility
  utilities/rali_performance_tests/rali_performance_tests.cpp
Labels: enhancement

#215 Appending node type to local tensor names for calibration
  model_compiler/python/caffe_to_nnir.py
  model_compiler/python/nnef_to_nnir.py
  model_compiler/python/nnir.py
  model_compiler/python/nnir_update.py
  model_compiler/python/onnx_to_nnir.py
Labels: enhancement

#240 H/constant layer
  model_compiler/README.md
  model_compiler/python/nnir.py
  model_compiler/python/onnx_to_nnir.py
Labels: enhancement

#243 Added raliReset functionality and fixed multi-threaded decode performance issue
  apps/image_augmentation/image_augmentation.cpp
  rali/CMakeLists.txt
  rali/include/circular_buffer.h
  rali/include/image.h
  rali/include/image_loader_single_thread.h
  rali/include/image_read_and_decode.h
  rali/include/loader_module.h
  rali/include/master_graph.h
  rali/include/node_video_file_source.h
  rali/include/rali_api_data_loaders.h
  rali/include/rali_api_types.h
  rali/include/ring_buffer.h
  rali/include/video_loader_configs.h
  rali/include/video_loader_module.h
  rali/source/circular_buffer.cpp
  rali/source/image.cpp
  rali/source/image_loader_multi_thread.cpp
  rali/source/image_loader_single_thread.cpp
  rali/source/master_graph.cpp
  rali/source/node_video_file_source.cpp
  rali/source/rali_api.cpp
  rali/source/rali_api_data_loaders.cpp
  rali/source/ring_buffer.cpp
  rali/source/video_loader_module.cpp
Labels: bugfix, enhancement
