Repository ROCm/MIVisionX, pull requests merged in 2020-08, with the labels that each got.

#350 readme updates
  amd_openvx_extensions/amd_nn/README.md
  model_compiler/README.md
Labels: enhancement

#348 reduce min layer
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  amd_openvx_extensions/amd_nn/include/vx_amd_nn.h
  amd_openvx_extensions/amd_nn/src/kernels.cpp
  amd_openvx_extensions/amd_nn/src/kernels.h
  amd_openvx_extensions/amd_nn/src/reduce_min.cpp
  model_compiler/python/nnir.py
  model_compiler/python/nnir_to_openvx.py
  model_compiler/python/onnx_to_nnir.py
Labels: enhancement

#352 H/tile layer
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  amd_openvx_extensions/amd_nn/README.md
  amd_openvx_extensions/amd_nn/include/vx_amd_nn.h
  amd_openvx_extensions/amd_nn/src/kernels.cpp
  amd_openvx_extensions/amd_nn/src/kernels.h
  amd_openvx_extensions/amd_nn/src/tile_layer.cpp
  model_compiler/README.md
  model_compiler/python/nnir.py
  model_compiler/python/nnir_to_openvx.py
  model_compiler/python/onnx_to_nnir.py
Labels: enhancement

#355 CMakeLists & Setup Update
  CMakeLists.txt
  MIVisionX-setup.py
  README.md
  amd_openvx_extensions/CMakeLists.txt
Labels: bugfix, enhancement

#356 Project Readme Updates
  CMakeLists.txt
  README.md
  amd_openvx/README.md
  amd_openvx/openvx/README.md
  amd_openvx_extensions/README.md
  amd_openvx_extensions/amd_loomsl/README.md
  amd_openvx_extensions/amd_nn/README.md
  amd_openvx_extensions/amd_opencv/README.md
  amd_openvx_extensions/amd_rpp/README.md
  amd_openvx_extensions/amd_winml/README.md
  apps/README.md
  apps/bubble_pop/README.md
  apps/cloud_inference/README.md
  apps/dg_test/README.md
  apps/image_augmentation/README.md
  apps/mivisionx_inference_analyzer/README.md
  apps/mivisionx_openvx_classifier/README.md
  apps/mivisionx_validation_tool/README.md
  apps/mivisionx_winml_classifier/README.md
  apps/mivisionx_winml_yolov2/README.md
  docs/README.md
  model_compiler/README.md
  rali/README.md
  samples/README.md
  utilities/README.md
Labels: enhancement

#358 MIVisionX Online Documentation Fix
  README.md
  amd_openvx/README.md
  amd_openvx_extensions/amd_winml/README.md
  apps/README.md
  apps/cloud_inference/README.md
  model_compiler/README.md
  utilities/inference_generator/README.md
Labels: bugfix

#359 RPP Updates for PR #351
  MIVisionX-setup.py
  README.md
Labels: bugfix, enhancement
