Repository ROCm/MIVisionX, pull requests merged in 2020-12, with the labels that each got.

#401 CMakeList - cmake version update
  CMakeLists.txt
  amd_openvx/CMakeLists.txt
  amd_openvx/openvx/CMakeLists.txt
  amd_openvx_extensions/CMakeLists.txt
  amd_openvx_extensions/amd_loomsl/CMakeLists.txt
  amd_openvx_extensions/amd_media/CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  amd_openvx_extensions/amd_opencv/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  apps/CMakeLists.txt
  apps/bubble_pop/CMakeLists.txt
  apps/cloud_inference/server_app/CMakeLists.txt
  apps/image_augmentation/CMakeLists.txt
  apps/mivisionx_openvx_classifier/CMakeLists.txt
  model_compiler/python/nnir_to_clib.py
  model_compiler/python/nnir_to_openvx.py
  rali/CMakeLists.txt
  rali/rali/CMakeLists.txt
  rali/rali_pybind/CMakeLists.txt
  rali/rali_pybind/third_party_lib/CMakeLists.txt
  samples/c_samples/canny/CMakeLists.txt
  samples/c_samples/opencv_orb/CMakeLists.txt
  samples/inference/mv_objdetect/CMakeLists.txt
  samples/model_compiler_samples/CMakeLists.txt
  utilities/CMakeLists.txt
  utilities/inference_generator/CMakeLists.txt
  utilities/loom_io_media/CMakeLists.txt
  utilities/loom_shell/CMakeLists.txt
  utilities/mv_deploy/CMakeLists.txt
  utilities/rali/rali_basic_test/CMakeLists.txt
  utilities/rali/rali_dataloader/CMakeLists.txt
  utilities/rali/rali_dataloader_mt/CMakeLists.txt
  utilities/rali/rali_dataloader_tf/CMakeLists.txt
  utilities/rali/rali_performance_tests/CMakeLists.txt
  utilities/rali/rali_performance_tests_with_depth/CMakeLists.txt
  utilities/rali/rali_unittests/CMakeLists.txt
  utilities/runcl/CMakeLists.txt
  utilities/runvx/CMakeLists.txt
Labels: enhancement

#408 Updated x265 build instruction to skip cmake GUI
  MIVisionX-setup.py
Labels: enhancement

#406 Package update to support ROCm upgrade
  CMakeLists.txt
Labels: enhancement

#400 fixes for IEEE model
  model_compiler/README.md
  model_compiler/python/onnx_to_nnir.py
Labels: bugfix, enhancement

#409 Package Updates
  CMakeLists.txt
Labels: enhancement

#411 Setup Script - RHEL Support
  MIVisionX-setup.py
Labels: bugfix

#412 Setup - OpenCV with Display for RHEL
  MIVisionX-setup.py
Labels: enhancement

#413 CL Warning Fix - refactor PR #403
  amd_openvx/cmake/FindOpenCL.cmake
Labels: bugfix

#415 MIVisionX 1.9.5 Release Updates
  README.md
  rali/README.md
  tests/vision_tests/README.md
  tests/vision_tests/gdfs/17_fastCorners.gdf
  tests/vision_tests/gdfs/19_harrisCorners.gdf
  tests/vision_tests/runVisionTests.py
Labels: bugfix, enhancement
