Repository ROCm/MIVisionX, pull requests merged in 2021-02, with the labels that each got.

#437 Jenkins - MIVisionX Build,Install & Test
  .jenkins/common.groovy
  .jenkins/precheckin.groovy
Labels: enhancement

#438 fix for hang at the end for RALI app and training
  rali/rali/source/master_graph.cpp
  rali/rali/source/rali_api_info.cpp
  rali/rali_pybind/amd/rali/ops.py
Labels: bugfix

#439 Jenkins - Test Fix
  .jenkins/common.groovy
  .jenkins/precheckin.groovy
Labels: enhancement

#440 Jenkins - SLES OpenCL Fix & Update OS List
  .jenkins/common.groovy
  .jenkins/precheckin.groovy
  MIVisionX-setup.py
  amd_openvx/cmake/FindOpenCL.cmake
  amd_openvx/openvx/CMakeLists.txt
Labels: bugfix, enhancement

#441 Test - Installation Check
  .jenkins/common.groovy
  MIVisionX-setup.py
  README.md
  tests/library_tests/README.md
  tests/library_tests/runLibraryTests.py
Labels: enhancement
