Repository ROCm/MIVisionX, pull requests merged in 2021-05, with the labels that each got.

#494 rocAL - cifar10 reader update
  rocAL/rocAL/source/cifar10_data_reader.cpp
  rocAL/rocAL_pybind/amd/rali/ops.py
  rocAL/rocAL_pybind/amd/rali/types.py
  rocAL/rocAL_pybind/rali_pybind.cpp
  utilities/rali/rali_dataloader/rali_dataloader.cpp
Labels: enhancement

#496 Tests - update the readme for runVisionTests script
  tests/vision_tests/README.md
Labels: enhancement

#493 App Update to Python3 - MivisionX Inference Analyzer
  apps/mivisionx_inference_analyzer/inference_control.py
  apps/mivisionx_inference_analyzer/mivisionx_inference_analyzer.py
Labels: enhancement

#495 OpenVX HIP GPU backend - fix a bug for FastCorners kernels
  amd_openvx/openvx/ago/ago_kernel_api.cpp
  amd_openvx/openvx/ago/ago_util_hip.cpp
  amd_openvx/openvx/hipvx/hip_host_decls.h
  amd_openvx/openvx/hipvx/vision_kernels.cpp
Labels: bugfix

#497 OpenVX CTS - Enable testing FastCorners for HIP backend
  .jenkins/common.groovy
Labels: enhancement

#502 Setup - OpenCV install prefix
  MIVisionX-setup.py
  README.md
Labels: bugfix

#504 rocAL - brightness and seed fix.
  rocAL/rocAL/include/node_brightness.h
  rocAL/rocAL/include/rali_api_augmentation.h
  rocAL/rocAL/source/node_brightness.cpp
  rocAL/rocAL/source/parameter_factory.cpp
  rocAL/rocAL/source/rali_api_augmentation.cpp
Labels: bugfix

#507 openVX HIP GPU backend - fix a bug for Graph.GraphState test
  amd_openvx/openvx/ago/ago_interface.cpp
Labels: bugfix

#506 rocAL - Random BBox crop reader code clean up
  rocAL/rocAL/include/randombboxcrop_reader.h
  rocAL/rocAL/source/randombboxcrop_reader.cpp
  rocAL/rocAL_pybind/amd/rali/ops.py
Labels: enhancement

#508 OpenVX HIP GPU backend - fix a bug for WeightedAverage kernel
  amd_openvx/openvx/hipvx/arithmetic_kernels.cpp
  amd_openvx/openvx/hipvx/hip_common_funcs.h
Labels: bugfix

#505 OpenVX HIP GPU backend - Fix bugs for Remap kernels
  amd_openvx/openvx/hipvx/geometric_kernels.cpp
Labels: bugfix

#509 Docker - Dockerfiles update
  MIVisionX-setup.py
  README.md
  docker/centos7/level-4.dockerfile
  docker/centos8/level-4.dockerfile
  docker/mivisionx-on-centos7.dockerfile
  docker/mivisionx-on-centos8.dockerfile
  docker/mivisionx-on-ubuntu18.dockerfile
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/ubuntu18/level-4.dockerfile
  docker/ubuntu18/level-5.dockerfile
  docker/ubuntu20/level-4.dockerfile
  docker/ubuntu20/level-5.dockerfile
Labels: bugfix, enhancement

#503 OpenVX CTS - Enable WarpPerspective and ScaleImage tests for CI testing
  .jenkins/common.groovy
Labels: bugfix

#510 Enable GraphState/WeightedAverage/Remap for CI testing
  .jenkins/common.groovy
Labels: enhancement

#512 OpenVX HIP GPU backend - fix a bug for ScaleGaussianHalf5x5 kernel
  amd_openvx/openvx/hipvx/filter_kernels.cpp
Labels: bugfix

#511 OpenVX GPU backend - code clean up
  CMakeLists.txt
  amd_openvx/openvx/ago/ago_drama_alloc.cpp
  amd_openvx/openvx/ago/ago_interface.cpp
  amd_openvx/openvx/ago/ago_internal.h
  amd_openvx/openvx/ago/ago_util_hip.cpp
  amd_openvx/openvx/hipvx/CMakeLists.txt
Labels: enhancement
