Repository ROCm/MIVisionX, pull requests merged in 2021-08, with the labels that each got.

#584 MV_Deploy - Fix absolute path
  amd_openvx/openvx/CMakeLists.txt
  utilities/mv_deploy/CMakeLists.txt
Labels: bugfix

#587 Neural Network extension - HIP GPU backend - add support for tile layer
  amd_openvx_extensions/amd_nn/nn_hip/nn_hip_host_decls.h
  amd_openvx_extensions/amd_nn/nn_hip/nn_hip_kernels.cpp
  amd_openvx_extensions/amd_nn/src/tile_layer.cpp
Labels: enhancement

#590 Docker - CentOS 7 Fix
  docker/centos7/level-3.dockerfile
  docker/centos7/level-4.dockerfile
  docker/mivisionx-on-centos7.dockerfile
Labels: bugfix

#589 GPU OCL&HIP Backend - Color Convert Bug Fix
  amd_openvx/openvx/ago/ago_haf_gpu_conversion.cpp
  amd_openvx/openvx/hipvx/color_kernels.cpp
Labels: bugfix

#588 Bug Fix - topK layer
  amd_openvx_extensions/amd_nn/src/topk_layer.cpp
Labels: bugfix

#591 Docker - CentOS 7/8 MIVisionX Support Updates
  docker/centos7/level-1.dockerfile
  docker/centos7/level-2.dockerfile
  docker/centos7/level-3.dockerfile
  docker/centos7/level-4.dockerfile
  docker/centos8/level-1.dockerfile
  docker/centos8/level-2.dockerfile
  docker/centos8/level-3.dockerfile
  docker/centos8/level-4.dockerfile
  docker/mivisionx-on-centos7.dockerfile
  docker/mivisionx-on-centos8.dockerfile
Labels: enhancement, bugfix

#596 Issue 558 - vxMapRemapPatch.MapRandomRemap Random Failure Fix
  amd_openvx/openvx/ago/ago_kernel_api.cpp
  amd_openvx/openvx/ago/ago_platform.cpp
  amd_openvx/openvx/ago/ago_platform.h
Labels: bugfix

#598 OpenVX GPU backend - fix a regression for HarrisCorner node introduced by PR#596
  amd_openvx/openvx/ago/ago_drama_alloc.cpp
  amd_openvx/openvx/ago/ago_kernel_api.cpp
  amd_openvx/openvx/api/vx_api.cpp
Labels: bugfix

#595 Neural Network Extension - HIP GPU backend - add support for cast layer
  amd_openvx_extensions/amd_nn/nn_hip/nn_hip_host_decls.h
  amd_openvx_extensions/amd_nn/nn_hip/nn_hip_kernels.cpp
  amd_openvx_extensions/amd_nn/src/cast_layer.cpp
Labels: enhancement

#599 MIVisionX - Fix build issue
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/include/internal_publishKernels.h
  amd_openvx_extensions/amd_rpp/include/kernels_rpp.h
  amd_openvx_extensions/amd_rpp/include/vx_ext_rpp.h
  amd_openvx_extensions/amd_rpp/source/BilateralFilterbatchPD.cpp
  amd_openvx_extensions/amd_rpp/source/CannyEdgeDetector.cpp
  amd_openvx_extensions/amd_rpp/source/FastCornerDetector.cpp
  amd_openvx_extensions/amd_rpp/source/HarrisCornerDetector.cpp
  amd_openvx_extensions/amd_rpp/source/Histogram.cpp
  amd_openvx_extensions/amd_rpp/source/HuebatchPD.cpp
  amd_openvx_extensions/amd_rpp/source/LaplacianImagePyramid.cpp
  amd_openvx_extensions/amd_rpp/source/Remap.cpp
  amd_openvx_extensions/amd_rpp/source/SaturationbatchPD.cpp
  amd_openvx_extensions/amd_rpp/source/internal_publishKernels.cpp
  amd_openvx_extensions/amd_rpp/source/kernel_rpp.cpp
Labels: bugfix

#594 CI : OpenVX 1.3 Updates
  .jenkins/common.groovy
  .travis.yml
  amd_openvx_extensions/CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  utilities/CMakeLists.txt
Labels: enhancement

#603 CI:Jenkins - OpenVX 1.3 CTS Artifacts
  .jenkins/common.groovy
Labels: enhancement

#606 CI:Jenkins - Code Coverage
  .jenkins/common.groovy
  amd_openvx_extensions/amd_nn/CMakeLists.txt
Labels: enhancement

#610 Neural Network Extension - add support for finding the installed MIOPEN backend
  amd_openvx_extensions/CMakeLists.txt
Labels: enhancement, bugfix

#611 Docker - Updates & Bug Fix
  docker/centos7/level-1.dockerfile
  docker/centos7/level-2.dockerfile
  docker/centos7/level-3.dockerfile
  docker/centos7/level-4.dockerfile
  docker/centos8/level-1.dockerfile
  docker/centos8/level-2.dockerfile
  docker/centos8/level-3.dockerfile
  docker/centos8/level-4.dockerfile
  docker/mivisionx-on-centos7.dockerfile
  docker/mivisionx-on-centos8.dockerfile
  docker/mivisionx-on-ubuntu18.dockerfile
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/ubuntu18/level-1.dockerfile
  docker/ubuntu18/level-2.dockerfile
  docker/ubuntu18/level-3.dockerfile
  docker/ubuntu18/level-4.dockerfile
  docker/ubuntu18/level-5.dockerfile
  docker/ubuntu20/level-1.dockerfile
  docker/ubuntu20/level-2.dockerfile
  docker/ubuntu20/level-3.dockerfile
  docker/ubuntu20/level-4.dockerfile
  docker/ubuntu20/level-5.dockerfile
Labels: enhancement, bugfix

#612 SLES Support - Setup & CI
  .jenkins/common.groovy
  MIVisionX-setup.py
Labels: enhancement, bugfix
