Repository ROCm/MIVisionX, pull requests merged in 2021-06, with the labels that each got.

#514 OpenVX HIP GPU backend - code clean up
  amd_openvx/openvx/ago/ago_internal.h
  amd_openvx/openvx/ago/ago_util_hip.cpp
Labels: enhancement

#515 Docker - PyTorch Support
  docker/pytorch/mivisionx-with-pytorch.dockerfile
Labels: enhancement

#517 Boost Updates - MIOpen Install Fix
  MIVisionX-setup.py
  README.md
  docker/mivisionx-on-ubuntu18.dockerfile
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/ubuntu18/level-4.dockerfile
  docker/ubuntu18/level-5.dockerfile
  docker/ubuntu20/level-4.dockerfile
  docker/ubuntu20/level-5.dockerfile
Labels: bugfix

#520 PyTorch Docker - Updates
  docker/pytorch/mivisionx-with-pytorch.dockerfile
Labels: enhancement

#518 OpenVX HIP GPU backend - fix a bug for HalfScaleGaussian5x5
  amd_openvx/openvx/hipvx/filter_kernels.cpp
Labels: bugfix

#521 rocAL - pr513 override
  rocAL/rocAL/CMakeLists.txt
  rocAL/rocAL/include/master_graph.h
  rocAL/rocAL/include/meta_data.h
  rocAL/rocAL/include/meta_node.h
  rocAL/rocAL/include/meta_node_crop_mirror_normalize.h
  rocAL/rocAL/include/node_crop_mirror_normalize.h
  rocAL/rocAL/include/node_ssd_random_crop.h
  rocAL/rocAL/include/rali_api_meta_data.h
  rocAL/rocAL/include/randombboxcrop_meta_data.h
  rocAL/rocAL/include/randombboxcrop_meta_data_reader.h
  rocAL/rocAL/include/randombboxcrop_reader.h
  rocAL/rocAL/source/bounding_box_graph.cpp
  rocAL/rocAL/source/caffe2_meta_data_reader_detection.cpp
  rocAL/rocAL/source/caffe_meta_data_reader_detection.cpp
  rocAL/rocAL/source/coco_meta_data_reader.cpp
  rocAL/rocAL/source/fused_crop_decoder.cpp
  rocAL/rocAL/source/image_read_and_decode.cpp
  rocAL/rocAL/source/master_graph.cpp
  rocAL/rocAL/source/meta_node_crop.cpp
  rocAL/rocAL/source/meta_node_crop_mirror_normalize.cpp
  rocAL/rocAL/source/meta_node_crop_resize.cpp
  rocAL/rocAL/source/meta_node_flip.cpp
  rocAL/rocAL/source/meta_node_resize.cpp
  rocAL/rocAL/source/meta_node_resize_crop_mirror.cpp
  rocAL/rocAL/source/meta_node_rotate.cpp
  rocAL/rocAL/source/meta_node_ssd_random_crop.cpp
  rocAL/rocAL/source/node_ssd_random_crop.cpp
  rocAL/rocAL/source/rali_api_meta_data.cpp
  rocAL/rocAL/source/randombboxcrop_reader.cpp
  rocAL/rocAL/source/tf_meta_data_reader_detection.cpp
  rocAL/rocAL_pybind/amd/rali/ops.py
  rocAL/rocAL_pybind/example/coco_pipeline.py
Labels: bugfix

#524 SPACK Support - FindOpenCL - CL_TARGET_OPENCL_VERSION
  amd_openvx/cmake/FindOpenCL.cmake
Labels: enhancement

#528 OpenVX OCL GPU Backend – add support for WeightedAverage kernel
  amd_openvx/openvx/ago/ago_kernel_api.cpp
  amd_openvx/openvx/ago/ago_util_opencl.cpp
Labels: enhancement

#530 Readme updates
  README.md
  docs/images/OpenVX_logo.png
Labels: enhancement

#523 OpenVX HIP GPU backend - add support for scalar output sync
  amd_openvx/openvx/ago/ago_haf_gpu_corners.cpp
  amd_openvx/openvx/ago/ago_internal.h
  amd_openvx/openvx/ago/ago_kernel_api.cpp
  amd_openvx/openvx/ago/ago_util.cpp
  amd_openvx/openvx/ago/ago_util_hip.cpp
  amd_openvx/openvx/ago/ago_util_opencl.cpp
Labels: enhancement

#526 OpenVX OCL GPU backend - fix bugs for some of the color kernels
  amd_openvx/openvx/ago/ago_haf_gpu_conversion.cpp
Labels: bugfix, enhancement

#527 OpenVX HIP GPU backend - fix a bug for ColorKernels
  amd_openvx/openvx/hipvx/color_kernels.cpp
Labels: bugfix, enhancement

#531 CI - enable vxWeightedAverage(for OCL)/VirtualArray(for HIP)
  .jenkins/common.groovy
Labels: enhancement

#532 OpenCL Version - Fix
  amd_openvx/cmake/FindOpenCL.cmake
Labels: bugfix

#533 OpenVX OCL GPU backend - disable buffer merge for HarrisCorners
  amd_openvx/openvx/ago/ago_kernel_api.cpp
  amd_openvx/openvx/ago/ago_platform.cpp
  amd_openvx/openvx/ago/ago_platform.h
Labels: bugfix

#535 VxMapRemapPatch - Fix
  amd_openvx/openvx/ago/ago_kernel_list.cpp
Labels: bugfix

#536 CTS Bug Fix for vxCanny & Support for int16 Threshold data type
  amd_openvx/openvx/ago/ago_kernel_api.cpp
  amd_openvx/openvx/api/vx_api.cpp
Labels: bugfix, enhancement

#540 OpenVX HIP GPU backend - fix bugs for HarrisCorner3x3 kernels
  amd_openvx/openvx/ago/ago_kernel_api.cpp
  amd_openvx/openvx/hipvx/hip_host_decls.h
  amd_openvx/openvx/hipvx/vision_kernels.cpp
Labels: bugfix, enhancement

#543 OpenVX - Fix for VXU Link Error
  amd_openvx/openvx/CMakeLists.txt
  utilities/runvx/CMakeLists.txt
Labels: bugfix

#544 CI - Failure Bypass
  tests/vision_tests/runVisionTests.py
Labels: updates
