Repository ROCm/MIVisionX, pull requests merged in 2021-11, with the labels that each got.

#667 Docker - Ubuntu Updates
  docker/mivisionx-on-ubuntu18.dockerfile
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/ubuntu18/level-2.dockerfile
  docker/ubuntu18/level-3.dockerfile
  docker/ubuntu18/level-4.dockerfile
  docker/ubuntu18/level-5.dockerfile
  docker/ubuntu20/level-2.dockerfile
  docker/ubuntu20/level-3.dockerfile
  docker/ubuntu20/level-4.dockerfile
  docker/ubuntu20/level-5.dockerfile
Labels: enhancement

#668 Docker - RPP Update Version
  docker/mivisionx-on-ubuntu18.dockerfile
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/ubuntu18/level-5.dockerfile
  docker/ubuntu20/level-5.dockerfile
Labels: bugfix

#671 Windows - README updates
  README.md
  amd_openvx_extensions/amd_winml/README.md
Labels: enhancement, bugfix

#673 Include Path reorg
  amd_openvx_extensions/amd_media/CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
Labels: enhancement

#675 WinML apps - bug fixes
  amd_openvx/openvx/ago/ago_platform.h
  amd_openvx_extensions/amd_opencv/README.md
  amd_openvx_extensions/amd_winml/packages.config
  amd_openvx_extensions/amd_winml/utilities/MIVisionX-WinML-Validate/MIVisionX-WinML-Validate.vcxproj
  amd_openvx_extensions/amd_winml/vx_winml.vcxproj
  apps/mivisionx_winml_classifier/README.md
  apps/mivisionx_winml_yolov2/README.md
Labels: enhancement, bugfix

#676 Setup - MIOpen 2.14.0 Updates
  MIVisionX-setup.py
  README.md
Labels: enhancement

#678 OpenVX OCL GPU backend - Fix offset values for image/pyramid data types
  amd_openvx/openvx/ago/ago_util.cpp
Labels: bugfix

#680 Neural Network Extension - Add hip support for the Prior Box layer
  amd_openvx_extensions/amd_nn/nn_hip/nn_hip_host_decls.h
  amd_openvx_extensions/amd_nn/nn_hip/nn_hip_kernels.cpp
  amd_openvx_extensions/amd_nn/src/prior_box_layer.cpp
Labels: enhancement

#682 Docker - Updates & Bug Fixes
  docker/centos8/level-4.dockerfile
  docker/mivisionx-on-centos8.dockerfile
  docker/mivisionx-on-ubuntu18.dockerfile
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/ubuntu18/level-4.dockerfile
  docker/ubuntu18/level-5.dockerfile
  docker/ubuntu20/level-4.dockerfile
  docker/ubuntu20/level-5.dockerfile
Labels: enhancement, bugfix

#684 Neural Network extension, HIP GPU Backend - add support for the Concat layer
  amd_openvx_extensions/amd_nn/nn_hip/nn_hip_host_decls.h
  amd_openvx_extensions/amd_nn/nn_hip/nn_hip_kernels.cpp
  amd_openvx_extensions/amd_nn/src/concat_layer.cpp
  amd_openvx_extensions/amd_nn/src/permute_layer.cpp
  amd_openvx_extensions/amd_nn/src/prior_box_layer.cpp
Labels: enhancement

#685 Neural Network extension, HIP GPU backend - add support for the argmax layer
  amd_openvx_extensions/amd_nn/nn_hip/nn_hip_host_decls.h
  amd_openvx_extensions/amd_nn/nn_hip/nn_hip_kernels.cpp
  amd_openvx_extensions/amd_nn/src/argmax_layer.cpp
Labels: enhancement

#686 MV Compile - Update to Python3
  utilities/mv_deploy/mv_compile.cpp
Labels: bugfix

#688 add README for mv_deploy
  samples/inference/mv_objdetect/README.md
  utilities/mv_deploy/README.md
Labels: bugfix

#683 Fix build issues
  rocAL/rocAL/include/master_graph.h
  rocAL/rocAL/include/video_loader_module.h
  rocAL/rocAL/include/video_reader.h
  rocAL/rocAL/source/master_graph.cpp
Labels: enhancement, bugfix

#693 CI - CentOS 8 Updates
  .jenkins/common.groovy
Labels: bugfix

#690 added few optimizations for SSD
  rocAL/rocAL/include/master_graph.h
  rocAL/rocAL/source/bounding_box_graph.cpp
  rocAL/rocAL/source/master_graph.cpp
  rocAL/rocAL/source/rali_api_info.cpp
Labels: enhancement

#689 OpenVX - add support for writing the OpenVX GPU backend type into a header file
  amd_openvx/openvx/CMakeLists.txt
  amd_openvx/openvx/include/openvx_backend.h.in
Labels: enhancement

#691 NN model comiler - update the nnir_to_openvx script to detect the OpenVX backend
  model_compiler/python/nnir_to_openvx.py
Labels: enhancement

#696 Neural Network extension, HIP GPU backend - code clean up
  amd_openvx_extensions/amd_nn/nn_hip/nn_hip_kernels.cpp
Labels: enhancement

#697 MIVisionX - Updates
  README.md
  docs/images/MIVisionX.png
Labels: enhancement
