Repository ROCm/MIVisionX, pull requests merged in 2021-04, with the labels that each got.

#463 Dockers & CMake Updates
  .travis.yml
  MIVisionX-setup.py
  README.md
  amd_openvx/cmake/FindAMDRPP.cmake
  amd_openvx/cmake/FindFFmpeg.cmake
  amd_openvx/cmake/FindOpenCL.cmake
  amd_openvx/cmake/FindTurboJpeg.cmake
  amd_openvx_extensions/amd_media/CMakeLists.txt
  docker/centos8/level-1.dockerfile
  docker/centos8/level-2.dockerfile
  docker/centos8/level-3.dockerfile
  docker/centos8/level-4.dockerfile
  docker/mivisionx-on-ubuntu18.dockerfile
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/ubuntu18/level-5.dockerfile
  rali/rali/CMakeLists.txt
  rali/rali_pybind/CMakeLists.txt
Labels: bugfix, enhancement

#466 CMakeList - OpenCL_Support Variable FIX
  amd_openvx_extensions/CMakeLists.txt
  utilities/CMakeLists.txt
  utilities/runvx/CMakeLists.txt
Labels: bugfix

#468 2.0 Updates
  .jenkins/common.groovy
  MIVisionX-setup.py
  tests/neural_network_tests/runNeuralNetworkTests.py
Labels: enhancement

#469 CTS FIX - Seg Faults Fix
  .travis.yml
  README.md
  amd_openvx/openvx/ago/ago_interface.cpp
  tests/vision_tests/gdfs/37_tableLookup.gdf
  tests/vision_tests/gdfs/39_warpAffine.gdf
  tests/vision_tests/gdfs/40_warpPerspective.gdf
Labels: bugfix

#470 Jenkins - CPU/GPU 1.3 Conformance
  .jenkins/common.groovy
  .travis.yml
  README.md
Labels: enhancement

#473 VX_NN - MIOpen Version Update
  MIVisionX-setup.py
  README.md
Labels: enhancement

#472 rename some variables to have common names for both HIP/OCL GPU backends
  amd_openvx/openvx/ago/ago_drama_alloc.cpp
  amd_openvx/openvx/ago/ago_interface.cpp
  amd_openvx/openvx/ago/ago_internal.h
  amd_openvx/openvx/ago/ago_kernel_api.cpp
  amd_openvx/openvx/ago/ago_util.cpp
  amd_openvx/openvx/ago/ago_util_hip.cpp
  amd_openvx/openvx/ago/ago_util_opencl.cpp
  amd_openvx/openvx/api/vx_api.cpp
  amd_openvx/openvx/include/vx_ext_amd.h
  amd_openvx_extensions/amd_media/decoder.cpp
  amd_openvx_extensions/amd_media/encoder.cpp
  utilities/loom_io_media/decoder.cpp
  utilities/loom_io_media/encoder.cpp
  utilities/runvx/vxEngine.cpp
  utilities/runvx/vxUtils.cpp
Labels: enhancement

#475 RHEL - Support for setup and test
  MIVisionX-setup.py
  README.md
  tests/neural_network_tests/runNeuralNetworkTests.py
Labels: enhancement

#476 add support for VX_DIRECTIVE_AMD_COPY_TO_HIPMEM for HIP backend
  amd_openvx/openvx/ago/ago_interface.cpp
Labels: enhancement

#477 fix rali_unittest compiler warnings
  utilities/rali/rali_unittests/rali_unittests.cpp
Labels: enhancement

#479 OpenVX HIP GPU backend - convolution kernels
  amd_openvx/openvx/ago/ago_kernel_api.cpp
  amd_openvx/openvx/hipvx/filter_kernels.cpp
Labels: bugfix

#480 OpenVX HIP GPU backend - fix OpenVX CTS failures for Gaussian3x3 test
  amd_openvx/openvx/hipvx/filter_kernels.cpp
Labels: bugfix

#481 Jenkins - OpenVX Conformance Log
  .jenkins/common.groovy
Labels: enhancement

#482 OpenVX HIP GPU backend - fix Canny3x3
  amd_openvx/openvx/hipvx/vision_kernels.cpp
Labels: bugfix

#484 OpenVX HIP GPU backend - fix seg fault in FastCorners with suppression
  amd_openvx/openvx/ago/ago_kernel_api.cpp
  amd_openvx/openvx/hipvx/hip_host_decls.h
  amd_openvx/openvx/hipvx/vision_kernels.cpp
Labels: bugfix

#483 OpenVX HIP GPU backend - add Canny5x5/Canny7x7
  amd_openvx/openvx/hipvx/hip_common_funcs.h
  amd_openvx/openvx/hipvx/vision_kernels.cpp
Labels: enhancement

#485 CI - HIP Support
  .jenkins/common.groovy
  tests/vision_tests/runVisionTests.py
Labels: enhancement

#487 Update README.md
  rocAL/rocAL_pybind/README.md
Labels: enhancement

#489 Model Compiler - OpenCL Find Fix
  model_compiler/python/nnir_to_openvx.py
Labels: bugfix

#490 rocAL - Pybind build issue fix
  rocAL/README.md
  rocAL/rocAL_pybind/CMakeLists.txt
  rocAL/rocAL_pybind/setup.py
Labels: bugfix

#491 OpenVX gdf test - add gdfs for several convolution sizes
  tests/openvx_node_tests/kernelGDFs/filter/Convolve_S16_U8_5x5.gdf
  tests/openvx_node_tests/kernelGDFs/filter/Convolve_S16_U8_7x7.gdf
  tests/openvx_node_tests/kernelGDFs/filter/Convolve_S16_U8_9x9.gdf
  tests/openvx_node_tests/kernelGDFs/filter/Convolve_U8_U8_5x5.gdf
  tests/openvx_node_tests/kernelGDFs/filter/Convolve_U8_U8_7x7.gdf
  tests/openvx_node_tests/kernelGDFs/filter/Convolve_U8_U8_9x9.gdf
Labels: enhancement

#492 OpenVX HIP GPU backend - fix a bug in convolution kernels
  amd_openvx/openvx/ago/ago_kernel_api.cpp
  amd_openvx/openvx/hipvx/filter_kernels.cpp
  amd_openvx/openvx/hipvx/hip_host_decls.h
Labels: bugfix
