Repository ROCm/MIVisionX, pull requests merged in 2021-07, with the labels that each got.

#545 CI Failure Bypass - Remove test case to unblock
  tests/vision_tests/runVisionTests.py
Labels: updates

#547 OpenVX HIP GPU backend - add support for HarrisCorner5x5/7x7 kernels
  amd_openvx/openvx/hipvx/vision_kernels.cpp
Labels: enhancement

#553 runvx HIP backend - fix a linking issue
  utilities/runvx/CMakeLists.txt
Labels: bugfix

#550 CI Updates - Tests
  .jenkins/common.groovy
Labels: enhancement

#551 Update level-2.dockerfile
  docker/ubuntu20/level-2.dockerfile
Labels: bugfix

#554 CMake HIP backend - remove unnecessary linking
  amd_openvx/openvx/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  rocAL/rocAL_pybind/CMakeLists.txt
Labels: enhancement

#556 Readme - instructions for building HIP backend.
  README.md
Labels: enhancement

#555 amd_rpp - force gpu affinity to cpu for running without codegen
  amd_openvx_extensions/amd_rpp/source/BrightnessbatchPD.cpp
  amd_openvx_extensions/amd_rpp/source/ResizebatchPD.cpp
Labels: bugfix

#557 Deps Update - Use Release Tag for ROCM-CMAKE
  MIVisionX-setup.py
  README.md
  docker/centos7/level-4.dockerfile
  docker/centos8/level-4.dockerfile
  docker/mivisionx-on-centos7.dockerfile
  docker/mivisionx-on-centos8.dockerfile
  docker/mivisionx-on-ubuntu18.dockerfile
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/ubuntu18/level-4.dockerfile
  docker/ubuntu18/level-5.dockerfile
  docker/ubuntu20/level-4.dockerfile
  docker/ubuntu20/level-5.dockerfile
Labels: bugfix, enhancement

#525 SSD Accuracy Fix
  rocAL/rocAL/include/bounding_box_graph.h
  rocAL/rocAL/include/cifar10_data_loader.h
  rocAL/rocAL/include/circular_buffer.h
  rocAL/rocAL/include/image_loader.h
  rocAL/rocAL/include/image_loader_sharded.h
  rocAL/rocAL/include/image_read_and_decode.h
  rocAL/rocAL/include/loader_module.h
  rocAL/rocAL/include/meta_data_graph.h
  rocAL/rocAL/include/randombboxcrop_meta_data_reader.h
  rocAL/rocAL/include/randombboxcrop_reader.h
  rocAL/rocAL/source/bounding_box_graph.cpp
  rocAL/rocAL/source/cifar10_data_loader.cpp
  rocAL/rocAL/source/circular_buffer.cpp
  rocAL/rocAL/source/coco_file_source_reader.cpp
  rocAL/rocAL/source/fused_crop_decoder.cpp
  rocAL/rocAL/source/image_loader.cpp
  rocAL/rocAL/source/image_loader_sharded.cpp
  rocAL/rocAL/source/image_read_and_decode.cpp
  rocAL/rocAL/source/master_graph.cpp
  rocAL/rocAL/source/randombboxcrop_reader.cpp
  rocAL/rocAL_pybind/amd/rali/plugin/pytorch.py
  rocAL/rocAL_pybind/amd/rali/plugin/tf.py
  rocAL/rocAL_pybind/example/caffe2_reader.py
  rocAL/rocAL_pybind/example/caffe_reader.py
  rocAL/rocAL_pybind/example/coco_pipeline.py
  rocAL/rocAL_pybind/example/tf_classification_pipeline.py
  rocAL/rocAL_pybind/example/tf_detection_pipeline.py
  rocAL/rocAL_pybind/example/tf_pipeline.py
Labels: bugfix

#559 Readme - Updates
  README.md
Labels: enhancement

#563 GCC 9 - CPU Warning Fix
  amd_openvx/openvx/api/vx_api.cpp
Labels: bugfix, enhancement

#560 VisionTest HIP GPU backend - Fix a segfault for opticalFlowLK gdf test
  amd_openvx/openvx/ago/ago_kernel_api.cpp
  amd_openvx/openvx/hipvx/filter_kernels.cpp
  amd_openvx/openvx/hipvx/hip_host_decls.h
Labels: bugfix

#564 rocal_pybind - fix for package link error
  rocAL/rocAL_pybind/CMakeLists.txt
Labels: bugfix

#567 rocAL_pybind - CMakeList: add finalized install path
  rocAL/rocAL_pybind/CMakeLists.txt
Labels: bugfix

#569 Backend Support - AMD EXT Expanded Support
  CMakeLists.txt
  amd_openvx_extensions/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  rocAL/rocAL/CMakeLists.txt
  rocAL/rocAL/rocAL_hip/CMakeLists.txt
  utilities/CMakeLists.txt
Labels: bugfix, enhancement

#574 rocAL Pybind - Temp Fix
  rocAL/rocAL_pybind/CMakeLists.txt
Labels: bugfix

#570 Cast Layer - adding validate support
  amd_openvx_extensions/amd_nn/src/cast_layer.cpp
Labels: enhancement

#568 Neural Network Extension - add CMake support for HIP GPU backend
  amd_openvx_extensions/CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  amd_openvx_extensions/amd_nn/nn_hip/CMakeLists.txt
  amd_openvx_extensions/amd_nn/nn_hip/nn_hip_host_decls.h
  amd_openvx_extensions/amd_nn/nn_hip/nn_hip_kernels.cpp
Labels: enhancement

#581 Docker Updates
  README.md
  amd_openvx/openvx/CMakeLists.txt
  amd_openvx_extensions/CMakeLists.txt
  docker/README.md
  docker/centos7/level-1.dockerfile
  docker/centos7/level-2.dockerfile
  docker/centos7/level-3.dockerfile
  docker/centos7/level-4.dockerfile
  docker/centos8/level-1.dockerfile
  docker/centos8/level-2.dockerfile
  docker/centos8/level-3.dockerfile
  docker/centos8/level-4.dockerfile
  docker/mivisionx-on-centos7.dockerfile
  docker/mivisionx-on-centos8.dockerfile
  docker/mivisionx-on-ubuntu18.dockerfile
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/pytorch/mivisionx-with-pytorch.dockerfile
  docker/ubuntu18/level-1.dockerfile
  docker/ubuntu18/level-2.dockerfile
  docker/ubuntu18/level-3.dockerfile
  docker/ubuntu18/level-4.dockerfile
  docker/ubuntu18/level-5.dockerfile
  docker/ubuntu20/level-1.dockerfile
  docker/ubuntu20/level-2.dockerfile
  docker/ubuntu20/level-3.dockerfile
  docker/ubuntu20/level-4.dockerfile
  docker/ubuntu20/level-5.dockerfile
  rocAL/rocAL/CMakeLists.txt
  utilities/CMakeLists.txt
Labels: enhancement

#582 VX_NN - Issue #577 Fix
  apps/dg_test/annmodule.cpp
  apps/mivisionx_openvx_classifier/include/caffeModels.h
Labels: bugfix

#579 coco meta_data_reader update for SSD
  rocAL/rocAL/include/caffe2_meta_data_reader.h
  rocAL/rocAL/include/caffe2_meta_data_reader_detection.h
  rocAL/rocAL/include/caffe_meta_data_reader.h
  rocAL/rocAL/include/caffe_meta_data_reader_detection.h
  rocAL/rocAL/include/coco_file_source_reader.h
  rocAL/rocAL/include/coco_meta_data_reader.h
  rocAL/rocAL/include/image_source_evaluator.h
  rocAL/rocAL/include/meta_data_reader.h
  rocAL/rocAL/include/node_fused_jpeg_crop.h
  rocAL/rocAL/include/node_fused_jpeg_crop_single_shard.h
  rocAL/rocAL/include/node_image_loader.h
  rocAL/rocAL/include/node_image_loader_single_shard.h
  rocAL/rocAL/include/reader.h
  rocAL/rocAL/source/coco_file_source_reader.cpp
  rocAL/rocAL/source/coco_meta_data_reader.cpp
  rocAL/rocAL/source/node_fused_jpeg_crop.cpp
  rocAL/rocAL/source/node_fused_jpeg_crop_single_shard.cpp
  rocAL/rocAL/source/node_image_loader.cpp
  rocAL/rocAL/source/node_image_loader_single_shard.cpp
  rocAL/rocAL/source/rali_api_data_loaders.cpp
Labels: enhancement

#575 Neural Network Extension, HIP GPU backend - add support for gather layer
  amd_openvx/openvx/ago/ago_platform.h
  amd_openvx_extensions/amd_nn/src/gather_layer.cpp
  amd_openvx_extensions/amd_nn/src/kernels.cpp
  amd_openvx_extensions/amd_nn/src/kernels.h
Labels: enhancement

#576 added HIP backend for activation layer
  amd_openvx_extensions/amd_nn/src/activation_layer.cpp
Labels: enhancement
