Repository ROCm/MIVisionX, pull requests merged in 2021-03, with the labels that each got.

#444 OpenCV decoder support and TJ partial decoding with scale
  MIVisionX-setup.py
  apps/image_augmentation/image_augmentation.cpp
  rali/rali/CMakeLists.txt
  rali/rali/include/decoder.h
  rali/rali/include/image_read_and_decode.h
  rali/rali/include/image_source_evaluator.h
  rali/rali/include/log.h
  rali/rali/include/open_cv_decoder.h
  rali/rali/include/rali_api_data_loaders.h
  rali/rali/include/rali_api_types.h
  rali/rali/include/turbo_jpeg_decoder.h
  rali/rali/source/decoder_factory.cpp
  rali/rali/source/image_read_and_decode.cpp
  rali/rali/source/open_cv_decoder.cpp
  rali/rali/source/rali_api_data_loaders.cpp
  rali/rali/source/turbo_jpeg_decoder.cpp
  rali/rali_pybind/rali_pybind.cpp
Labels: enhancement

#447 Jenkins - Artifacts
  .jenkins/common.groovy
  tests/library_tests/runLibraryTests.py
  tests/neural_network_tests/runNeuralNetworkTests.py
  tests/vision_tests/runVisionTests.py
Labels: enhancement

#448 Docker - Ubuntu DockerFiles Added
  README.md
  docker/README.md
  docker/mivisionx-on-ubuntu18.dockerfile
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/ubuntu18/level-1.dockerfile
  docker/ubuntu18/level-2.dockerfile
  docker/ubuntu18/level-3.dockerfile
  docker/ubuntu18/level-4.dockerfile
  docker/ubuntu18/level-5.dockerfile
Labels: enhancement

#449 GPU Flow - color convert - RGB output cases
  amd_openvx/openvx/ago/ago_haf_gpu_conversion.cpp
Labels: bugfix

#450 MIVisionX Setup Updates
  CMakeLists.txt
  MIVisionX-setup.py
Labels: enhancement

#452 OpenVX Core - Channel Combine GPU
  amd_openvx/openvx/ago/ago_util_opencl.cpp
Labels: bugfix

#451 Jenkins Updates
  .jenkins/common.groovy
Labels: bugfix, enhancement

#455 RunVX - border mode on command line functionality
  utilities/runvx/vxEngine.cpp
  utilities/runvx/vxEngine.h
Labels: enhancement

#453 CentOS - Find Package Fix & Docker Files
  MIVisionX-setup.py
  amd_openvx/cmake/FindAMDRPP.cmake
  amd_openvx/cmake/FindFFmpeg.cmake
  amd_openvx/cmake/FindOpenCL.cmake
  amd_openvx/cmake/FindTurboJpeg.cmake
  docker/README.md
  docker/centos7/level-1.dockerfile
  docker/centos7/level-2.dockerfile
  docker/centos7/level-3.dockerfile
  docker/centos7/level-4.dockerfile
  docker/mivisionx-on-centos7.dockerfile
Labels: enhancement

#461 OpenVX 1.3 & Extensions - Latest Headers
  amd_openvx/openvx/api/vx_api.cpp
  amd_openvx/openvx/include/VX/vx.h
  amd_openvx/openvx/include/VX/vx_api.h
  amd_openvx/openvx/include/VX/vx_compatibility.h
  amd_openvx/openvx/include/VX/vx_import.h
  amd_openvx/openvx/include/VX/vx_kernels.h
  amd_openvx/openvx/include/VX/vx_khr_buffer_aliasing.h
  amd_openvx/openvx/include/VX/vx_khr_class.h
  amd_openvx/openvx/include/VX/vx_khr_icd.h
  amd_openvx/openvx/include/VX/vx_khr_import_kernel.h
  amd_openvx/openvx/include/VX/vx_khr_ix.h
  amd_openvx/openvx/include/VX/vx_khr_nn.h
  amd_openvx/openvx/include/VX/vx_khr_opencl_interop.h
  amd_openvx/openvx/include/VX/vx_khr_pipelining.h
  amd_openvx/openvx/include/VX/vx_khr_tiling.h
  amd_openvx/openvx/include/VX/vx_khr_user_data_object.h
  amd_openvx/openvx/include/VX/vx_khr_xml.h
  amd_openvx/openvx/include/VX/vx_nodes.h
  amd_openvx/openvx/include/VX/vx_types.h
  amd_openvx/openvx/include/VX/vx_vendors.h
  amd_openvx/openvx/include/VX/vxu.h
  amd_openvx/openvx/include/vx_ext_amd.h
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  amd_openvx_extensions/amd_nn/src/detection_output.cpp
  amd_openvx_extensions/amd_nn/src/kernels.cpp
  amd_openvx_extensions/amd_nn/src/kernels.h
  amd_openvx_extensions/amd_nn/src/nms_layer.cpp
  amd_openvx_extensions/amd_nn/src/reduce_min.cpp
  amd_openvx_extensions/amd_nn/src/topk_layer.cpp
  amd_openvx_extensions/amd_winml/source/internal_dataTranslator.cpp
  amd_openvx_extensions/amd_winml/source/winML_getTopKLabels.cpp
  apps/cloud_inference/server_app/inference.cpp
  apps/dg_test/DGtest.cpp
  apps/dg_test/annmodule.cpp
  apps/mivisionx_openvx_classifier/source/caffeModels.cpp
  apps/mivisionx_openvx_classifier/source/classifier.cpp
  apps/mivisionx_winml_classifier/classifier.cpp
  apps/mivisionx_winml_yolov2/source/AnnieYoloDetect.cpp
  model_compiler/python/nnir_to_clib.py
  model_compiler/python/nnir_to_openvx.py
  samples/model_compiler_samples/source/classifier.cpp
  utilities/inference_generator/src/caffe2openvx.cpp
  utilities/inference_generator/src/nnef2openvx.cpp
  utilities/runvx/vxTensor.cpp
Labels: bugfix, enhancement
