Repository ROCm/MIVisionX, pull requests merged in 2021-09, with the labels that each got.

#613 Neural Network extension - find OCL/HIP packages before finding MIOPEN package
  amd_openvx_extensions/CMakeLists.txt
Labels: enhancement

#614 Setup - Updates
  .jenkins/common.groovy
  MIVisionX-setup.py
  README.md
Labels: enhancement, bugfix, New Feature

#615 Issue #585: VX_NN - Link With MIOpen & MIOpenGEMM -- Fix
  .jenkins/common.groovy
  CMakeLists.txt
  amd_openvx/openvx/CMakeLists.txt
Labels: bugfix

#616 SLES - NN Flow Fix
  MIVisionX-setup.py
  README.md
  amd_openvx/cmake/FindOpenCL.cmake
  model_compiler/python/nnir_to_openvx.py
Labels: bugfix

#617 Neural Network Extension - find/link MIOpenGEMM only for OCL GPU backend
  amd_openvx_extensions/CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  apps/CMakeLists.txt
Labels: enhancement, bugfix

#618 Issue #458 Fix - GNU 9.3.0: Warnings & Error Handling
  amd_openvx/openvx/ago/ago_internal.h
  amd_openvx_extensions/amd_loomsl/live_stitch_api.cpp
  amd_openvx_extensions/amd_nn/src/kernels.cpp
Labels: bugfix

#620 OpenVX HIP GPU backend - fix failures reported in issue #566 for HIP backend
  amd_openvx/openvx/ago/ago_kernel_api.cpp
  amd_openvx/openvx/hipvx/geometric_kernels.cpp
  amd_openvx/openvx/hipvx/hip_common_funcs.h
  amd_openvx/openvx/hipvx/hip_host_decls.h
Labels: bugfix

#623 ADAT - Classification Sample Added
  toolkit/amd_data_analysis_toolkit/classification/.gitignore
  toolkit/amd_data_analysis_toolkit/classification/sample/AMD-tinyDataSet-val.txt
  toolkit/amd_data_analysis_toolkit/classification/sample/hierarchy.csv
  toolkit/amd_data_analysis_toolkit/classification/sample/inceptionV4-results.csv
  toolkit/amd_data_analysis_toolkit/classification/sample/labels.txt
Labels: enhancement, bugfix

#604 OpenVX HIP GPU Backend - Fix for vxReplicateNode
  amd_openvx/openvx/ago/ago_drama_divide.cpp
  amd_openvx/openvx/ago/ago_interface.cpp
  amd_openvx/openvx/ago/ago_kernel_api.cpp
  amd_openvx/openvx/api/vx_api.cpp
  amd_openvx/openvx/api/vxu.cpp
  amd_openvx/openvx/hipvx/geometric_kernels.cpp
  amd_openvx/openvx/hipvx/hip_host_decls.h
Labels: enhancement, bugfix

#624 OpenVX HIP backend - bug fix - RGB to YUV4 &RGBX to YUV4
  amd_openvx/openvx/hipvx/color_kernels.cpp
Labels: bugfix

#625 OpenVX - Documentation
  README.md
  amd_openvx/README.md
  amd_openvx/openvx/README.md
Labels: enhancement

#626 OpenVX HIP GPU backend - fix an uninitialized variable warning
  amd_openvx/openvx/hipvx/geometric_kernels.cpp
Labels: bugfix

#622 rocAL - python package improvisation wrt installation
  rocAL/rocAL_pybind/README.md
  rocAL/rocAL_pybind/run.sh
Labels: enhancement

#628 Setup Script - Python3 & Python2 Support
  MIVisionX-setup.py
  README.md
Labels: enhancement, bugfix

#619 Neural Network Extension, HIP GPU backend - add support for layers that use MIOpen
  amd_openvx_extensions/amd_nn/nn_hip/nn_hip_host_decls.h
  amd_openvx_extensions/amd_nn/nn_hip/nn_hip_kernels.cpp
  amd_openvx_extensions/amd_nn/src/batch_normalization_layer.cpp
  amd_openvx_extensions/amd_nn/src/cast_layer.cpp
  amd_openvx_extensions/amd_nn/src/convolution_layer.cpp
  amd_openvx_extensions/amd_nn/src/deconvolution_layer.cpp
  amd_openvx_extensions/amd_nn/src/fully_connected_layer.cpp
  amd_openvx_extensions/amd_nn/src/gather_layer.cpp
  amd_openvx_extensions/amd_nn/src/image_tensor_converter.cpp
  amd_openvx_extensions/amd_nn/src/kernels.cpp
  amd_openvx_extensions/amd_nn/src/kernels.h
  amd_openvx_extensions/amd_nn/src/local_response_normalization_layer.cpp
  amd_openvx_extensions/amd_nn/src/normalization_layer.cpp
  amd_openvx_extensions/amd_nn/src/pooling_layer.cpp
  amd_openvx_extensions/amd_nn/src/reshape_layer.cpp
  amd_openvx_extensions/amd_nn/src/scale_layer.cpp
  amd_openvx_extensions/amd_nn/src/softmax_layer.cpp
  amd_openvx_extensions/amd_nn/src/tensor_add.cpp
  amd_openvx_extensions/amd_nn/src/tensor_image_converter.cpp
  amd_openvx_extensions/amd_nn/src/tensor_matrix_multiply.cpp
  amd_openvx_extensions/amd_nn/src/tensor_max.cpp
  amd_openvx_extensions/amd_nn/src/tensor_min.cpp
  amd_openvx_extensions/amd_nn/src/tensor_multiply.cpp
  amd_openvx_extensions/amd_nn/src/tensor_subtract.cpp
  amd_openvx_extensions/amd_nn/src/tile_layer.cpp
Labels: enhancement, New Feature

#630 OpenVX 1.3 - HIP Backend - Harris Corner Bug Fix
  amd_openvx/openvx/hipvx/vision_kernels.cpp
Labels: bugfix

#627 vxCreateUniformImage API - adding support for VX_DF_IMAGE_U8
  amd_openvx/openvx/api/vx_api.cpp
Labels: enhancement

#633 Fix Windows build
  amd_openvx/openvx/ago/ago_platform.cpp
  amd_openvx/openvx/openvx.vcxproj
  amd_openvx/openvx/openvx.vcxproj.filters
Labels: enhancement, bugfix

#629 Jenkins - MIVisionX HIP Backend on Ubuntu20 & CentOS 8
  .jenkins/common.groovy
  MIVisionX-setup.py
  README.md
  amd_openvx_extensions/CMakeLists.txt
  rocAL/rocAL/CMakeLists.txt
  rocAL/rocAL_pybind/CMakeLists.txt
Labels: enhancement

#637 MIVisionX Package - Set dependency on rocm-core
  CMakeLists.txt
Labels: enhancement
