Repository ROCm/MIVisionX, pull requests merged in 2021-01, with the labels that each got.

#417 1.9.5 Updates
  .github/info.plist
  CMakeLists.txt
  README.md
Labels: enhancement

#404 model compiler: py2to3
  model_compiler/python/caffe_pb2.py
  model_compiler/python/caffe_to_nnir.py
  model_compiler/python/nnef_to_nnir.py
  model_compiler/python/nnir.py
  model_compiler/python/nnir_to_clib.py
  model_compiler/python/nnir_to_nnef.py
  model_compiler/python/nnir_to_openvx.py
  model_compiler/python/nnir_update.py
  model_compiler/python/onnx_to_nnir.py
Labels: enhancement

#380 Update Readme for NNEF
  model_compiler/README.md
Labels: enhancement, high

#419 Lintian Fix
  CMakeLists.txt
  amd_openvx/openvx/CMakeLists.txt
  amd_openvx_extensions/amd_loomsl/CMakeLists.txt
  amd_openvx_extensions/amd_media/CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  amd_openvx_extensions/amd_opencv/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  apps/cloud_inference/server_app/CMakeLists.txt
  copyright.txt
  rali/rali/CMakeLists.txt
  rali/rali_pybind/CMakeLists.txt
  utilities/inference_generator/CMakeLists.txt
  utilities/loom_shell/CMakeLists.txt
  utilities/mv_deploy/CMakeLists.txt
  utilities/runcl/CMakeLists.txt
  utilities/runvx/CMakeLists.txt
Labels: bugfix

#421 fix for ubuntu20.04 warning
  rali/rali/source/graph.cpp
Labels: enhancement

#423 Build Fix - Release/Debug
  CMakeLists.txt
  README.md
  amd_openvx/README.md
  amd_openvx/openvx/CMakeLists.txt
  amd_openvx_extensions/README.md
  amd_openvx_extensions/amd_loomsl/CMakeLists.txt
  amd_openvx_extensions/amd_media/CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  amd_openvx_extensions/amd_opencv/CMakeLists.txt
  amd_openvx_extensions/amd_opencv/README.md
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/README.md
  apps/cloud_inference/server_app/CMakeLists.txt
  docs/build-levels.md
  rali/rali/CMakeLists.txt
  rali/rali_pybind/CMakeLists.txt
  utilities/inference_generator/CMakeLists.txt
  utilities/loom_shell/CMakeLists.txt
  utilities/mv_deploy/CMakeLists.txt
  utilities/runcl/CMakeLists.txt
  utilities/runvx/CMakeLists.txt
  utilities/runvx/README.md
Labels: enhancement

#418 Model Compiler README updates
  model_compiler/README.md
Labels: enhancement

#424 MIVisionX 1.9.6
  CMakeLists.txt
  README.md
  amd_openvx/README.md
  amd_openvx_extensions/amd_opencv/README.md
  amd_openvx_extensions/amd_rpp/README.md
Labels: enhancement

#426 Jenkins Infrastructure
  .jenkins/common.groovy
  .jenkins/precheckin.groovy
  .travis.yml
  CMakeLists.txt
  tests/README.md
  tests/neural_network_tests/README.md
  tests/neural_network_tests/models/caffe-mnist/model.caffemodel
  tests/neural_network_tests/models/nnef-mnist/graph.nnef
  tests/neural_network_tests/models/nnef-mnist/input.dat
  tests/neural_network_tests/models/nnef-mnist/output.dat
  tests/neural_network_tests/models/nnef-mnist/variable1.dat
  tests/neural_network_tests/models/nnef-mnist/variable2.dat
  tests/neural_network_tests/models/nnef-mnist/variable3.dat
  tests/neural_network_tests/models/nnef-mnist/variable4.dat
  tests/neural_network_tests/models/nnef-mnist/variable5.dat
  tests/neural_network_tests/models/nnef-mnist/variable6.dat
  tests/neural_network_tests/models/onnx-mnist/model.onnx
  tests/neural_network_tests/models/onnx-mnist/test_data_set_0/input_0.pb
  tests/neural_network_tests/models/onnx-mnist/test_data_set_0/output_0.pb
  tests/neural_network_tests/models/onnx-mnist/test_data_set_1/input_0.pb
  tests/neural_network_tests/models/onnx-mnist/test_data_set_1/output_0.pb
  tests/neural_network_tests/models/onnx-mnist/test_data_set_2/input_0.pb
  tests/neural_network_tests/models/onnx-mnist/test_data_set_2/output_0.pb
  tests/neural_network_tests/runNeuralNetworkTests.py
  tests/vision_tests/README.md
  tests/vision_tests/runVisionTests.py
Labels: enhancement

#431 Test - updates
  README.md
  tests/README.md
  tests/neural_network_tests/README.md
  tests/neural_network_tests/runNeuralNetworkTests.py
  tests/vision_tests/runVisionTests.py
Labels: bugfix, enhancement

#433 updated smoke tests to Python 3
  tests/smoke_tests/Inference/inference-measure-accuracy.py
  tests/smoke_tests/Inference/inference-parse-perf-dump.py
  tests/smoke_tests/Inference/inference-performance-accuracy.py
  tests/smoke_tests/Inference/inference-test.py
Labels: enhancement

#435 Test updates - NN Test & Vision Tests
  tests/neural_network_tests/README.md
  tests/neural_network_tests/runNeuralNetworkTests.py
  tests/vision_tests/runVisionTests.py
Labels: enhancement

#434 Rr/rali failed training fix
  apps/image_augmentation/image_augmentation.cpp
  rali/rali/source/file_source_reader.cpp
  rali/rali/source/label_reader_folders.cpp
Labels: bugfix

#436 fixes FP16 bug(SWDEV-270422) & getbuffer errors(SWDEV-270424)
  model_compiler/python/nnir.py
  model_compiler/python/nnir_to_openvx.py
Labels: bugfix
