Repository ROCm/MIVisionX, pull requests merged in 2022-10, with the labels that each got.

#964 AMD Media Decoder - Measure Decode Time
  amd_openvx_extensions/amd_media/decoder.cpp
Labels: enhancement, bugfix

#959 rocAL - Changing Python Lib Path
  rocAL/rocAL_pybind/run.sh
Labels: enhancement

#967 CMakeList Updates
  CMakeLists.txt
  MIVisionX-setup.py
  amd_openvx/openvx/CMakeLists.txt
  amd_openvx_extensions/amd_custom/custom_lib/CMakeLists.txt
  amd_openvx_extensions/amd_loomsl/CMakeLists.txt
  amd_openvx_extensions/amd_media/CMakeLists.txt
  amd_openvx_extensions/amd_migraphx/CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  amd_openvx_extensions/amd_opencv/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  rocAL/rocAL/CMakeLists.txt
  rocAL/rocAL_pybind/CMakeLists.txt
  utilities/CMakeLists.txt
  utilities/rocAL/rocAL_dataloader_mt/CMakeLists.txt
  utilities/runvx/CMakeLists.txt
Labels: enhancement, bugfix

#950 rocAL - Resize scaling modes support
  rocAL/rocAL/include/api/rocal_api_augmentation.h
  rocAL/rocAL/include/api/rocal_api_types.h
  rocAL/rocAL/include/augmentations/geometry_augmentations/node_resize.h
  rocAL/rocAL/source/api/rocal_api_augmentation.cpp
  rocAL/rocAL/source/augmentations/geometry_augmentations/node_resize.cpp
  rocAL/rocAL_pybind/amd/rocal/fn.py
  rocAL/rocAL_pybind/example/new_api/rocAL_api_python_unittest.py
  rocAL/rocAL_pybind/rocal_pybind.cpp
Labels: enhancement, bugfix

#968 rocAL - fix for copy-write violation
  rocAL/rocAL_pybind/example/new_api/parse_config.py
  rocAL/rocAL_pybind/example/new_api/rocAL_api_caffe_reader.py
Labels: enhancement

#972 rocAL - add missing header
  CHANGELOG.md
  README.md
  rocAL/rocAL/include/device/device_manager_hip.h
Labels: bugfix

#970 amd_openvx - increase max tensor dimension
  amd_openvx/openvx/ago/ago_internal.h
Labels: enhancement, New Feature

#974 AMD Media Decoder - Added timing measurement to decoder looping option
  amd_openvx_extensions/amd_media/decoder.cpp
Labels: enhancement

#976 [Vision tests] - add a new gdf test for scaling an NV12 image and converting it to an RGB image
  tests/vision_tests/gdfs/42_scale_nv12_to_rgb.gdf
  tests/vision_tests/gdfs/inputs/dino_1280x720.nv12
  tests/vision_tests/gdfs/openvx_test_results/.gitkeep
Labels: enhancement

#978 RPP - Update version
  CHANGELOG.md
  CMakeLists.txt
  MIVisionX-setup.py
  README.md
Labels: enhancement

#960 rocAL - Resize tensor Updates
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/include/internal_publishKernels.h
  amd_openvx_extensions/amd_rpp/include/kernels_rpp.h
  amd_openvx_extensions/amd_rpp/include/vx_ext_rpp.h
  amd_openvx_extensions/amd_rpp/source/Resizetensor.cpp
  amd_openvx_extensions/amd_rpp/source/internal_publishKernels.cpp
  amd_openvx_extensions/amd_rpp/source/kernel_rpp.cpp
  rocAL/rocAL/source/augmentations/geometry_augmentations/node_resize.cpp
  rocAL/rocAL_pybind/amd/rocal/types.py
Labels: enhancement

#984 migraphx - palamida scan fix
  tests/amd_migraphx_tests/gdf/image-4.png
  tests/amd_migraphx_tests/gdf/image_0.jpg
  tests/amd_migraphx_tests/gdf/image_1.jpg
  tests/amd_migraphx_tests/gdf/image_4.jpg
  tests/amd_migraphx_tests/gdf/mnist_migraphx.gdf
Labels: enhancement

#989 Readme updates - OpenVX Trademark Updates
  README.md
  amd_openvx/README.md
  amd_openvx/openvx/README.md
  amd_openvx_extensions/README.md
  amd_openvx_extensions/amd_custom/README.md
  amd_openvx_extensions/amd_media/README.md
  amd_openvx_extensions/amd_migraphx/README.md
  amd_openvx_extensions/amd_opencv/README.md
  amd_openvx_extensions/amd_rpp/README.md
  docs/README.md
  tests/README.md
  tests/amd_opencv_tests/README.md
  tests/openvx_node_tests/README.md
Labels: enhancement

#990 Media - License Issue Fix
  data/videos/test.mp4
  tests/amd_media_tests/README.md
  tests/amd_media_tests/gdf/data/test.mp4
  tests/amd_media_tests/gdf/data/test.yuv
  tests/amd_media_tests/gdf/decoder.gdf
  tests/amd_media_tests/gdf/encoder.gdf
Labels: enhancement, bugfix

#979 runVisionTest - add a new test
  tests/vision_tests/runVisionTests.py
Labels: enhancement

#982 rocAL - Changes in run.sh file to uninstall & then install the Wheel
  rocAL/rocAL_pybind/run.sh
Labels: enhancement

#983 amd media - device support
  amd_openvx_extensions/amd_media/decoder.cpp
  amd_openvx_extensions/amd_media/include/vx_amd_media.h
Labels: enhancement

#986 docker update - rpp version update
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/mivisionx-opencl-on-ubuntu20.dockerfile
  docker/pytorch/mivisionx-with-pytorch.dockerfile
  docker/tensorflow/mivisionx-with-tensorflow.dockerfile
  docker/ubuntu20/level-5.dockerfile
Labels: enhancement

#981 rocal - README updates and directory name change
  rocAL/docs/examples/pytorch/README.md
  rocAL/rocAL_pybind/README.md
  rocAL/rocAL_pybind/examples/PYTHON_UNITTEST_TEST_FILE.sh
  rocAL/rocAL_pybind/examples/READERS_TEST_FILE.sh
  rocAL/rocAL_pybind/examples/README.md
  rocAL/rocAL_pybind/examples/parse_config.py
  rocAL/rocAL_pybind/examples/rocAL_api_caffe2_reader.py
  rocAL/rocAL_pybind/examples/rocAL_api_caffe_reader.py
  rocAL/rocAL_pybind/examples/rocAL_api_coco_pipeline.py
  rocAL/rocAL_pybind/examples/rocAL_api_python_unittest.py
  rocAL/rocAL_pybind/examples/rocAL_api_tf_classification_reader.py
  rocAL/rocAL_pybind/examples/rocAL_api_tf_detection_pipeline.py
  rocAL/rocAL_pybind/examples/rocAL_api_video_pipeline.py
  rocAL/rocAL_pybind/examples/tf_petsTrainingExample/README.md
  rocAL/rocAL_pybind/examples/tf_petsTrainingExample/download_and_preprocess_dataset.sh
  rocAL/rocAL_pybind/examples/tf_petsTrainingExample/train_withROCAL_withTFRecordReader.py
  utilities/rocAL/rocAL_unittests/README.md
Labels: enhancement
