Repository ROCm/MIVisionX, pull requests merged in 2022-08, with the labels that each got.

#913 HIP Bin prefix path updated to rocm_path as per reorg structure
  amd_openvx/CMakeLists.txt
  amd_openvx_extensions/CMakeLists.txt
  amd_openvx_extensions/amd_migraphx/CMakeLists.txt
  apps/cloud_inference/server_app/CMakeLists.txt
  rocAL/rocAL/CMakeLists.txt
  rocAL/rocAL_pybind/CMakeLists.txt
  utilities/CMakeLists.txt
Labels: enhancement

#916 Rocal updates: name changes and pytorch training example
  README.md
  rocAL/docs/README.md
  rocAL/docs/examples/pytorch/test_training.py
  rocAL/rocAL/include/decoders/video/hw_jpeg_decoder.h
  rocAL/rocAL/source/decoders/image/decoder_factory.cpp
  rocAL/rocAL/source/decoders/video/hw_jpeg_decoder.cpp
Labels: enhancement

#918 Revert PR 894 -- "rocAL - Changes for classification "
  .gitignore
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/include/internal_publishKernels.h
  amd_openvx_extensions/amd_rpp/include/kernels_rpp.h
  amd_openvx_extensions/amd_rpp/include/vx_ext_rpp.h
  amd_openvx_extensions/amd_rpp/source/Resizetensor.cpp
  amd_openvx_extensions/amd_rpp/source/internal_publishKernels.cpp
  amd_openvx_extensions/amd_rpp/source/kernel_rpp.cpp
  rocAL/rocAL/include/api/rocal_api_augmentation.h
  rocAL/rocAL/include/api/rocal_api_info.h
  rocAL/rocAL/include/augmentations/geometry_augmentations/node_resize_shorter.h
  rocAL/rocAL/include/decoders/image/decoder.h
  rocAL/rocAL/include/decoders/image/fused_crop_decoder.h
  rocAL/rocAL/include/decoders/image/open_cv_decoder.h
  rocAL/rocAL/include/decoders/image/turbo_jpeg_decoder.h
  rocAL/rocAL/include/decoders/video/hw_jpeg_decoder.h
  rocAL/rocAL/include/parameters/parameter_crop.h
  rocAL/rocAL/source/api/rocal_api_augmentation.cpp
  rocAL/rocAL/source/api/rocal_api_data_loaders.cpp
  rocAL/rocAL/source/api/rocal_api_info.cpp
  rocAL/rocAL/source/augmentations/geometry_augmentations/node_crop.cpp
  rocAL/rocAL/source/augmentations/geometry_augmentations/node_resize.cpp
  rocAL/rocAL/source/augmentations/geometry_augmentations/node_resize_shorter.cpp
  rocAL/rocAL/source/decoders/image/fused_crop_decoder.cpp
  rocAL/rocAL/source/decoders/image/open_cv_decoder.cpp
  rocAL/rocAL/source/decoders/image/turbo_jpeg_decoder.cpp
  rocAL/rocAL/source/loaders/image/image_read_and_decode.cpp
  rocAL/rocAL/source/parameters/parameter_rali_crop.cpp
  rocAL/rocAL/source/pipeline/image.cpp
  rocAL/rocAL/source/pipeline/ring_buffer.cpp
  rocAL/rocAL_pybind/amd/rocal/decoders.py
  rocAL/rocAL_pybind/amd/rocal/fn.py
  rocAL/rocAL_pybind/amd/rocal/pipeline.py
  rocAL/rocAL_pybind/amd/rocal/readers.py
  rocAL/rocAL_pybind/example/new_api/PYTHON_UNITTEST_TEST_FILE.sh
  rocAL/rocAL_pybind/example/new_api/rocAL_api_python_unittest.py
  rocAL/rocAL_pybind/rocal_pybind.cpp
  utilities/rocAL/rocAL_dataloader/CMakeLists.txt
  utilities/rocAL/rocAL_dataloader_mt/CMakeLists.txt
  utilities/rocAL/rocAL_performance_tests/CMakeLists.txt
Labels: bugfix

#920 [rocAL] Fix rocAL Pybind build issue.
  rocAL/rocAL_pybind/CMakeLists.txt
Labels: bugfix

#919 AMD RPP - updates for ROCm Re-Org
  CHANGELOG.md
  CMakeLists.txt
  MIVisionX-setup.py
  README.md
  amd_openvx/cmake/FindAMDRPP.cmake
  amd_openvx_extensions/CMakeLists.txt
  amd_openvx_extensions/amd_media/CMakeLists.txt
  amd_openvx_extensions/amd_opencv/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  apps/cloud_inference/server_app/CMakeLists.txt
  apps/image_augmentation/CMakeLists.txt
  apps/image_augmentation/README.md
  apps/mivisionx_openvx_classifier/CMakeLists.txt
  apps/mivisionx_validation_tool/README.md
  docker/mivisionx-on-ubuntu18.dockerfile
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/mivisionx-opencl-on-ubuntu18.dockerfile
  docker/mivisionx-opencl-on-ubuntu20.dockerfile
  docker/pytorch/mivisionx-with-pytorch.dockerfile
  docker/ubuntu18/level-5.dockerfile
  docker/ubuntu20/level-5.dockerfile
  docker/zenDNN/zenDNN-HIP.dockerfile
  rocAL/rocAL/CMakeLists.txt
  rocAL/rocAL_pybind/CMakeLists.txt
  rocAL/rocAL_pybind/README.md
  samples/inference/mv_objdetect/CMakeLists.txt
  tests/openvx_node_tests/runvxTestAllScript.sh
  tests/smoke_tests/RALI/RALI-UNITTEST-CPU.sh
  tests/smoke_tests/RALI/RALI-UNITTEST-GPU.sh
  tests/smoke_tests/rocAL/rocAL-unittest-CPU.sh
  tests/smoke_tests/rocAL/rocAL-unittest-GPU.sh
  utilities/mv_deploy/CMakeLists.txt
  utilities/rocAL/rocAL_dataloader/README.md
  utilities/rocAL/rocAL_dataloader_mt/README.md
  utilities/rocAL/rocAL_dataloader_tf/README.md
Labels: enhancement, bugfix

#922 [CMAKE] Updated default HSA Path to new/current install prefix path
  amd_openvx/openvx/CMakeLists.txt
  amd_openvx_extensions/CMakeLists.txt
  amd_openvx_extensions/amd_media/CMakeLists.txt
  amd_openvx_extensions/amd_migraphx/CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  rocAL/rocAL/CMakeLists.txt
  rocAL/rocAL_pybind/CMakeLists.txt
  utilities/rocAL/rocAL_dataloader_mt/CMakeLists.txt
  utilities/runvx/CMakeLists.txt
Labels: enhancement

#924 Zen DNN - Docker & Tests
  CMakeLists.txt
  docker/zenDNN/zenDNN-cpu-only.dockerfile
  docker/zenDNN/zenDNN-gpu-hip.dockerfile
  tests/README.md
  tests/zen_dnn_tests/README.md
  tests/zen_dnn_tests/conv/CMakeLists.txt
  tests/zen_dnn_tests/conv/source/zen-dnn-conv.cpp
  tests/zen_dnn_tests/mnist/CMakeLists.txt
  tests/zen_dnn_tests/mnist/source/mnist_caffe_f32.cpp
  tests/zen_dnn_tests/mnist_app/CMakeLists.txt
  tests/zen_dnn_tests/mnist_app/data/images/image-1.png
  tests/zen_dnn_tests/mnist_app/data/images/image-3.png
  tests/zen_dnn_tests/mnist_app/data/images/image-4.png
  tests/zen_dnn_tests/mnist_app/data/images/image-5.png
  tests/zen_dnn_tests/mnist_app/data/images/input_data_3.bin
  tests/zen_dnn_tests/mnist_app/data/images/input_data_4.bin
  tests/zen_dnn_tests/mnist_app/data/images/input_data_5.bin
  tests/zen_dnn_tests/mnist_app/data/weights.bin
  tests/zen_dnn_tests/mnist_app/source/mnist_caffe_f32.cpp
Labels: enhancement

#921 Rocal Updates
  docker/tensorflow/mivisionx-with-tensorflow.dockerfile
  rocAL/docs/examples/pytorch/test_training.py
  rocAL/rocAL_pybind/amd/rocal/pipeline.py
  rocAL/rocAL_pybind/amd/rocal/plugin/tf.py
  rocAL/rocAL_pybind/example/new_api/tf_petsTrainingExample/README.md
  rocAL/rocAL_pybind/example/new_api/tf_petsTrainingExample/download_and_preprocess_dataset.sh
  rocAL/rocAL_pybind/example/new_api/tf_petsTrainingExample/train_withROCAL_withTFRecordReader.py
  rocAL/rocAL_pybind/run.sh
Labels: enhancement

#928 Lk/docker update
  docker/mivisionx-on-ubuntu18.dockerfile
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/mivisionx-opencl-on-ubuntu18.dockerfile
  docker/mivisionx-opencl-on-ubuntu20.dockerfile
  docker/pytorch/mivisionx-with-pytorch.dockerfile
  docker/ubuntu18/level-5.dockerfile
  docker/ubuntu20/level-5.dockerfile
  docker/zenDNN/zenDNN-gpu-hip.dockerfile
Labels: enhancement

#925 AMD OpenVX custom extension implementation
  amd_openvx_extensions/CMakeLists.txt
  amd_openvx_extensions/amd_custom/CMakeLists.txt
  amd_openvx_extensions/amd_custom/CustomNode.md
  amd_openvx_extensions/amd_custom/README.md
  amd_openvx_extensions/amd_custom/custom_lib/CMakeLists.txt
  amd_openvx_extensions/amd_custom/custom_lib/custom_api.cpp
  amd_openvx_extensions/amd_custom/custom_lib/custom_api.h
  amd_openvx_extensions/amd_custom/custom_lib/custom_copy_impl.cpp
  amd_openvx_extensions/amd_custom/custom_lib/custom_copy_impl.h
  amd_openvx_extensions/amd_custom/custom_lib/custom_template.h
  amd_openvx_extensions/amd_custom/include/vx_amd_custom.h
  amd_openvx_extensions/amd_custom/source/custom_kernels.cpp
  amd_openvx_extensions/amd_custom/source/custom_layer.cpp
  amd_openvx_extensions/amd_custom/source/kernels.h
Labels: enhancement

#929 update readme for amd_migraphx extension
  README.md
  amd_openvx_extensions/README.md
  amd_openvx_extensions/amd_migraphx/README.md
Labels: enhancement

#935 amd_custom - fixes build issue
  amd_openvx_extensions/amd_custom/custom_lib/CMakeLists.txt
Labels: bugfix
