Repository ROCm/MIVisionX, pull requests merged in 2022-07, with the labels that each got.

#887 rocAL - Unit Test Fix
  amd_openvx/README.md
  amd_openvx/openvx/ago/ago_util_hip.cpp
  amd_openvx/openvx/ago/ago_util_opencl.cpp
  utilities/rocAL/rocAL_performance_tests_with_depth/CMakeLists.txt
  utilities/rocAL/rocAL_performance_tests_with_depth/rocAL_performance_tests_with_depth.cpp
  utilities/rocAL/rocAL_unittests/rocAL_unittests.cpp
  utilities/rocAL/rocAL_video_unittests/rocAL_video_unittests.cpp
Labels: bugfix

#888 Cleanup & remove old files
  README.md
  utilities/README.md
  utilities/mv_deploy/README.md
  utilities/rali/rali_performance_tests_with_depth/CMakeLists.txt
  utilities/rali/rali_unittests/rali_unittests.cpp
  utilities/rali/rali_video_unittests/CMakeLists.txt
Labels: enhancement, bugfix

#890 Fix warning for building rocAL and NN extension with ROCm5.2+
  amd_openvx_extensions/amd_nn/src/tensor_matrix_multiply.cpp
  rocAL/rocAL/include/api/rocal_api_types.h
  rocAL/rocAL/rocAL_hip/rocal_hip_kernels.cpp
  rocAL/rocAL/source/meta_data/coco_meta_data_reader.cpp
  rocAL/rocAL/source/pipeline/master_graph.cpp
Labels: bugfix

#891 ZenDNN - Docker Files
  amd_openvx/openvx/ago/ago_util_opencl.cpp
  docker/zenDNN/zenDNN-HIP.dockerfile
  docker/zenDNN/zenDNN-cpu-only.dockerfile
Labels: enhancement

#897 ROCm 5.2 - Updates (#893)
  CHANGELOG.md
  MIVisionX-setup.py
  README.md
  amd_openvx/cmake/FindOpenCL.cmake
  apps/cloud_inference/server_app/cmake/FindOpenCL.cmake
  docker/conformance/openvx-1-3-on-ubuntu18.dockerfile
  docker/conformance/openvx-1-3-on-ubuntu20.dockerfile
  docker/mivisionx-on-ubuntu18.dockerfile
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/mivisionx-opencl-on-ubuntu18.dockerfile
  docker/mivisionx-opencl-on-ubuntu20.dockerfile
  docker/ubuntu18/level-2.dockerfile
  docker/ubuntu18/level-3.dockerfile
  docker/ubuntu18/level-4.dockerfile
  docker/ubuntu18/level-5.dockerfile
  docker/ubuntu20/level-2.dockerfile
  docker/ubuntu20/level-3.dockerfile
  docker/ubuntu20/level-4.dockerfile
  docker/ubuntu20/level-5.dockerfile
  docker/zenDNN/zenDNN-HIP.dockerfile
  model_compiler/python/nnir_to_openvx.py
  tests/library_tests/runLibraryTests.py
  tests/vision_tests/runVisionTests.py
Labels: enhancement, bugfix

#900 Docker - Updates to half & Pytorch install
  docker/mivisionx-on-ubuntu18.dockerfile
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/mivisionx-opencl-on-ubuntu18.dockerfile
  docker/mivisionx-opencl-on-ubuntu20.dockerfile
  docker/pytorch/mivisionx-with-pytorch.dockerfile
  docker/ubuntu18/level-4.dockerfile
  docker/ubuntu18/level-5.dockerfile
  docker/ubuntu20/level-4.dockerfile
  docker/ubuntu20/level-5.dockerfile
  docker/zenDNN/zenDNN-HIP.dockerfile
Labels: enhancement, bugfix

#901 Fix HIP Backend issues in unit test
  utilities/rocAL/rocAL_basic_test/rocAL_basic_test.cpp
  utilities/rocAL/rocAL_dataloader/rocAL_dataloader.cpp
  utilities/rocAL/rocAL_dataloader_tf/rocAL_dataloader_tf.cpp
  utilities/rocAL/rocAL_unittests/rocAL_unittests.cpp
  utilities/rocAL/rocAL_video_unittests/rocAL_video_unittests.cpp
Labels: enhancement, bugfix

#902 Apps - validation app - name change from rali to rocal
  apps/mivisionx_validation_tool/README.md
  apps/mivisionx_validation_tool/data/images/rocal-white.png
  apps/mivisionx_validation_tool/data/images/rocal.png
  apps/mivisionx_validation_tool/inference_control.py
  apps/mivisionx_validation_tool/inference_setup.py
  apps/mivisionx_validation_tool/inference_viewer.py
  apps/mivisionx_validation_tool/inference_viewer.ui
  apps/mivisionx_validation_tool/mivisionx_validation_tool.py
  apps/mivisionx_validation_tool/rocal_setup.py
Labels: enhancement, bugfix

#905 MIVisionX - Release Updates
  README.md
  amd_openvx/CMakeLists.txt
  amd_openvx/cmake/FindFFmpeg.cmake
  amd_openvx/openvx/CMakeLists.txt
  amd_openvx/openvx/hipvx/CMakeLists.txt
  amd_openvx_extensions/amd_loomsl/CMakeLists.txt
  amd_openvx_extensions/amd_media/CMakeLists.txt
  amd_openvx_extensions/amd_migraphx/CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  amd_openvx_extensions/amd_opencv/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  apps/bubble_pop/CMakeLists.txt
  apps/cloud_inference/server_app/CMakeLists.txt
  apps/image_augmentation/CMakeLists.txt
  apps/optical_flow/CMakeLists.txt
  docker/conformance/system_info.py
  model_compiler/python/nnir_to_clib.py
  model_compiler/python/nnir_to_openvx.py
  rocAL/rocAL/CMakeLists.txt
  rocAL/rocAL/rocAL_hip/CMakeLists.txt
  rocAL/rocAL_pybind/CMakeLists.txt
  samples/c_samples/canny/CMakeLists.txt
  samples/c_samples/opencv_orb/CMakeLists.txt
  samples/inference/mv_objdetect/CMakeLists.txt
  samples/model_compiler_samples/CMakeLists.txt
  tests/neural_network_tests/runNeuralNetworkTests.py
  tests/vision_tests/runVisionTests.py
  utilities/CMakeLists.txt
  utilities/inference_generator/CMakeLists.txt
  utilities/inference_generator/src/caffe2openvx.cpp
  utilities/inference_generator/src/nnef2openvx.cpp
  utilities/loom_io_media/CMakeLists.txt
  utilities/loom_shell/CMakeLists.txt
  utilities/mv_deploy/CMakeLists.txt
  utilities/rocAL/rocAL_basic_test/CMakeLists.txt
  utilities/rocAL/rocAL_dataloader/CMakeLists.txt
  utilities/rocAL/rocAL_dataloader_mt/CMakeLists.txt
  utilities/rocAL/rocAL_dataloader_tf/CMakeLists.txt
  utilities/rocAL/rocAL_performance_tests/CMakeLists.txt
  utilities/rocAL/rocAL_performance_tests_with_depth/CMakeLists.txt
  utilities/rocAL/rocAL_unittests/CMakeLists.txt
  utilities/rocAL/rocAL_video_unittests/CMakeLists.txt
  utilities/runcl/CMakeLists.txt
  utilities/runvx/CMakeLists.txt
Labels: enhancement, bugfix

#909 amd_nn - Warning Fixes
  amd_openvx/openvx/ago/ago_util_hip.cpp
  amd_openvx_extensions/amd_nn/src/convolution_layer.cpp
  amd_openvx_extensions/amd_nn/src/detection_output.cpp
  amd_openvx_extensions/amd_nn/src/nms_layer.cpp
Labels: bugfix

#912 RPP - Version Update
  CHANGELOG.md
  MIVisionX-setup.py
  README.md
  docker/mivisionx-on-ubuntu18.dockerfile
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/mivisionx-opencl-on-ubuntu18.dockerfile
  docker/mivisionx-opencl-on-ubuntu20.dockerfile
  docker/pytorch/mivisionx-with-pytorch.dockerfile
  docker/ubuntu18/level-5.dockerfile
  docker/ubuntu20/level-5.dockerfile
  docker/zenDNN/zenDNN-HIP.dockerfile
Labels: enhancement, bugfix

#896 Fix CMakeLists install dir & Warnings
  rocAL/rocAL/include/decoders/image/fused_crop_decoder.h
  rocAL/rocAL/include/decoders/image/turbo_jpeg_decoder.h
  rocAL/rocAL/include/decoders/video/hw_jpeg_decoder.h
  rocAL/rocAL/include/loaders/video/video_loader.h
  rocAL/rocAL/include/meta_data/caffe2_meta_data_reader.h
  rocAL/rocAL/include/meta_data/caffe2_meta_data_reader_detection.h
  rocAL/rocAL/include/meta_data/caffe_meta_data_reader.h
  rocAL/rocAL/include/meta_data/caffe_meta_data_reader_detection.h
  rocAL/rocAL/include/meta_data/cifar10_meta_data_reader.h
  rocAL/rocAL/include/meta_data/coco_meta_data_reader.h
  rocAL/rocAL/include/meta_data/coco_meta_data_reader_key_points.h
  rocAL/rocAL/include/meta_data/label_reader_folders.h
  rocAL/rocAL/include/meta_data/meta_node_resize.h
  rocAL/rocAL/include/meta_data/mxnet_meta_data_reader.h
  rocAL/rocAL/include/meta_data/text_file_meta_data_reader.h
  rocAL/rocAL/include/meta_data/tf_meta_data_reader.h
  rocAL/rocAL/include/meta_data/tf_meta_data_reader_detection.h
  rocAL/rocAL/include/meta_data/video_label_reader.h
  rocAL/rocAL/include/pipeline/context.h
  rocAL/rocAL/include/pipeline/master_graph.h
  rocAL/rocAL/include/readers/image/coco_file_source_reader.h
  rocAL/rocAL/include/readers/image/file_source_reader.h
  rocAL/rocAL/include/readers/image/tf_record_reader.h
  rocAL/rocAL/include/readers/video/sequence_file_source_reader.h
  rocAL/rocAL/include/readers/video/video_file_source_reader.h
  rocAL/rocAL/source/pipeline/master_graph.cpp
  utilities/rocAL/rocAL_dataloader/rocAL_dataloader.cpp
  utilities/rocAL/rocAL_unittests/rocAL_unittests.cpp
Labels: enhancement, bugfix

#914 implemented fix for Harris Corners bug in HIP
  amd_openvx/openvx/ago/ago_kernel_api.cpp
  amd_openvx/openvx/hipvx/hip_host_decls.h
  amd_openvx/openvx/hipvx/vision_kernels.cpp
Labels: bugfix
