Repository ROCm/MIVisionX, pull requests merged in 2022-02, with the labels that each got.

#747 apps - update the dg_test and mivisionx_openvx_classifier apps to find the OpenCL package only if the OpenVX backend is OCL
  apps/dg_test/CMakeLists.txt
  apps/mivisionx_openvx_classifier/CMakeLists.txt
Labels: enhancement, updates

#733 rocAL - Changes in rali_unittests.cpp
  utilities/rali/rali_unittests/rali_unittests.cpp
Labels: enhancement

#732 VX_NN - vxTensorCompare node implementation
  CHANGELOG.md
  amd_openvx/openvx/ago/ago_util.cpp
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  amd_openvx_extensions/amd_nn/README.md
  amd_openvx_extensions/amd_nn/include/vx_amd_nn.h
  amd_openvx_extensions/amd_nn/nn_hip/nn_hip_host_decls.h
  amd_openvx_extensions/amd_nn/nn_hip/nn_hip_kernels.cpp
  amd_openvx_extensions/amd_nn/src/kernels.cpp
  amd_openvx_extensions/amd_nn/src/kernels.h
  amd_openvx_extensions/amd_nn/src/tensor_compare.cpp
  model_compiler/README.md
  model_compiler/python/nnir.py
  model_compiler/python/nnir_to_openvx.py
  model_compiler/python/onnx_to_nnir.py
Labels: enhancement, New Feature

#749 VX_OpenCV - OpenCV V4.X Support
  CMakeLists.txt
  amd_openvx/CMakeLists.txt
  amd_openvx/cmake/FindAMDRPP.cmake
  amd_openvx/cmake/FindFFmpeg.cmake
  amd_openvx/cmake/FindOpenCL.cmake
  amd_openvx/cmake/FindTurboJpeg.cmake
  amd_openvx/openvx/CMakeLists.txt
  amd_openvx_extensions/CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  amd_openvx_extensions/amd_opencv/CMakeLists.txt
  amd_openvx_extensions/amd_opencv/include/internal_opencvTunnel.h
  amd_openvx_extensions/amd_opencv/include/vx_ext_opencv.h
  amd_openvx_extensions/amd_opencv/source/OpenCV_orbCompute.cpp
  amd_openvx_extensions/amd_opencv/source/OpenCV_orbDetector.cpp
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  apps/CMakeLists.txt
  rocAL/rocAL/CMakeLists.txt
  rocAL/rocAL_pybind/CMakeLists.txt
  utilities/CMakeLists.txt
  utilities/runvx/CMakeLists.txt
  utilities/runvx/vxUtils.h
Labels: enhancement, New Feature

#751 Changelog - Updates
  CHANGELOG.md
Labels: enhancement

#754 Apps - Inference Server App Fix
  apps/cloud_inference/server_app/CMakeLists.txt
Labels: bugfix

#756 Changelog Updates
  CHANGELOG.md
Labels: enhancement

#757 VX_Pop - Updates
  apps/bubble_pop/CMakeLists.txt
  apps/bubble_pop/include/internal_opencvTunnel.h
  apps/bubble_pop/include/internal_publishKernels.h
  apps/bubble_pop/include/vx_ext_pop.h
  apps/bubble_pop/include/vx_pop.h
  apps/bubble_pop/source/AMD_VX_Pop_Bubble.cpp
  apps/bubble_pop/source/AMD_VX_Pop_Donut.cpp
  apps/bubble_pop/source/AMD_app.cpp
  apps/bubble_pop/source/internal_dataTranslator.cpp
  apps/bubble_pop/source/internal_publishKernels.cpp
  apps/bubble_pop/source/internal_vxNodes.cpp
Labels: enhancement

#753 amd_media - update for GPU mode
  amd_openvx/openvx/ago/ago_interface.cpp
  amd_openvx_extensions/amd_media/README.md
  amd_openvx_extensions/amd_media/decoder.cpp
  amd_openvx_extensions/amd_media/encoder.cpp
  amd_openvx_extensions/amd_media/include/vx_amd_media.h
Labels: enhancement

#760 App Updates
  apps/bubble_pop/source/AMD_app.cpp
  apps/bubble_pop/source/internal_dataTranslator.cpp
Labels: enhancement

#762 VX_NN - bug fix
  amd_openvx_extensions/amd_nn/include/vx_amd_nn.h
Labels: bugfix

#748 MIVisionX Backend - Default GPU backend: HIP
  .jenkins/common.groovy
  CMakeLists.txt
  MIVisionX-setup.py
  README.md
  amd_openvx_extensions/CMakeLists.txt
  rocAL/rocAL/CMakeLists.txt
Labels: enhancement

#763 Tests: runVisionTests - enable more tests
  tests/vision_tests/runVisionTests.py
Labels: enhancement

#764 ROCm 5.0.0 - Release Updates
  CHANGELOG.md
  README.md
  apps/bubble_pop/README.md
  apps/optical_flow/README.md
  docker/README.md
Labels: enhancement, bugfix

#729 rocAL - MXNet Record Reader Support for Image Classification
  rocAL/rocAL/include/master_graph.h
  rocAL/rocAL/include/meta_data_reader.h
  rocAL/rocAL/include/mxnet_meta_data_reader.h
  rocAL/rocAL/include/mxnet_recordio_reader.h
  rocAL/rocAL/include/rali_api_data_loaders.h
  rocAL/rocAL/include/rali_api_meta_data.h
  rocAL/rocAL/include/reader.h
  rocAL/rocAL/source/master_graph.cpp
  rocAL/rocAL/source/meta_data_reader_factory.cpp
  rocAL/rocAL/source/mxnet_meta_data_reader.cpp
  rocAL/rocAL/source/mxnet_recordio_reader.cpp
  rocAL/rocAL/source/rali_api_data_loaders.cpp
  rocAL/rocAL/source/rali_api_meta_data.cpp
  rocAL/rocAL/source/reader_factory.cpp
  rocAL/tools/README.md
  utilities/rali/rali_unittests/rali_unittests.cpp
Labels: enhancement

#767 Tests - Readme Updates
  tests/README.md
Labels: enhancement

#768 Version Updates - 2.1.0 updates
  .travis.yml
  CHANGELOG.md
  CMakeLists.txt
  MIVisionX-setup.py
  README.md
  amd_openvx_extensions/amd_winml/README.md
  apps/dg_test/README.md
  apps/image_augmentation/README.md
  apps/mivisionx_inference_analyzer/mivisionx_inference_analyzer.py
  apps/mivisionx_validation_tool/mivisionx_validation_tool.py
  apps/mivisionx_winml_classifier/README.md
  apps/mivisionx_winml_yolov2/README.md
  docker/centos7/level-3.dockerfile
  docker/centos7/level-4.dockerfile
  docker/centos8/level-3.dockerfile
  docker/centos8/level-4.dockerfile
  docker/conformance/system_info.py
  docker/mivisionx-on-centos7.dockerfile
  docker/mivisionx-on-centos8.dockerfile
  docker/mivisionx-on-ubuntu18.dockerfile
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/pytorch/mivisionx-with-pytorch.dockerfile
  docker/ubuntu18/level-3.dockerfile
  docker/ubuntu18/level-4.dockerfile
  docker/ubuntu18/level-5.dockerfile
  docker/ubuntu20/level-3.dockerfile
  docker/ubuntu20/level-4.dockerfile
  docker/ubuntu20/level-5.dockerfile
  rocAL/rocAL/CMakeLists.txt
  rocAL/rocAL/include/open_cv_decoder.h
  samples/inference/mv_objdetect/README.md
  tests/conformance_tests/runConformanceTests.py
  tests/library_tests/runLibraryTests.py
  tests/neural_network_tests/runNeuralNetworkTests.py
  tests/vision_tests/runVisionTests.py
  toolkit/amd_data_analysis_toolkit/classification/generate-visualization.py
  toolkit/amd_data_analysis_toolkit/object_detection/generate-visualization.py
  utilities/mv_deploy/README.md
  utilities/rali/rali_dataloader/README.md
  utilities/rali/rali_dataloader_mt/README.md
  utilities/rali/rali_dataloader_tf/README.md
  utilities/rali/rali_performance_tests/README.md
  utilities/rali/rali_performance_tests_with_depth/README.md
  utilities/rali/rali_unittests/README.md
Labels: enhancement

#766 rocAL - renamed rali_unittest to rocal_unittest
  utilities/rali/rocal_unittests/CMakeLists.txt
  utilities/rali/rocal_unittests/README.md
  utilities/rali/rocal_unittests/rocal_unittests.cpp
Labels: enhancement

#773 Codacy - issue fix
  README.md
Labels: enhancement

#772 Docker - update to install HIP by default
  docker/mivisionx-on-centos7.dockerfile
  docker/mivisionx-on-centos8.dockerfile
  docker/mivisionx-on-ubuntu18.dockerfile
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/pytorch/mivisionx-with-pytorch.dockerfile
Labels: enhancement

#776 amd_media - readme fix
  amd_openvx_extensions/amd_media/README.md
Labels: bugfix

#765 HIP buffer transfer - Eliminate cupy usage
  README.md
  amd_openvx/openvx/ago/ago_util_hip.cpp
  amd_openvx/openvx/api/vx_api.cpp
  rocAL/rocAL/CMakeLists.txt
  rocAL/rocAL/include/master_graph.h
  rocAL/rocAL/include/rali_api_data_transfer.h
  rocAL/rocAL/rocAL_hip/rali_hip_kernels.cpp
  rocAL/rocAL/rocAL_hip/rali_hip_kernels.h
  rocAL/rocAL/source/master_graph.cpp
  rocAL/rocAL/source/rali_api_data_transfer.cpp
  rocAL/rocAL_pybind/CMakeLists.txt
  rocAL/rocAL_pybind/amd/rali/pipeline.py
  rocAL/rocAL_pybind/example/coco_pipeline.py
  rocAL/rocAL_pybind/example/rali-python-unittest.py
  rocAL/rocAL_pybind/rali_pybind.cpp
  rocAL/rocAL_pybind/run.sh
  rocAL/rocAL_pybind/setup.py
Labels: enhancement

#777 Tests - Video encoder test
  tests/amd_media_tests/README.md
  tests/amd_media_tests/encoder.gdf
  tests/amd_media_tests/test.yuv
Labels: enhancement
