Repository ROCm/MIVisionX, pull requests merged in 2022-09, with the labels that each got.

#936 update the readme for the migraphx extension
  amd_openvx_extensions/amd_migraphx/README.md
Labels: enhancement

#923 vx_amd_migraphx tests
  amd_openvx_extensions/amd_migraphx/src/migraphx_node.cpp
  tests/amd_migraphx_test/mnist/CMakeLists.txt
  tests/amd_migraphx_test/mnist/migraphx_node_test.cpp
  tests/amd_migraphx_test/resnet50/CMakeLists.txt
  tests/amd_migraphx_test/resnet50/migraphx_node_test.cpp
  tests/amd_migraphx_test/runMIGraphXTests/CMakeLists.txt
  tests/amd_migraphx_test/runMIGraphXTests/README.md
  tests/amd_migraphx_test/runMIGraphXTests/runMIGraphXTests.cpp
Labels: enhancement

#930 OpenVX HIP backend - report correct number of CUs for gfx10+ in the logs
  amd_openvx/openvx/ago/ago_util_hip.cpp
Labels: enhancement

#938 add argument for specifying pytorch version for building docker file
  docker/README.md
  docker/pytorch/README.md
  docker/pytorch/mivisionx-with-pytorch.dockerfile
Labels: enhancement

#940 Fixes bug with respect to user_given_size_restricted decode policy
  rocAL/rocAL/source/api/rocal_api_data_loaders.cpp
Labels: enhancement, bugfix

#942 Codacy fixes for PR937
  docker/tensorflow/README.md
  docker/tensorflow/mivisionx-with-tensorflow.dockerfile
  rocAL/rocAL_pybind/example/new_api/tf_petsTrainingExample/README.md
Labels: enhancement, bugfix

#926 Adding NCHW FP16 SIMD kernel
  rocAL/rocAL/CMakeLists.txt
  rocAL/rocAL/source/pipeline/master_graph.cpp
Labels: enhancement

#939 README for rocAL video unit test
  utilities/rocAL/rocAL_video_unittests/README.md
  utilities/rocAL/rocAL_video_unittests/rocAL_video_unittests.cpp
  utilities/rocAL/rocAL_video_unittests/samples/sequence_reader.png
  utilities/rocAL/rocAL_video_unittests/samples/sequence_rearrange.png
  utilities/rocAL/rocAL_video_unittests/samples/video_reader.png
  utilities/rocAL/rocAL_video_unittests/testScript.sh
Labels: enhancement

#943 MIVisionX - cmake cleanup
  amd_openvx/CMakeLists.txt
  amd_openvx/openvx/CMakeLists.txt
  amd_openvx_extensions/CMakeLists.txt
  amd_openvx_extensions/amd_custom/CMakeLists.txt
  amd_openvx_extensions/amd_custom/custom_lib/CMakeLists.txt
  amd_openvx_extensions/amd_media/CMakeLists.txt
  amd_openvx_extensions/amd_migraphx/CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  amd_openvx_extensions/amd_nn/nn_hip/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  apps/cloud_inference/server_app/CMakeLists.txt
  rocAL/rocAL/CMakeLists.txt
  rocAL/rocAL_pybind/CMakeLists.txt
  utilities/CMakeLists.txt
  utilities/rocAL/rocAL_dataloader_mt/CMakeLists.txt
  utilities/runvx/CMakeLists.txt
  utilities/runvx/vxUtils.h
Labels: enhancement, bugfix

#941 ZenDNN model compiler
  model_compiler/python/nnir_to_zendnn.py
Labels: enhancement

#946 MIVisionx - cmake clean up - part2
  amd_openvx/openvx/hipvx/CMakeLists.txt
  amd_openvx_extensions/amd_nn/nn_hip/CMakeLists.txt
  apps/cloud_inference/server_app/CMakeLists.txt
  rocAL/rocAL/rocAL_hip/CMakeLists.txt
Labels: enhancement

#945 model compiler script updates
  model_compiler/python/caffe_to_nnir.py
  model_compiler/python/nnef_to_nnir.py
  model_compiler/python/nnir_to_clib.py
  model_compiler/python/nnir_to_nnef.py
  model_compiler/python/nnir_to_openvx.py
  model_compiler/python/nnir_update.py
  model_compiler/python/onnx_to_nnir.py
Labels: enhancement, bugfix

#948 SPACK updates - Turbo JPEG
  amd_openvx/cmake/FindTurboJpeg.cmake
Labels: bugfix

#951 V2.3 - Updates
  CHANGELOG.md
  MIVisionX-setup.py
  README.md
Labels: enhancement

#954 rocal: cleanup
  rocAL/rocAL_pybind/amd/rocal/pipeline.py
Labels: bugfix

#947 rocAL - Tf pets training
  rocAL/rocAL_pybind/amd/rocal/plugin/tf.py
  rocAL/rocAL_pybind/example/new_api/tf_petsTrainingExample/train_withROCAL_withTFRecordReader.py
Labels: enhancement

#955 rocAL - fix bug in the usage of GetImageName
  data/images/AMD-tinyDataSet-val.txt
  utilities/rocAL/rocAL_basic_test/CMakeLists.txt
  utilities/rocAL/rocAL_basic_test/rocal_basic_test.cpp
  utilities/rocAL/rocAL_dataloader_mt/rocAL_dataloader_mt.cpp
  utilities/rocAL/rocAL_dataloader_tf/rocAL_dataloader_tf.cpp
Labels: bugfix

#956 AMD - Float16 Support
  CMakeLists.txt
  amd_openvx/openvx/include/vx_ext_amd.h
Labels: enhancement
