Repository ROCm/MIVisionX, pull requests merged in 2022-04, with the labels that each got.

#801 VX_NN - Updates
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  model_compiler/python/nnir_to_clib.py
  model_compiler/python/nnir_to_openvx.py
Labels: enhancement

#804 VX_NN - Updates (#801)
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  model_compiler/python/nnir_to_clib.py
  model_compiler/python/nnir_to_openvx.py
Labels: bugfix

#807 Backend Support - CPU for Setup & Testing
  MIVisionX-setup.py
  tests/amd_media_tests/README.md
  tests/amd_media_tests/gdf/data/test.mp4
  tests/amd_media_tests/gdf/data/test.yuv
  tests/amd_media_tests/gdf/decoder.gdf
  tests/amd_media_tests/gdf/encoder.gdf
  tests/library_tests/runLibraryTests.py
  tests/vision_tests/README.md
  tests/vision_tests/runVisionTests.py
Labels: enhancement, bugfix

#809 Release - Updates for 5.1.1
  CHANGELOG.md
  MIVisionX-setup.py
  README.md
  docker/centos7/level-4.dockerfile
  docker/centos8/level-4.dockerfile
  docker/mivisionx-on-centos7.dockerfile
  docker/mivisionx-on-centos8.dockerfile
  docker/mivisionx-on-ubuntu18.dockerfile
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/mivisionx-opencl-on-ubuntu18.dockerfile
  docker/mivisionx-opencl-on-ubuntu20.dockerfile
  docker/ubuntu18/level-4.dockerfile
  docker/ubuntu18/level-5.dockerfile
  docker/ubuntu20/level-4.dockerfile
  docker/ubuntu20/level-5.dockerfile
Labels: enhancement

#803 OpenVX extensions - add support for MIGraphX node
  CMakeLists.txt
  amd_openvx_extensions/CMakeLists.txt
  amd_openvx_extensions/amd_migraphx/CMakeLists.txt
  amd_openvx_extensions/amd_migraphx/include/vx_amd_migraphx.h
  amd_openvx_extensions/amd_migraphx/src/kernels.cpp
  amd_openvx_extensions/amd_migraphx/src/kernels.h
  amd_openvx_extensions/amd_migraphx/src/migraphx_node.cpp
  tests/amd_migraphx_test/mnist/CMakeLists.txt
  tests/amd_migraphx_test/mnist/digits.txt
  tests/amd_migraphx_test/mnist/migraphx_node_test.cpp
  tests/amd_migraphx_test/mnist/mnist-8.onnx
Labels: New Feature

#812 OpenVX/rocAL - remove the call to hipDeviceReset
  amd_openvx/openvx/ago/ago_util_hip.cpp
  rocAL/rocAL/source/device_manager_hip.cpp
Labels: bugfix

#814 MIGraphX extension - modify the cmake warning messages
  amd_openvx_extensions/CMakeLists.txt
Labels: enhancement

#815 migraphx extension - modify the node to use the program object directly
  amd_openvx/openvx/api/vx_api.cpp
  amd_openvx/openvx/include/vx_ext_amd.h
  amd_openvx_extensions/amd_migraphx/src/migraphx_node.cpp
Labels: enhancement

#818 migraphx extension - modify the node to register the program internally
  amd_openvx_extensions/amd_migraphx/include/vx_amd_migraphx.h
  amd_openvx_extensions/amd_migraphx/src/migraphx_node.cpp
  tests/amd_migraphx_test/mnist/migraphx_node_test.cpp
  tests/amd_migraphx_test/resnet50/migraphx_node_test.cpp
Labels: enhancement

#786 ROCm 5.2.0 Updates - File/Folder Reorg Changes
  .jenkins/common.groovy
  CMakeLists.txt
  amd_openvx/CMakeLists.txt
  amd_openvx/openvx/CMakeLists.txt
  amd_openvx_extensions/CMakeLists.txt
  amd_openvx_extensions/amd_loomsl/CMakeLists.txt
  amd_openvx_extensions/amd_media/CMakeLists.txt
  amd_openvx_extensions/amd_migraphx/CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  amd_openvx_extensions/amd_opencv/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  apps/mivisionx_openvx_classifier/CMakeLists.txt
  rocAL/rocAL/CMakeLists.txt
  samples/c_samples/canny/CMakeLists.txt
  samples/c_samples/opencv_orb/CMakeLists.txt
  samples/inference/mv_objdetect/CMakeLists.txt
  samples/model_compiler_samples/CMakeLists.txt
  tests/amd_migraphx_test/mnist/CMakeLists.txt
  tests/amd_migraphx_test/resnet50/CMakeLists.txt
  utilities/CMakeLists.txt
  utilities/runvx/CMakeLists.txt
Labels: enhancement

#817 rocAL - Fix issues with cascaded augmentations
  rocAL/rocAL/rocAL_hip/rali_hip_kernels.cpp
  rocAL/rocAL_pybind/amd/rocal/plugin/pytorch.py
  rocAL/rocAL_pybind/example/new_api/PYTHON_UNITTEST_TEST_FILE.sh
  rocAL/rocAL_pybind/example/new_api/READERS_TEST_FILE.sh
  rocAL/rocAL_pybind/example/new_api/parse_config.py
  rocAL/rocAL_pybind/example/new_api/rocAL_api_caffe2_reader.py
  rocAL/rocAL_pybind/example/new_api/rocAL_api_caffe_reader.py
  rocAL/rocAL_pybind/example/new_api/rocAL_api_python_unittest.py
  rocAL/rocAL_pybind/example/new_api/rocAL_api_tf_classification_reader.py
  rocAL/rocAL_pybind/example/new_api/rocAL_api_tf_detection_pipeline.py
  rocAL/rocAL_pybind/example/new_api/rocAL_api_video_pipeline.py
Labels: bugfix

#820 fix build error for rocal opencl backend
  rocAL/rocAL/include/master_graph.h
  rocAL/rocAL/source/rali_api_meta_data.cpp
Labels: bugfix

#821 setup script - add support for installing MIGraphX
  MIVisionX-setup.py
Labels: New Feature

#823 rocAL - Build Warnings Fix
  rocAL/rocAL/include/master_graph.h
  rocAL/rocAL/source/master_graph.cpp
Labels: bugfix
