Repository ROCm/MIVisionX, pull requests merged in 2022-12, with the labels that each got.

#1000 CMakeList - OpenMP & Boost Find
  amd_openvx_extensions/amd_custom/CMakeLists.txt
  amd_openvx_extensions/amd_custom/custom_lib/CMakeLists.txt
  rocAL/rocAL/CMakeLists.txt
Labels: enhancement, bugfix

#1002 Docker - PyTorch Fix
  docker/pytorch/mivisionx-with-pytorch-with-mesa.dockerfile
Labels: enhancement

#1003 rocAL - CPU Backend
  amd_openvx_extensions/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/include/internal_rpp.h
  amd_openvx_extensions/amd_rpp/source/BlurbatchPD.cpp
  amd_openvx_extensions/amd_rpp/source/CannyEdgeDetector.cpp
  amd_openvx_extensions/amd_rpp/source/kernel_rpp.cpp
  rocAL/rocAL/CMakeLists.txt
  rocAL/rocAL/include/device/device_manager.h
  rocAL/rocAL/include/device/device_manager_hip.h
  rocAL/rocAL/include/device/ocl_setup.h
  rocAL/rocAL/include/loaders/circular_buffer.h
  rocAL/rocAL/include/loaders/image/cifar10_data_loader.h
  rocAL/rocAL/include/loaders/image/image_loader.h
  rocAL/rocAL/include/loaders/image/image_loader_sharded.h
  rocAL/rocAL/include/loaders/image/node_cifar10_loader.h
  rocAL/rocAL/include/loaders/image/node_fused_jpeg_crop.h
  rocAL/rocAL/include/loaders/image/node_fused_jpeg_crop_single_shard.h
  rocAL/rocAL/include/loaders/image/node_image_loader.h
  rocAL/rocAL/include/loaders/image/node_image_loader_single_shard.h
  rocAL/rocAL/include/loaders/video/node_video_loader.h
  rocAL/rocAL/include/loaders/video/node_video_loader_single_shard.h
  rocAL/rocAL/include/loaders/video/video_loader.h
  rocAL/rocAL/include/loaders/video/video_loader_sharded.h
  rocAL/rocAL/include/pipeline/image.h
  rocAL/rocAL/include/pipeline/master_graph.h
  rocAL/rocAL/include/pipeline/ring_buffer.h
  rocAL/rocAL/source/api/rocal_api_data_transfer.cpp
  rocAL/rocAL/source/api/rocal_api_meta_data.cpp
  rocAL/rocAL/source/augmentations/geometry_augmentations/node_resize.cpp
  rocAL/rocAL/source/device/device_manager.cpp
  rocAL/rocAL/source/device/device_manager_hip.cpp
  rocAL/rocAL/source/device/ocl_setup.cpp
  rocAL/rocAL/source/loaders/circular_buffer.cpp
  rocAL/rocAL/source/loaders/image/cifar10_data_loader.cpp
  rocAL/rocAL/source/loaders/image/image_loader.cpp
  rocAL/rocAL/source/loaders/image/image_loader_sharded.cpp
  rocAL/rocAL/source/loaders/image/node_cifar10_loader.cpp
  rocAL/rocAL/source/loaders/image/node_fused_jpeg_crop.cpp
  rocAL/rocAL/source/loaders/image/node_fused_jpeg_crop_single_shard.cpp
  rocAL/rocAL/source/loaders/image/node_image_loader.cpp
  rocAL/rocAL/source/loaders/image/node_image_loader_single_shard.cpp
  rocAL/rocAL/source/loaders/video/node_video_loader.cpp
  rocAL/rocAL/source/loaders/video/node_video_loader_single_shard.cpp
  rocAL/rocAL/source/loaders/video/video_loader.cpp
  rocAL/rocAL/source/loaders/video/video_loader_sharded.cpp
  rocAL/rocAL/source/meta_data/bounding_box_graph.cpp
  rocAL/rocAL/source/pipeline/image.cpp
  rocAL/rocAL/source/pipeline/master_graph.cpp
  rocAL/rocAL/source/pipeline/ring_buffer.cpp
Labels: enhancement, bugfix, New Feature

#1005 rocAL : Fix build errors wrt Boost version:1.80 and build warnings in Ubuntu version:22
  rocAL/rocAL/include/readers/image/reader.h
  rocAL/rocAL/source/meta_data/bounding_box_graph.cpp
  rocAL/rocAL/source/meta_data/caffe2_meta_data_reader.cpp
  rocAL/rocAL/source/meta_data/caffe2_meta_data_reader_detection.cpp
  rocAL/rocAL/source/meta_data/caffe_meta_data_reader.cpp
  rocAL/rocAL/source/meta_data/caffe_meta_data_reader_detection.cpp
  rocAL/rocAL/source/readers/image/caffe2_lmdb_record_reader.cpp
  rocAL/rocAL/source/readers/image/caffe_lmdb_record_reader.cpp
Labels: bugfix

#1008 Develop - merge to master
  amd_openvx_extensions/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/include/internal_rpp.h
  amd_openvx_extensions/amd_rpp/source/BlurbatchPD.cpp
  amd_openvx_extensions/amd_rpp/source/CannyEdgeDetector.cpp
  amd_openvx_extensions/amd_rpp/source/kernel_rpp.cpp
  docker/pytorch/mivisionx-with-pytorch-with-mesa.dockerfile
  rocAL/rocAL/CMakeLists.txt
  rocAL/rocAL/include/device/device_manager.h
  rocAL/rocAL/include/device/device_manager_hip.h
  rocAL/rocAL/include/device/ocl_setup.h
  rocAL/rocAL/include/loaders/circular_buffer.h
  rocAL/rocAL/include/loaders/image/cifar10_data_loader.h
  rocAL/rocAL/include/loaders/image/image_loader.h
  rocAL/rocAL/include/loaders/image/image_loader_sharded.h
  rocAL/rocAL/include/loaders/image/node_cifar10_loader.h
  rocAL/rocAL/include/loaders/image/node_fused_jpeg_crop.h
  rocAL/rocAL/include/loaders/image/node_fused_jpeg_crop_single_shard.h
  rocAL/rocAL/include/loaders/image/node_image_loader.h
  rocAL/rocAL/include/loaders/image/node_image_loader_single_shard.h
  rocAL/rocAL/include/loaders/video/node_video_loader.h
  rocAL/rocAL/include/loaders/video/node_video_loader_single_shard.h
  rocAL/rocAL/include/loaders/video/video_loader.h
  rocAL/rocAL/include/loaders/video/video_loader_sharded.h
  rocAL/rocAL/include/pipeline/image.h
  rocAL/rocAL/include/pipeline/master_graph.h
  rocAL/rocAL/include/pipeline/ring_buffer.h
  rocAL/rocAL/source/api/rocal_api_data_transfer.cpp
  rocAL/rocAL/source/api/rocal_api_meta_data.cpp
  rocAL/rocAL/source/augmentations/geometry_augmentations/node_resize.cpp
  rocAL/rocAL/source/device/device_manager.cpp
  rocAL/rocAL/source/device/device_manager_hip.cpp
  rocAL/rocAL/source/device/ocl_setup.cpp
  rocAL/rocAL/source/loaders/circular_buffer.cpp
  rocAL/rocAL/source/loaders/image/cifar10_data_loader.cpp
  rocAL/rocAL/source/loaders/image/image_loader.cpp
  rocAL/rocAL/source/loaders/image/image_loader_sharded.cpp
  rocAL/rocAL/source/loaders/image/node_cifar10_loader.cpp
  rocAL/rocAL/source/loaders/image/node_fused_jpeg_crop.cpp
  rocAL/rocAL/source/loaders/image/node_fused_jpeg_crop_single_shard.cpp
  rocAL/rocAL/source/loaders/image/node_image_loader.cpp
  rocAL/rocAL/source/loaders/image/node_image_loader_single_shard.cpp
  rocAL/rocAL/source/loaders/video/node_video_loader.cpp
  rocAL/rocAL/source/loaders/video/node_video_loader_single_shard.cpp
  rocAL/rocAL/source/loaders/video/video_loader.cpp
  rocAL/rocAL/source/loaders/video/video_loader_sharded.cpp
  rocAL/rocAL/source/meta_data/bounding_box_graph.cpp
  rocAL/rocAL/source/pipeline/image.cpp
  rocAL/rocAL/source/pipeline/master_graph.cpp
  rocAL/rocAL/source/pipeline/ring_buffer.cpp
Labels: enhancement, bugfix

#1007 OpenVX - Bug fix for vxSetKernelAttribute - CPU backend
  amd_openvx/openvx/api/vx_api.cpp
Labels: bugfix

#1009 vx_amd_migraphx tests update
  tests/amd_migraphx_tests/mnist/migraphx_node_test.cpp
  tests/amd_migraphx_tests/resnet50/migraphx_node_test.cpp
Labels: enhancement

#1010 CMakeList - BUILD_DEV Option Added
  CMakeLists.txt
  amd_openvx/openvx/CMakeLists.txt
  amd_openvx_extensions/amd_custom/CMakeLists.txt
  amd_openvx_extensions/amd_loomsl/CMakeLists.txt
  amd_openvx_extensions/amd_media/CMakeLists.txt
  amd_openvx_extensions/amd_migraphx/CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  amd_openvx_extensions/amd_opencv/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  rocAL/rocAL/CMakeLists.txt
  rocAL/rocAL_pybind/third_party_lib/pybind11/CMakeLists.txt
  utilities/CMakeLists.txt
  utilities/mv_deploy/CMakeLists.txt
Labels: enhancement

#1001 rocAL: Classification Training Related changes
  rocAL/rocAL/include/api/rocal_api_data_loaders.h
  rocAL/rocAL/include/decoders/image/decoder.h
  rocAL/rocAL/include/decoders/image/fused_crop_decoder.h
  rocAL/rocAL/include/decoders/image/open_cv_decoder.h
  rocAL/rocAL/include/decoders/image/turbo_jpeg_decoder.h
  rocAL/rocAL/include/decoders/video/hw_jpeg_decoder.h
  rocAL/rocAL/include/loaders/image/image_read_and_decode.h
  rocAL/rocAL/include/loaders/image/node_fused_jpeg_crop.h
  rocAL/rocAL/include/loaders/image/node_fused_jpeg_crop_single_shard.h
  rocAL/rocAL/include/parameters/parameter_crop.h
  rocAL/rocAL/include/parameters/parameter_factory.h
  rocAL/rocAL/include/parameters/parameter_random_crop_decoder.h
  rocAL/rocAL/include/pipeline/image.h
  rocAL/rocAL/source/api/rocal_api_data_loaders.cpp
  rocAL/rocAL/source/augmentations/geometry_augmentations/node_crop.cpp
  rocAL/rocAL/source/augmentations/geometry_augmentations/node_crop_mirror_normalize.cpp
  rocAL/rocAL/source/augmentations/geometry_augmentations/node_resize.cpp
  rocAL/rocAL/source/decoders/image/fused_crop_decoder.cpp
  rocAL/rocAL/source/loaders/image/image_read_and_decode.cpp
  rocAL/rocAL/source/loaders/image/node_fused_jpeg_crop.cpp
  rocAL/rocAL/source/loaders/image/node_fused_jpeg_crop_single_shard.cpp
  rocAL/rocAL/source/parameters/parameter_factory.cpp
  rocAL/rocAL/source/parameters/parameter_random_crop_decoder.cpp
  rocAL/rocAL/source/parameters/parameter_rocal_crop.cpp
  rocAL/rocAL/source/pipeline/image.cpp
  rocAL/rocAL/source/pipeline/master_graph.cpp
  rocAL/rocAL_pybind/amd/rocal/decoders.py
  rocAL/rocAL_pybind/amd/rocal/fn.py
  rocAL/rocAL_pybind/amd/rocal/pipeline.py
  rocAL/rocAL_pybind/amd/rocal/readers.py
  rocAL/rocAL_pybind/rocal_pybind.cpp
  rocAL/rocAL_pybind/run.sh
  utilities/rocAL/rocAL_unittests/rocAL_unittests.cpp
Labels: enhancement, bugfix

#1012 ROCm 5.4.1 updates
  CHANGELOG.md
  MIVisionX-setup.py
  README.md
  amd_openvx_extensions/amd_custom/CMakeLists.txt
  amd_openvx_extensions/amd_custom/custom_lib/CMakeLists.txt
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/mivisionx-on-ubuntu22.dockerfile
  docker/pytorch/mivisionx-with-pytorch-with-mesa.dockerfile
  docker/pytorch/mivisionx-with-pytorch.dockerfile
  docker/ubuntu20/level-1.dockerfile
  docker/ubuntu20/level-2.dockerfile
  docker/ubuntu20/level-3.dockerfile
  docker/ubuntu20/level-4.dockerfile
  docker/ubuntu20/level-5.dockerfile
  docker/ubuntu22/level-1.dockerfile
  docker/ubuntu22/level-2.dockerfile
  docker/ubuntu22/level-3.dockerfile
  docker/ubuntu22/level-4.dockerfile
  docker/ubuntu22/level-5.dockerfile
  rocAL/rocAL/include/parameters/parameter_random_crop_decoder.h
  utilities/runvx/CMakeLists.txt
Labels: enhancement, bugfix
