Repository ROCm/MIVisionX, pull requests merged in 2022-03, with the labels that each got.

#780 AMD_MEDIA - PR#775 Update: this fixes the encoder issue encoding green frames.
  amd_openvx_extensions/amd_media/decoder.cpp
  amd_openvx_extensions/amd_media/encoder.cpp
  amd_openvx_extensions/amd_media/kernels.cpp
Labels: bugfix

#782 fix error message for EOS in amd_media encoder
  amd_openvx/openvx/ago/ago_interface.cpp
  amd_openvx/openvx/ago/ago_util_hip.cpp
  amd_openvx_extensions/amd_media/decoder.cpp
Labels: enhancement

#783 Tests: runVisionTests - make the collection of the perf counters optional when profiling is enabled
  tests/vision_tests/runVisionTests.py
Labels: enhancement

#785 CTS TESTS - Support OS
  tests/conformance_tests/runConformanceTests.py
Labels: enhancement, bugfix

#787 Develop - Merge to Master
  tests/conformance_tests/runConformanceTests.py
Labels: enhancement

#789 Tests -- AMD_MEDIA: decoder & encoder gdf
  tests/amd_media_tests/README.md
  tests/amd_media_tests/decoder.gdf
  tests/amd_media_tests/encoder.gdf
  tests/amd_media_tests/test.mp4
Labels: enhancement

#790 OpenVX OCL GPU backend - Fix syncing issue
  amd_openvx/openvx/ago/ago_util_opencl.cpp
Labels: bugfix

#793 RPP - Version upgrade
  CHANGELOG.md
  MIVisionX-setup.py
  README.md
Labels: enhancement

#794 Develop - MIVisionX 2.1.0 Release (#793)
  CHANGELOG.md
  MIVisionX-setup.py
  README.md
Labels: enhancement

#796 Model Compiler - OpenCV 4 Support
  model_compiler/python/nnir_to_openvx.py
Labels: bugfix

#798 Develop - Merge to TOT (#796)
  model_compiler/python/nnir_to_openvx.py
Labels: enhancement, bugfix

#799 Docker - HIP Backend Fix
  docker/conformance/openvx-1-3-on-ubuntu18.dockerfile
  docker/conformance/openvx-1-3-on-ubuntu20.dockerfile
  docker/mivisionx-on-ubuntu18.dockerfile
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/mivisionx-opencl-on-ubuntu18.dockerfile
  docker/mivisionx-opencl-on-ubuntu20.dockerfile
  docker/pytorch/mivisionx-with-pytorch.dockerfile
  docker/ubuntu18/level-5.dockerfile
  docker/ubuntu20/level-5.dockerfile
Labels: bugfix
