Repository ROCm/MIVisionX, pull requests merged in 2022-06, with the labels that each got.

#850 Docker - Updates & Fix
  CHANGELOG.md
  MIVisionX-setup.py
  README.md
  docker/centos7/level-4.dockerfile
  docker/centos8/level-4.dockerfile
  docker/mivisionx-on-centos7.dockerfile
  docker/mivisionx-on-centos8.dockerfile
  docker/mivisionx-on-ubuntu18.dockerfile
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/mivisionx-opencl-on-ubuntu18.dockerfile
  docker/mivisionx-opencl-on-ubuntu20.dockerfile
  docker/pytorch/mivisionx-with-pytorch.dockerfile
  docker/ubuntu18/level-2.dockerfile
  docker/ubuntu18/level-3.dockerfile
  docker/ubuntu18/level-4.dockerfile
  docker/ubuntu18/level-5.dockerfile
  docker/ubuntu20/level-2.dockerfile
  docker/ubuntu20/level-3.dockerfile
  docker/ubuntu20/level-4.dockerfile
  docker/ubuntu20/level-5.dockerfile
  model_compiler/README.md
  tests/neural_network_tests/runNeuralNetworkTests.py
Labels: enhancement, bugfix

#854 rocAL Unit Test - Fix & Updates
  utilities/rali/rali_basic_test/CMakeLists.txt
  utilities/rali/rali_basic_test/rali_basic_test.cpp
  utilities/rali/rali_dataloader/CMakeLists.txt
  utilities/rali/rali_dataloader/rali_dataloader.cpp
  utilities/rali/rali_dataloader_mt/CMakeLists.txt
  utilities/rali/rali_dataloader_mt/rali_dataloader_mt.cpp
  utilities/rali/rali_dataloader_tf/CMakeLists.txt
  utilities/rali/rali_dataloader_tf/rali_dataloader_tf.cpp
  utilities/rali/rali_performance_tests/CMakeLists.txt
  utilities/rali/rali_performance_tests/rali_performance_tests.cpp
  utilities/rali/rali_performance_tests_with_depth/CMakeLists.txt
  utilities/rali/rali_performance_tests_with_depth/rali_performance_tests_with_depth.cpp
  utilities/rali/rali_unittests/CMakeLists.txt
  utilities/rali/rali_unittests/rali_unittests.cpp
  utilities/rali/rali_video_unittests/CMakeLists.txt
  utilities/rali/rali_video_unittests/rali_video_unittests.cpp
  utilities/rali/rocal_unittests/CMakeLists.txt
  utilities/rali/rocal_unittests/rocal_unittests.cpp
Labels: enhancement, bugfix

#831 rocAL - Fix for tar files present in a folder
  rocAL/rocAL/source/label_reader_folders.cpp
Labels: bugfix

#855 rocAL - decoder device support and OpenCV version related changes
  amd_openvx_extensions/amd_media/decoder.cpp
  apps/image_augmentation/CMakeLists.txt
  apps/image_augmentation/image_augmentation.cpp
  rocAL/rocAL/include/rali_api_data_loaders.h
  rocAL/rocAL/source/hw_jpeg_decoder.cpp
  rocAL/rocAL/source/image_loader.cpp
  rocAL/rocAL/source/rali_api_data_loaders.cpp
  utilities/rali/rali_dataloader_mt/CMakeLists.txt
  utilities/rali/rali_dataloader_mt/rali_dataloader_mt.cpp
Labels: enhancement, bugfix

#856 Jenkins CI - use centralized Jenkins code
  .jenkins/common.groovy
  .jenkins/precheckin.groovy
Labels: enhancement

#859 AMD MIGraphX node-- test script
  tests/amd_migraphx_test/runMIGraphXTests/CMakeLists.txt
  tests/amd_migraphx_test/runMIGraphXTests/README.md
  tests/amd_migraphx_test/runMIGraphXTests/labels.txt
  tests/amd_migraphx_test/runMIGraphXTests/runMIGraphXTests.cpp
Labels: enhancement

#863 FFMPEG updates
  CHANGELOG.md
  MIVisionX-setup.py
  README.md
  docker/centos7/level-3.dockerfile
  docker/centos7/level-4.dockerfile
  docker/mivisionx-on-centos7.dockerfile
  docker/mivisionx-on-ubuntu18.dockerfile
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/mivisionx-opencl-on-ubuntu18.dockerfile
  docker/mivisionx-opencl-on-ubuntu20.dockerfile
  docker/ubuntu18/level-3.dockerfile
  docker/ubuntu18/level-4.dockerfile
  docker/ubuntu18/level-5.dockerfile
  docker/ubuntu20/level-3.dockerfile
  docker/ubuntu20/level-4.dockerfile
  docker/ubuntu20/level-5.dockerfile
Labels: enhancement

#864 DGTest OpenCV 4.x support
  apps/dg_test/CMakeLists.txt
  apps/dg_test/DGtest.cpp
  apps/dg_test/UserInterface.cpp
Labels: enhancement

#871 OpenVX cts- Floating point exception fix
  amd_openvx/openvx/ago/ago_kernel_api.cpp
Labels: bugfix

#865 amd_media decoder ffmpeg new version support
  amd_openvx_extensions/amd_media/decoder.cpp
Labels: enhancement, bugfix

#868 Inference Server App Fix
  apps/cloud_inference/server_app/inference.h
  apps/cloud_inference/server_app/inference_hip.cpp
Labels: enhancement, bugfix

#853 [CMAKE] GNUInstall Dir enhancements
  CMakeLists.txt
  amd_openvx/openvx/CMakeLists.txt
  amd_openvx_extensions/amd_loomsl/CMakeLists.txt
  amd_openvx_extensions/amd_media/CMakeLists.txt
  amd_openvx_extensions/amd_migraphx/CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  amd_openvx_extensions/amd_opencv/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  apps/CMakeLists.txt
  apps/cloud_inference/server_app/CMakeLists.txt
  apps/image_augmentation/CMakeLists.txt
  apps/optical_flow/CMakeLists.txt
  rocAL/rocAL/CMakeLists.txt
  rocAL/rocAL_pybind/CMakeLists.txt
  rocAL/rocAL_pybind/third_party_lib/pybind11/CMakeLists.txt
  utilities/CMakeLists.txt
  utilities/inference_generator/CMakeLists.txt
  utilities/loom_io_media/CMakeLists.txt
  utilities/loom_shell/CMakeLists.txt
  utilities/mv_deploy/CMakeLists.txt
  utilities/rali/rali_basic_test/CMakeLists.txt
  utilities/rali/rali_dataloader/CMakeLists.txt
  utilities/rali/rali_dataloader_mt/CMakeLists.txt
  utilities/rali/rali_dataloader_tf/CMakeLists.txt
  utilities/rali/rali_performance_tests/CMakeLists.txt
  utilities/rali/rali_performance_tests_with_depth/CMakeLists.txt
  utilities/rali/rali_unittests/CMakeLists.txt
  utilities/rali/rali_video_unittests/CMakeLists.txt
  utilities/rali/rocal_unittests/CMakeLists.txt
  utilities/runcl/CMakeLists.txt
  utilities/runvx/CMakeLists.txt
Labels: enhancement

#870 rocAL rali_data_loader_mt update
  rocAL/rocAL/include/rali_api_meta_data.h
  rocAL/rocAL/include/rali_api_types.h
  rocAL/rocAL/source/rali_api_meta_data.cpp
  utilities/rali/rali_dataloader_mt/CMakeLists.txt
  utilities/rali/rali_dataloader_mt/rali_dataloader_mt.cpp
Labels: enhancement

#873 MIVisionX 2.3.0 - Updates
  CMakeLists.txt
  tests/library_tests/runLibraryTests.py
Labels: enhancement

#869 RPP compatibility mods for hip/ocl
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
Labels: enhancement, bugfix

#875 CMakeList - use {ROCM_PATH}/include
  amd_openvx/openvx/CMakeLists.txt
  amd_openvx_extensions/amd_media/CMakeLists.txt
  amd_openvx_extensions/amd_migraphx/CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  rocAL/rocAL/CMakeLists.txt
  utilities/runvx/CMakeLists.txt
Labels: enhancement, bugfix

#876 Setup - Backend CPU Support
  MIVisionX-setup.py
  README.md
Labels: bugfix

#872 Develop - Merge to Master
  CMakeLists.txt
  MIVisionX-setup.py
  README.md
  amd_openvx/openvx/CMakeLists.txt
  amd_openvx/openvx/ago/ago_kernel_api.cpp
  amd_openvx_extensions/amd_loomsl/CMakeLists.txt
  amd_openvx_extensions/amd_media/CMakeLists.txt
  amd_openvx_extensions/amd_media/decoder.cpp
  amd_openvx_extensions/amd_migraphx/CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  amd_openvx_extensions/amd_opencv/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  apps/CMakeLists.txt
  apps/cloud_inference/server_app/CMakeLists.txt
  apps/cloud_inference/server_app/inference.h
  apps/cloud_inference/server_app/inference_hip.cpp
  apps/image_augmentation/CMakeLists.txt
  apps/optical_flow/CMakeLists.txt
  rocAL/rocAL/CMakeLists.txt
  rocAL/rocAL/include/rali_api_meta_data.h
  rocAL/rocAL/include/rali_api_types.h
  rocAL/rocAL/source/rali_api_meta_data.cpp
  rocAL/rocAL_pybind/CMakeLists.txt
  rocAL/rocAL_pybind/third_party_lib/pybind11/CMakeLists.txt
  tests/library_tests/runLibraryTests.py
  utilities/CMakeLists.txt
  utilities/inference_generator/CMakeLists.txt
  utilities/loom_io_media/CMakeLists.txt
  utilities/loom_shell/CMakeLists.txt
  utilities/mv_deploy/CMakeLists.txt
  utilities/rali/rali_basic_test/CMakeLists.txt
  utilities/rali/rali_dataloader/CMakeLists.txt
  utilities/rali/rali_dataloader_mt/CMakeLists.txt
  utilities/rali/rali_dataloader_mt/rali_dataloader_mt.cpp
  utilities/rali/rali_dataloader_tf/CMakeLists.txt
  utilities/rali/rali_performance_tests/CMakeLists.txt
  utilities/rali/rali_performance_tests_with_depth/CMakeLists.txt
  utilities/rali/rali_unittests/CMakeLists.txt
  utilities/rali/rali_video_unittests/CMakeLists.txt
  utilities/rali/rocal_unittests/CMakeLists.txt
  utilities/runcl/CMakeLists.txt
  utilities/runvx/CMakeLists.txt
Labels: enhancement, bugfix

#882 MIVisionX Apps - Standalone
  apps/CMakeLists.txt
  apps/README.md
  apps/bubble_pop/CMakeLists.txt
  apps/cloud_inference/server_app/CMakeLists.txt
  apps/cloud_inference/server_app/cmake/FindOpenCL.cmake
  apps/cloud_inference/server_app/include/arguments.h
  apps/cloud_inference/server_app/include/common.h
  apps/cloud_inference/server_app/include/compiler.h
  apps/cloud_inference/server_app/include/configure.h
  apps/cloud_inference/server_app/include/infcom.h
  apps/cloud_inference/server_app/include/inference.h
  apps/cloud_inference/server_app/include/netutil.h
  apps/cloud_inference/server_app/include/profiler.h
  apps/cloud_inference/server_app/include/region.h
  apps/cloud_inference/server_app/include/server.h
  apps/cloud_inference/server_app/include/shadow.h
  apps/cloud_inference/server_app/source/arguments.cpp
  apps/cloud_inference/server_app/source/common.cpp
  apps/cloud_inference/server_app/source/compiler.cpp
  apps/cloud_inference/server_app/source/configure.cpp
  apps/cloud_inference/server_app/source/inference.cpp
  apps/cloud_inference/server_app/source/inference_hip.cpp
  apps/cloud_inference/server_app/source/main.cpp
  apps/cloud_inference/server_app/source/netutil.cpp
  apps/cloud_inference/server_app/source/profiler.cpp
  apps/cloud_inference/server_app/source/region.cpp
  apps/cloud_inference/server_app/source/server.cpp
  apps/cloud_inference/server_app/source/shadow.cpp
  apps/dg_test/CMakeLists.txt
  apps/dg_test/cmake/FindOpenCL.cmake
  apps/dg_test/include/DGtest.h
  apps/dg_test/include/UserInterface.h
  apps/dg_test/include/annmodule.h
  apps/dg_test/include/cvui.h
  apps/dg_test/source/DGtest.cpp
  apps/dg_test/source/UserInterface.cpp
  apps/dg_test/source/annmodule.cpp
  apps/dg_test/source/main.cpp
  apps/image_augmentation/CMakeLists.txt
  apps/mivisionx_openvx_classifier/CMakeLists.txt
  apps/mivisionx_openvx_classifier/cmake/FindOpenCL.cmake
  apps/optical_flow/CMakeLists.txt
Labels: enhancement, bugfix

#885 CMakeLists cleanup for samples- read openvx backend config from the new location only
  samples/inference/mv_objdetect/CMakeLists.txt
  samples/model_compiler_samples/CMakeLists.txt
Labels: enhancement, bugfix
