Repository ROCm/MIVisionX, pull requests merged in 2022-05, with the labels that each got.

#827 Validation app update - new rocAL API
  apps/mivisionx_validation_tool/inference_control.py
  apps/mivisionx_validation_tool/inference_setup.py
  apps/mivisionx_validation_tool/inference_viewer.py
  apps/mivisionx_validation_tool/mivisionx_validation_tool.py
  apps/mivisionx_validation_tool/rali_setup.py
  rocAL/rocAL_pybind/rali_pybind.cpp
Labels: bugfix

#828 VX_NN - vxUpsampleNearestLayer node implementation on HIP backend
  amd_openvx_extensions/amd_nn/nn_hip/nn_hip_host_decls.h
  amd_openvx_extensions/amd_nn/nn_hip/nn_hip_kernels.cpp
  amd_openvx_extensions/amd_nn/src/upsample_nearest_layer.cpp
Labels: bugfix

#834 OpenVX migraphx extension - modified migraphx node to take a path (onnx file) directly
  amd_openvx_extensions/amd_migraphx/include/vx_amd_migraphx.h
  amd_openvx_extensions/amd_migraphx/src/kernels.cpp
  amd_openvx_extensions/amd_migraphx/src/kernels.h
  amd_openvx_extensions/amd_migraphx/src/migraphx_node.cpp
  tests/amd_migraphx_test/mnist/migraphx_node_test.cpp
  tests/amd_migraphx_test/resnet50/migraphx_node_test.cpp
Labels: enhancement

#836 Samples - Readme updates
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  samples/c_samples/README.md
  samples/gdf/README.md
  samples/loom_360_stitch/README.md
  samples/model_compiler_samples/README.md
Labels: enhancement

#840 OpenVX migraphx node - modified the node to accept reversed dimensions for input/output tensors
  amd_openvx_extensions/amd_migraphx/src/migraphx_node.cpp
  tests/amd_migraphx_test/mnist/migraphx_node_test.cpp
Labels: enhancement

#839 migraphx - gdf example mnist
  tests/amd_migraphx_test/gdf/README.md
  tests/amd_migraphx_test/gdf/image_0.jpg
  tests/amd_migraphx_test/gdf/image_1.jpg
  tests/amd_migraphx_test/gdf/image_4.jpg
  tests/amd_migraphx_test/gdf/mnist_migraphx.gdf
  tests/amd_migraphx_test/gdf/out_mnist.f32
  utilities/runvx/CMakeLists.txt
Labels: New Feature

#841 NN Deps - Docker & Setup Updates
  CHANGELOG.md
  MIVisionX-setup.py
  README.md
  docker/mivisionx-on-ubuntu18.dockerfile
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/mivisionx-opencl-on-ubuntu18.dockerfile
  docker/mivisionx-opencl-on-ubuntu20.dockerfile
  docker/ubuntu18/level-4.dockerfile
  docker/ubuntu18/level-5.dockerfile
  docker/ubuntu20/level-4.dockerfile
  docker/ubuntu20/level-5.dockerfile
  samples/model_compiler_samples/README.md
Labels: enhancement, bugfix

#844 Windows - Updates & Fixes
  CMakeLists.txt
  amd_openvx/cmake/FindOpenCL.cmake
  amd_openvx/openvx/CMakeLists.txt
  amd_openvx/openvx/ago/ago_haf_gpu_special_filters.cpp
  amd_openvx/openvx/ago/ago_kernel_api.cpp
  amd_openvx/openvx/ago/ago_util.cpp
  amd_openvx_extensions/CMakeLists.txt
  amd_openvx_extensions/amd_loomsl/CMakeLists.txt
  amd_openvx_extensions/amd_opencv/CMakeLists.txt
  utilities/loom_shell/CMakeLists.txt
  utilities/runcl/CMakeLists.txt
  utilities/runvx/CMakeLists.txt
Labels: enhancement, bugfix

#846 Readme - Fix
  README.md
  amd_openvx/README.md
  docker/README.md
  docs/images/blue_square.png
  docs/images/green_square.png
Labels: bugfix

#848 AMD OpenVX- Readme Updates
  README.md
  amd_openvx/README.md
  docs/images/openvx_software_layers.png
  utilities/runvx/README.md
Labels: enhancement
