Repository ROCm/MIVisionX, pull requests merged in 2023-02, with the labels that each got.

#1038 rocal_pybind - bug fix for one hot encoded labels
  rocAL/rocAL_pybind/amd/rocal/pipeline.py
  rocAL/rocAL_pybind/amd/rocal/plugin/generic.py
  rocAL/rocAL_pybind/amd/rocal/plugin/tf.py
Labels: bugfix

#1035 rocAL - Tf pets training
  docker/tensorflow/mivisionx-with-tensorflow.dockerfile
  rocAL/rocAL_pybind/amd/rocal/pipeline.py
  rocAL/rocAL_pybind/examples/tf_petsTrainingExample/README.md
  rocAL/rocAL_pybind/examples/tf_petsTrainingExample/download_and_preprocess_dataset.sh
  rocAL/rocAL_pybind/examples/tf_petsTrainingExample/requirements.sh
Labels: enhancement

#1041 CMakeLists - Avoid RPATH removal from binaries
  CMakeLists.txt
Labels: bugfix

#1040 AMD_NN - bug fix
  amd_openvx_extensions/amd_nn/src/convolution_layer.cpp
  amd_openvx_extensions/amd_nn/src/deconvolution_layer.cpp
Labels: bugfix

#1036 rocAL - changes for classification training convergence
  rocAL/rocAL/include/pipeline/image.h
  rocAL/rocAL/source/api/rocal_api_augmentation.cpp
  rocAL/rocAL/source/augmentations/geometry_augmentations/node_resize.cpp
  rocAL/rocAL/source/decoders/image/fused_crop_decoder.cpp
  rocAL/rocAL/source/decoders/image/turbo_jpeg_decoder.cpp
  rocAL/rocAL/source/loaders/image/image_loader.cpp
  rocAL/rocAL/source/loaders/image/image_read_and_decode.cpp
  rocAL/rocAL/source/parameters/parameter_rocal_crop.cpp
  rocAL/rocAL/source/pipeline/image.cpp
  rocAL/rocAL_pybind/amd/rocal/decoders.py
Labels: enhancement

#1045 rocAL - run.sh Fix
  rocAL/rocAL_pybind/amd/rocal/readers.py
  rocAL/rocAL_pybind/rocal_pybind.cpp
Labels: bugfix

#1046 ADAT - Fix for Deprecated Function
  toolkit/amd_data_analysis_toolkit/classification/generate-visualization.py
Labels: enhancement, bugfix
