Repository ROCm/MIVisionX, pull requests merged in 2023-08, with the labels that each got.

#1161 Stop generating PDF on Read the Docs configuration
  .readthedocs.yaml
Labels: dependencies, ci:docs-only

#1158 CTest - Updates & Additional Tests
  CMakeLists.txt
  amd_openvx_extensions/CMakeLists.txt
  tests/openvx/CMakeLists.txt
  tests/openvx_api_tests/CMakeLists.txt
  tests/openvx_api_tests/canny/CMakeLists.txt
  tests/openvx_api_tests/canny/canny.cpp
  tests/openvx_api_tests/channel_extract/CMakeLists.txt
  tests/openvx_api_tests/channel_extract/channel_extract.cpp
  tests/openvx_api_tests/color_convert/CMakeLists.txt
  tests/openvx_api_tests/color_convert/color_convert.cpp
Labels: enhancement

#1163 CMakeLists - Update Min Version to 3.5
  CMakeLists.txt
  amd_openvx/CMakeLists.txt
  amd_openvx/openvx/CMakeLists.txt
  amd_openvx_extensions/CMakeLists.txt
  amd_openvx_extensions/amd_loomsl/CMakeLists.txt
  amd_openvx_extensions/amd_media/CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  amd_openvx_extensions/amd_opencv/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  apps/CMakeLists.txt
  apps/bubble_pop/CMakeLists.txt
  apps/cloud_inference/server_app/CMakeLists.txt
  apps/dg_test/CMakeLists.txt
  apps/image_augmentation/CMakeLists.txt
  apps/mivisionx_openvx_classifier/CMakeLists.txt
  apps/optical_flow/CMakeLists.txt
  model_compiler/python/nnir_to_clib.py
  model_compiler/python/nnir_to_openvx.py
  rocAL/CMakeLists.txt
  rocAL/rocAL/CMakeLists.txt
  rocAL/rocAL_pybind/CMakeLists.txt
  samples/c_samples/canny/CMakeLists.txt
  samples/c_samples/opencv_orb/CMakeLists.txt
  samples/inference/mv_objdetect/CMakeLists.txt
  samples/model_compiler_samples/CMakeLists.txt
  tests/amd_migraphx_tests/mnist/CMakeLists.txt
  tests/amd_migraphx_tests/resnet50/CMakeLists.txt
  tests/amd_migraphx_tests/runMIGraphXTests/CMakeLists.txt
  tests/openvx_api_tests/CMakeLists.txt
  tests/openvx_api_tests/canny/CMakeLists.txt
  tests/openvx_api_tests/channel_extract/CMakeLists.txt
  tests/openvx_api_tests/color_convert/CMakeLists.txt
  utilities/CMakeLists.txt
  utilities/inference_generator/CMakeLists.txt
  utilities/inference_generator/src/caffe2openvx.cpp
  utilities/inference_generator/src/nnef2openvx.cpp
  utilities/loom_io_media/CMakeLists.txt
  utilities/loom_shell/CMakeLists.txt
  utilities/mv_deploy/CMakeLists.txt
  utilities/rocAL/rocAL_basic_test/CMakeLists.txt
  utilities/rocAL/rocAL_dataloader/CMakeLists.txt
  utilities/rocAL/rocAL_dataloader_mt/CMakeLists.txt
  utilities/rocAL/rocAL_dataloader_tf/CMakeLists.txt
  utilities/rocAL/rocAL_performance_tests/CMakeLists.txt
  utilities/rocAL/rocAL_performance_tests_with_depth/CMakeLists.txt
  utilities/rocAL/rocAL_unittests/CMakeLists.txt
  utilities/rocAL/rocAL_video_unittests/CMakeLists.txt
  utilities/runcl/CMakeLists.txt
  utilities/runvx/CMakeLists.txt
Labels: enhancement

#1165 CMakeLists - bug fix for old gpu arch
  CMakeLists.txt
  amd_openvx/CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  rocAL/rocAL/CMakeLists.txt
Labels: bugfix

#1159 Model Compiler : int64 support
  docs/.sphinx/requirements.txt
  model_compiler/python/nnir_to_clib.py
Labels: enhancement

#1169 SWDEV-416815 - Added suffix 'asan' to ASAN package name
  CMakeLists.txt
Labels: bugfix

#1167 SWDEV-416547 - Set the dependent packages for MIVisionX
  CMakeLists.txt
Labels: enhancement, bugfix

#1168 SWDEV-416815 - Added suffix 'asan' to ASAN package name
  CMakeLists.txt
Labels: bugfix

#1166 SWDEV-416547 - Set the dependent packages for MIVisionX
  CMakeLists.txt
Labels: enhancement, bugfix

#1172 CMakelists - gfx1100 Arch Added
  amd_openvx/CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  rocAL/rocAL/CMakeLists.txt
Labels: enhancement

#1174 rocAL - Compile failure fix
  rocAL/CMakeLists.txt
  rocAL/rocAL/CMakeLists.txt
  rocAL/rocAL/include/loaders/image/loader_module.h
  rocAL/rocAL/include/meta_data/caffe2_meta_data_reader.h
  rocAL/rocAL/include/meta_data/caffe2_meta_data_reader_detection.h
  rocAL/rocAL/include/meta_data/caffe_meta_data_reader.h
  rocAL/rocAL/include/meta_data/caffe_meta_data_reader_detection.h
  rocAL/rocAL/include/meta_data/mxnet_meta_data_reader.h
  rocAL/rocAL/include/meta_data/randombboxcrop_meta_data_reader.h
  rocAL/rocAL/include/readers/image/caffe2_lmdb_record_reader.h
  rocAL/rocAL/include/readers/image/caffe_lmdb_record_reader.h
  rocAL/rocAL/include/readers/image/cifar10_data_reader.h
  rocAL/rocAL/include/readers/image/coco_file_source_reader.h
  rocAL/rocAL/include/readers/image/file_source_reader.h
  rocAL/rocAL/include/readers/image/image_reader.h
  rocAL/rocAL/include/readers/image/mxnet_recordio_reader.h
  rocAL/rocAL/include/readers/image/reader_factory.h
  rocAL/rocAL/include/readers/image/tf_record_reader.h
  rocAL/rocAL/include/readers/video/sequence_file_source_reader.h
  rocAL/rocAL/source/meta_data/caffe2_meta_data_reader.cpp
  rocAL/rocAL/source/meta_data/caffe2_meta_data_reader_detection.cpp
  rocAL/rocAL/source/meta_data/caffe_meta_data_reader_detection.cpp
  rocAL/rocAL/source/readers/image/caffe2_lmdb_record_reader.cpp
  rocAL/rocAL_pybind/CMakeLists.txt
Labels: bugfix
