Repository ROCm/MIVisionX, pull requests merged in 2023-05, with the labels that each got.

#1070 Model Compiler - ONNX update
  model_compiler/python/nnir_to_openvx.py
  model_compiler/python/onnx_to_nnir.py
Labels: bugfix

#1076 fix bug in rocal video unit-test failure
  amd_openvx_extensions/amd_rpp/source/TensorAdd.cpp
  amd_openvx_extensions/amd_rpp/source/TensorMatrixMultiply.cpp
  amd_openvx_extensions/amd_rpp/source/TensorMultiply.cpp
  amd_openvx_extensions/amd_rpp/source/TensorSubtract.cpp
  amd_openvx_extensions/amd_rpp/source/copy.cpp
  rocAL/rocAL_pybind/examples/PYTHON_UNITTEST_TEST_FILE.sh
Labels: bugfix

#1078 update the GPU target list
  amd_openvx/CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  rocAL/rocAL/CMakeLists.txt
Labels: enhancement

#1077 rocAL/NN - Reverting renaming of graphHandle to RPPHandle
  amd_openvx_extensions/amd_nn/src/activation_layer.cpp
  amd_openvx_extensions/amd_nn/src/batch_normalization_layer.cpp
  amd_openvx_extensions/amd_nn/src/convolution_layer.cpp
  amd_openvx_extensions/amd_nn/src/deconvolution_layer.cpp
  amd_openvx_extensions/amd_nn/src/fully_connected_layer.cpp
  amd_openvx_extensions/amd_nn/src/kernels.cpp
  amd_openvx_extensions/amd_nn/src/kernels.h
  amd_openvx_extensions/amd_nn/src/local_response_normalization_layer.cpp
  amd_openvx_extensions/amd_nn/src/normalization_layer.cpp
  amd_openvx_extensions/amd_nn/src/pooling_layer.cpp
  amd_openvx_extensions/amd_nn/src/reshape_layer.cpp
  amd_openvx_extensions/amd_nn/src/scale_layer.cpp
  amd_openvx_extensions/amd_nn/src/softmax_layer.cpp
  amd_openvx_extensions/amd_nn/src/tensor_add.cpp
  amd_openvx_extensions/amd_nn/src/tensor_matrix_multiply.cpp
  amd_openvx_extensions/amd_nn/src/tensor_max.cpp
  amd_openvx_extensions/amd_nn/src/tensor_min.cpp
  amd_openvx_extensions/amd_nn/src/tensor_multiply.cpp
  amd_openvx_extensions/amd_nn/src/tensor_subtract.cpp
Labels: bugfix

#1079 HIP - remove unsupported targets
  amd_openvx/CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  rocAL/rocAL/CMakeLists.txt
Labels: bugfix

#1086 Update documentation requirements
  docs/.sphinx/requirements.in
  docs/.sphinx/requirements.txt
Labels: noCI

#1085 Decode & rocAL - Add new YUV formats supported by VCN and fix python test and jupyter notebook
  amd_openvx_extensions/amd_media/decoder.cpp
  rocAL/docs/examples/image_processing/decoder.py
  rocAL/docs/examples/image_processing/decoder_examples.ipynb
  rocAL/rocAL/source/decoders/image/hw_jpeg_decoder.cpp
Labels: enhancement

#1082 Model Compiler - ONNX flow fix & Fuse Ops fix
  model_compiler/python/nnir.py
  model_compiler/python/onnx_to_nnir.py
Labels: bugfix
