Repository ROCm/MIVisionX, pull requests merged in 2023-12, with the labels that each got.

#1234 changelog updates
  CHANGELOG.md
Labels: enhancement

#1236 Arch support - add support for gfx942
  amd_openvx/CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  rocAL/rocAL/CMakeLists.txt
Labels: enhancement

#1239 macOS - Package build fix
  CMakeLists.txt
  docs/data/MIVisionX.bmp
Labels: bugfix

#1238 Adding issue template
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/issue_report.yml
Labels: enhancement

#1242 Test Package - Updates
  CMakeLists.txt
  amd_openvx/CMakeLists.txt
  amd_openvx_extensions/CMakeLists.txt
  amd_openvx_extensions/amd_custom/custom_lib/CMakeLists.txt
  amd_openvx_extensions/amd_media/CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  cmake/FindAMDRPP.cmake
  cmake/FindFFmpeg.cmake
  cmake/FindHALF.cmake
  cmake/FindLMDB.cmake
  cmake/FindMIVisionX.cmake
  cmake/FindOpenCL.cmake
  cmake/FindTurboJpeg.cmake
  rocAL/rocAL/CMakeLists.txt
  rocAL/rocAL_pybind/CMakeLists.txt
  utilities/CMakeLists.txt
  utilities/mv_deploy/CMakeLists.txt
  utilities/rocAL/rocAL_basic_test/CMakeLists.txt
  utilities/rocAL/rocAL_dataloader/CMakeLists.txt
  utilities/rocAL/rocAL_dataloader_mt/CMakeLists.txt
  utilities/rocAL/rocAL_dataloader_tf/CMakeLists.txt
  utilities/rocAL/rocAL_performance_tests/CMakeLists.txt
  utilities/rocAL/rocAL_performance_tests_with_depth/CMakeLists.txt
  utilities/rocAL/rocAL_unittests/CMakeLists.txt
  utilities/rocAL/rocAL_video_unittests/CMakeLists.txt
  utilities/runvx/CMakeLists.txt
Labels: enhancement, bugfix

#1243 Test Package - Updates (#1242)
  CMakeLists.txt
  amd_openvx/CMakeLists.txt
  amd_openvx_extensions/CMakeLists.txt
  amd_openvx_extensions/amd_custom/custom_lib/CMakeLists.txt
  amd_openvx_extensions/amd_media/CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  cmake/FindAMDRPP.cmake
  cmake/FindFFmpeg.cmake
  cmake/FindHALF.cmake
  cmake/FindLMDB.cmake
  cmake/FindMIVisionX.cmake
  cmake/FindOpenCL.cmake
  cmake/FindTurboJpeg.cmake
  rocAL/rocAL/CMakeLists.txt
  rocAL/rocAL_pybind/CMakeLists.txt
  utilities/CMakeLists.txt
  utilities/mv_deploy/CMakeLists.txt
  utilities/rocAL/rocAL_basic_test/CMakeLists.txt
  utilities/rocAL/rocAL_dataloader/CMakeLists.txt
  utilities/rocAL/rocAL_dataloader_mt/CMakeLists.txt
  utilities/rocAL/rocAL_dataloader_tf/CMakeLists.txt
  utilities/rocAL/rocAL_performance_tests/CMakeLists.txt
  utilities/rocAL/rocAL_performance_tests_with_depth/CMakeLists.txt
  utilities/rocAL/rocAL_unittests/CMakeLists.txt
  utilities/rocAL/rocAL_video_unittests/CMakeLists.txt
  utilities/runvx/CMakeLists.txt
Labels: enhancement, bugfix

#1244 Fixing linkage error for std experimental filesystem
  rocAL/rocAL/CMakeLists.txt
Labels: bugfix

#1248 Std filesystem cmake fix
  rocAL/rocAL/CMakeLists.txt
Labels: bugfix

#1247 Test package - updates
  CMakeLists.txt
  tests/CMakeLists.txt
  tests/ctest_cmakelists/CMakeLists.txt
Labels: enhancement

#1251 Update issue_report.yml
  .github/ISSUE_TEMPLATE/issue_report.yml
Labels: enhancement

#1252 Documenation - Updates
  README.md
  amd_openvx/openvx/README.md
  docker/README.md
  docker/archive/README.md
  docker/archive/centos7/level-1.dockerfile
  docker/archive/centos7/level-2.dockerfile
  docker/archive/centos7/level-3.dockerfile
  docker/archive/centos7/level-4.dockerfile
  docker/archive/centos8/level-1.dockerfile
  docker/archive/centos8/level-2.dockerfile
  docker/archive/centos8/level-3.dockerfile
  docker/archive/centos8/level-4.dockerfile
  docker/archive/mivisionx-on-centos7.dockerfile
  docker/archive/mivisionx-on-centos8.dockerfile
  docker/archive/mivisionx-on-ubuntu18.dockerfile
  docker/archive/mivisionx-opencl-on-ubuntu18.dockerfile
  docker/archive/mivisionx-opencl-on-ubuntu20.dockerfile
  docker/archive/ubuntu18/level-1.dockerfile
  docker/archive/ubuntu18/level-2.dockerfile
  docker/archive/ubuntu18/level-3.dockerfile
  docker/archive/ubuntu18/level-4.dockerfile
  docker/archive/ubuntu18/level-5.dockerfile
  samples/loom_360_stitch/README.md
Labels: enhancement

#1259 CuPy - Setup.py support updates
  CHANGELOG.md
  CMakeLists.txt
  MIVisionX-setup.py
  README.md
  rocAL/rocAL_pybind/README.md
Labels: enhancement, bugfix
