Repository ROCm/MIVisionX, pull requests merged in 2023-11, with the labels that each got.

#1212 Prerequisites - Boost Removal
  CMakeLists.txt
  MIVisionX-setup.py
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  apps/bubble_pop/include/internal_opencvTunnel.h
  docker/archive/centos7/level-4.dockerfile
  docker/archive/mivisionx-on-centos7.dockerfile
  docker/archive/mivisionx-on-ubuntu18.dockerfile
  docker/archive/mivisionx-opencl-on-ubuntu18.dockerfile
  docker/archive/mivisionx-opencl-on-ubuntu20.dockerfile
  docker/archive/ubuntu18/level-5.dockerfile
  docker/linux/mivisionx-on-rhel-8.dockerfile
  docker/linux/mivisionx-on-rhel-9.dockerfile
  docker/linux/mivisionx-on-sles-15.dockerfile
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/mivisionx-on-ubuntu22.dockerfile
  docker/mivisionx-release-ubuntu20.dockerfile
  docker/mivisionx-release-ubuntu22.dockerfile
  docker/pytorch/mivisionx-with-pytorch-with-mesa.dockerfile
  docker/pytorch/mivisionx-with-pytorch.dockerfile
  docker/tensorflow/mivisionx-with-tensorflow.dockerfile
  docker/ubuntu20/level-5.dockerfile
  docker/ubuntu22/level-5.dockerfile
  docker/zenDNN/zenDNN-gpu-hip.dockerfile
  rocAL/README.md
  rocAL/rocAL/CMakeLists.txt
  rocAL/rocAL/include/loaders/video/video_read_and_decode.h
  rocAL/rocAL/include/readers/video/video_properties.h
  rocAL/rocAL/source/api/rocal_api_data_loaders.cpp
  rocAL/rocAL/source/loaders/video/video_read_and_decode.cpp
  rocAL/rocAL/source/meta_data/caffe_meta_data_reader.cpp
  rocAL/rocAL/source/meta_data/cifar10_meta_data_reader.cpp
  rocAL/rocAL/source/meta_data/label_reader_folders.cpp
  rocAL/rocAL/source/meta_data/mxnet_meta_data_reader.cpp
  rocAL/rocAL/source/meta_data/video_label_reader.cpp
  rocAL/rocAL/source/readers/image/caffe2_lmdb_record_reader.cpp
  rocAL/rocAL/source/readers/image/caffe_lmdb_record_reader.cpp
  rocAL/rocAL/source/readers/image/cifar10_data_reader.cpp
  rocAL/rocAL/source/readers/image/coco_file_source_reader.cpp
  rocAL/rocAL/source/readers/image/file_source_reader.cpp
  rocAL/rocAL/source/readers/image/mxnet_recordio_reader.cpp
  rocAL/rocAL/source/readers/image/tf_record_reader.cpp
  rocAL/rocAL/source/readers/video/sequence_file_source_reader.cpp
  rocAL/rocAL/source/readers/video/video_file_source_reader.cpp
  rocAL/rocAL/source/readers/video/video_properties.cpp
  utilities/mv_deploy/mv_compile.cpp
Labels: enhancement, bugfix

#1224 MIVisionX ASAN - Exclude library_tests from ASAN pkg
  tests/openvx_api_tests/CMakeLists.txt
Labels: enhancement, bugfix

#1226 MIVisionX ASAN - Exclude library_tests from ASAN pkg
  tests/openvx_api_tests/CMakeLists.txt
Labels: enhancement, bugfix

#1231 Setup - CuPy Updates
  MIVisionX-setup.py
  README.md
Labels: bugfix

#1232 Package - generation for runtime, dev, asan, & test
  CMakeLists.txt
  amd_openvx/openvx/CMakeLists.txt
  amd_openvx_extensions/amd_custom/CMakeLists.txt
  amd_openvx_extensions/amd_loomsl/CMakeLists.txt
  amd_openvx_extensions/amd_media/CMakeLists.txt
  amd_openvx_extensions/amd_migraphx/CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  amd_openvx_extensions/amd_opencv/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  apps/bubble_pop/CMakeLists.txt
  apps/dg_test/CMakeLists.txt
  apps/image_augmentation/CMakeLists.txt
  apps/mivisionx_openvx_classifier/CMakeLists.txt
  apps/optical_flow/CMakeLists.txt
  docs/data/MIVisionX.bmp
  model_compiler/python/nnir_to_clib.py
  rocAL/rocAL/CMakeLists.txt
  tests/openvx_api_tests/CMakeLists.txt
  utilities/loom_io_media/CMakeLists.txt
  utilities/loom_shell/CMakeLists.txt
  utilities/mv_deploy/CMakeLists.txt
  utilities/rocAL/rocAL_basic_test/CMakeLists.txt
  utilities/rocAL/rocAL_dataloader/CMakeLists.txt
  utilities/rocAL/rocAL_dataloader_mt/CMakeLists.txt
  utilities/rocAL/rocAL_dataloader_tf/CMakeLists.txt
  utilities/rocAL/rocAL_performance_tests/CMakeLists.txt
  utilities/rocAL/rocAL_performance_tests_with_depth/CMakeLists.txt
  utilities/rocAL/rocAL_unittests/CMakeLists.txt
  utilities/rocAL/rocAL_video_unittests/CMakeLists.txt
  utilities/runcl/CMakeLists.txt
  utilities/runvx/CMakeLists.txt
Labels: enhancement, New Feature
