Repository ROCm/MIVisionX, pull requests merged in 2023-01, with the labels that each got.

#1018 RPP - Upgrade to V0.99
  CHANGELOG.md
  MIVisionX-setup.py
  README.md
  docker/archive/mivisionx-opencl-on-ubuntu20.dockerfile
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/mivisionx-on-ubuntu22.dockerfile
  docker/pytorch/mivisionx-with-pytorch-with-mesa.dockerfile
  docker/pytorch/mivisionx-with-pytorch.dockerfile
  docker/tensorflow/mivisionx-with-tensorflow.dockerfile
  docker/ubuntu20/level-5.dockerfile
  docker/ubuntu22/level-5.dockerfile
Labels: enhancement, bugfix

#1017 Revert "Remove RPATH/RUNPATH - Adding SKIP RPATH flag (#995)"
  CMakeLists.txt
  amd_openvx_extensions/amd_custom/custom_lib/CMakeLists.txt
  apps/cloud_inference/server_app/CMakeLists.txt
  apps/dg_test/CMakeLists.txt
  apps/image_augmentation/CMakeLists.txt
  apps/mivisionx_openvx_classifier/CMakeLists.txt
  model_compiler/python/nnir_to_clib.py
Labels: enhancement

#1020 Setup - Support for RedHat and Updates
  MIVisionX-setup.py
  README.md
  amd_openvx/cmake/FindAMDRPP.cmake
Labels: bugfix

#1023 CMakeList - Updates
  amd_openvx/cmake/FindAMDRPP.cmake
  amd_openvx/cmake/FindMIVisionX.cmake
  amd_openvx/cmake/FindTurboJpeg.cmake
  rocAL/rocAL/CMakeLists.txt
Labels: enhancement, bugfix

#1025 Setup - Install Dev Options
  MIVisionX-setup.py
  README.md
Labels: enhancement, bugfix

#1027 Linux - Distro Docker Support
  CMakeLists.txt
  docker/linux/mivisionx-on-rhel-8.dockerfile
  docker/linux/mivisionx-on-rhel-9.dockerfile
  docker/linux/mivisionx-on-sles-15.dockerfile
  tests/library_tests/runLibraryTests.py
  tests/neural_network_tests/runNeuralNetworkTests.py
  tests/vision_tests/runVisionTests.py
Labels: enhancement

#1024 rocAL - cmn fix
  rocAL/docs/examples/image_processing/inference_pipeline.py
  rocAL/rocAL/include/parameters/parameter_crop.h
  rocAL/rocAL/source/api/rocal_api_augmentation.cpp
  rocAL/rocAL/source/augmentations/geometry_augmentations/node_crop.cpp
  rocAL/rocAL/source/augmentations/geometry_augmentations/node_crop_mirror_normalize.cpp
  rocAL/rocAL/source/parameters/parameter_rocal_crop.cpp
  rocAL/rocAL_pybind/amd/rocal/fn.py
Labels: enhancement, bugfix

#1029 rocAL unit test and Video fixes.
  rocAL/rocAL/include/api/rocal_api_data_loaders.h
  rocAL/rocAL/source/api/rocal_api_data_loaders.cpp
  utilities/rocAL/rocAL_unittests/rocAL_unittests.cpp
  utilities/rocAL/rocAL_video_unittests/rocAL_video_unittests.cpp
Labels: enhancement, bugfix
