Repository ROCm/MIVisionX, pull requests merged in 2023-09, with the labels that each got.

#1177 Model Compiler - Update & Bug Fixes
  MIVisionX-setup.py
  model_compiler/python/nnir_to_clib.py
  model_compiler/python/nnir_to_openvx.py
  tests/neural_network_tests/runNeuralNetworkTests.py
Labels: enhancement, bugfix

#1182 Updates - Docker & Documentation
  README.md
  amd_openvx/README.md
  amd_openvx_extensions/amd_rpp/README.md
  docker/README.md
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/mivisionx-on-ubuntu22.dockerfile
  docker/ubuntu20/level-1.dockerfile
  docker/ubuntu20/level-2.dockerfile
  docker/ubuntu20/level-3.dockerfile
  docker/ubuntu20/level-4.dockerfile
  docker/ubuntu20/level-5.dockerfile
  docker/ubuntu22/level-1.dockerfile
  docker/ubuntu22/level-2.dockerfile
  docker/ubuntu22/level-3.dockerfile
  docker/ubuntu22/level-4.dockerfile
  docker/ubuntu22/level-5.dockerfile
Labels: enhancement

#1185 CuPy - Version Updates
  CHANGELOG.md
  MIVisionX-setup.py
  README.md
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/mivisionx-on-ubuntu22.dockerfile
  docker/pytorch/mivisionx-with-pytorch-with-mesa.dockerfile
  docker/pytorch/mivisionx-with-pytorch.dockerfile
  docker/tensorflow/mivisionx-with-tensorflow.dockerfile
  docker/ubuntu20/level-5.dockerfile
  docker/ubuntu22/level-5.dockerfile
Labels: bugfix

#1189 Samples - Updated
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  apps/image_augmentation/README.md
  apps/mivisionx_inference_analyzer/README.md
  docs/.sphinx/_toc.yml.in
  samples/README.md
  samples/model_compiler_samples/README.md
  samples/mv_objdetect/CMakeLists.txt
  samples/mv_objdetect/README.md
  samples/mv_objdetect/data/Videos/Videos_4.txt
  samples/mv_objdetect/data/images/Video_4_screenshot.png
  samples/mv_objdetect/data/images/img_04.JPG
  samples/mv_objdetect/mvobjdetect.cpp
  samples/mv_objdetect/visualize.cpp
  samples/mv_objdetect/visualize.h
  utilities/mv_deploy/README.md
Labels: enhancement, bugfix

#1179 SWDEV-415095 - Remove hard coded paths in RUNPATH
  CMakeLists.txt
  docs/.sphinx/requirements.in
Labels: enhancement

#1193 CTest - Updates
  CHANGELOG.md
  README.md
  tests/library_tests/README.md
  tests/library_tests/runLibraryTests.py
  tests/openvx_api_tests/CMakeLists.txt
  utilities/inference_generator/CMakeLists.txt
  utilities/inference_generator/README.md
  utilities/inference_generator/proto/caffe.proto
  utilities/inference_generator/src/caffe2openvx.cpp
  utilities/inference_generator/src/nnef2openvx.cpp
Labels: enhancement

#1200 VX_NN Reshape Layer Bug Fix
  amd_openvx_extensions/amd_nn/src/reshape_layer.cpp
Labels: bugfix
