Repository ROCm/MIVisionX, pull requests merged in 2023-10, with the labels that each got.

#1203 Half - Support Updates
  amd_openvx/cmake/FindHALF.cmake
  amd_openvx_extensions/amd_nn/src/reshape_layer.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/Copy.cpp
Labels: enhancement, bugfix

#1195 Package - Min Setup Installation
  CMakeLists.txt
  amd_openvx/cmake/FindTurboJpeg.cmake
  amd_openvx_extensions/amd_migraphx/CMakeLists.txt
  docker/mivisionx-release-ubuntu20.dockerfile
  docker/mivisionx-release-ubuntu22.dockerfile
Labels: enhancement, bugfix

#1211 VX_RPP Fix build with OPENCL backend
  amd_openvx_extensions/amd_rpp/source/tensor/Vignette.cpp
Labels: bugfix

#1213 Update README.md
  README.md
Labels: bugfix

#1220 Standardize docs
  .github/dependabot.yml
  .readthedocs.yaml
  README.md
  docs/.sphinx/requirements.in
  docs/conf.py
  docs/license.md
  docs/sphinx/_toc.yml.in
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
Labels: docs, dependencies, ci:docs-only

#1221 CMakeList - ROCm Path Options
  CHANGELOG.md
  CMakeLists.txt
  MIVisionX-setup.py
  README.md
  docker/archive/mivisionx-opencl-on-ubuntu20.dockerfile
  docker/linux/mivisionx-on-rhel-8.dockerfile
  docker/linux/mivisionx-on-rhel-9.dockerfile
  docker/linux/mivisionx-on-sles-15.dockerfile
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/mivisionx-on-ubuntu22.dockerfile
  docker/pytorch/mivisionx-with-pytorch-with-mesa.dockerfile
  docker/pytorch/mivisionx-with-pytorch.dockerfile
  docker/tensorflow/mivisionx-with-tensorflow.dockerfile
  docker/ubuntu20/level-5.dockerfile
  docker/ubuntu22/level-5.dockerfile
Labels: enhancement
