Repository ROCm/MIVisionX, pull requests merged in 2023-06, with the labels that each got.

#1096 hwdec fix bug which was causing crash in MI300
  rocAL/rocAL/include/decoders/image/hw_jpeg_decoder.h
  rocAL/rocAL/source/decoders/image/hw_jpeg_decoder.cpp
Labels: bugfix

#1099 Develop - Merge to master
  docs/.sphinx/requirements.txt
Labels: bugfix

#1092 rocAL - Python Unit test fix
  rocAL/rocAL_pybind/amd/rocal/decoders.py
  rocAL/rocAL_pybind/amd/rocal/pipeline.py
  rocAL/rocAL_pybind/amd/rocal/plugin/generic.py
  rocAL/rocAL_pybind/amd/rocal/plugin/pytorch.py
  rocAL/rocAL_pybind/rocal_pybind.cpp
Labels: bugfix

#1103 Documentation - Update dependabot configurations
  .github/dependabot.yml
Labels: docs, noCI, dependencies

#1106 CTest - Add Basic Tests
  CMakeLists.txt
  tests/openvx/CMakeLists.txt
  tests/openvx/canny/CMakeLists.txt
  tests/openvx/canny/canny.cpp
  tests/openvx/channel_extract/CMakeLists.txt
  tests/openvx/channel_extract/channel_extract.cpp
  tests/openvx/color_convert/CMakeLists.txt
  tests/openvx/color_convert/color_convert.cpp
Labels: enhancement

#1105 rocAL - PyBind11: Use pre-built Lib
  CHANGELOG.md
  MIVisionX-setup.py
  README.md
  rocAL/rocAL_pybind/CMakeLists.txt
  rocAL/rocAL_pybind/setup.py
  rocAL/rocAL_pybind/third_party_lib/CMakeLists.txt
  rocAL/rocAL_pybind/third_party_lib/pybind11/CMakeLists.txt
  rocAL/rocAL_pybind/third_party_lib/pybind11/include/pybind11/attr.h
  rocAL/rocAL_pybind/third_party_lib/pybind11/include/pybind11/buffer_info.h
  rocAL/rocAL_pybind/third_party_lib/pybind11/include/pybind11/cast.h
  rocAL/rocAL_pybind/third_party_lib/pybind11/include/pybind11/chrono.h
  rocAL/rocAL_pybind/third_party_lib/pybind11/include/pybind11/common.h
  rocAL/rocAL_pybind/third_party_lib/pybind11/include/pybind11/complex.h
  rocAL/rocAL_pybind/third_party_lib/pybind11/include/pybind11/detail/class.h
  rocAL/rocAL_pybind/third_party_lib/pybind11/include/pybind11/detail/common.h
  rocAL/rocAL_pybind/third_party_lib/pybind11/include/pybind11/detail/descr.h
  rocAL/rocAL_pybind/third_party_lib/pybind11/include/pybind11/detail/init.h
  rocAL/rocAL_pybind/third_party_lib/pybind11/include/pybind11/detail/internals.h
  rocAL/rocAL_pybind/third_party_lib/pybind11/include/pybind11/detail/typeid.h
  rocAL/rocAL_pybind/third_party_lib/pybind11/include/pybind11/eigen.h
  rocAL/rocAL_pybind/third_party_lib/pybind11/include/pybind11/embed.h
  rocAL/rocAL_pybind/third_party_lib/pybind11/include/pybind11/eval.h
  rocAL/rocAL_pybind/third_party_lib/pybind11/include/pybind11/functional.h
  rocAL/rocAL_pybind/third_party_lib/pybind11/include/pybind11/iostream.h
  rocAL/rocAL_pybind/third_party_lib/pybind11/include/pybind11/numpy.h
  rocAL/rocAL_pybind/third_party_lib/pybind11/include/pybind11/operators.h
  rocAL/rocAL_pybind/third_party_lib/pybind11/include/pybind11/options.h
  rocAL/rocAL_pybind/third_party_lib/pybind11/include/pybind11/pybind11.h
  rocAL/rocAL_pybind/third_party_lib/pybind11/include/pybind11/pytypes.h
  rocAL/rocAL_pybind/third_party_lib/pybind11/include/pybind11/stl.h
  rocAL/rocAL_pybind/third_party_lib/pybind11/include/pybind11/stl_bind.h
  rocAL/rocAL_pybind/third_party_lib/pybind11/pybind11/__init__.py
  rocAL/rocAL_pybind/third_party_lib/pybind11/pybind11/__main__.py
  rocAL/rocAL_pybind/third_party_lib/pybind11/pybind11/_version.py
  rocAL/rocAL_pybind/third_party_lib/pybind11/setup.cfg
  rocAL/rocAL_pybind/third_party_lib/pybind11/setup.py
  rocAL/rocAL_pybind/third_party_lib/pybind11/tools/FindCatch.cmake
  rocAL/rocAL_pybind/third_party_lib/pybind11/tools/FindEigen3.cmake
  rocAL/rocAL_pybind/third_party_lib/pybind11/tools/FindPythonLibsNew.cmake
  rocAL/rocAL_pybind/third_party_lib/pybind11/tools/check-style.sh
  rocAL/rocAL_pybind/third_party_lib/pybind11/tools/libsize.py
  rocAL/rocAL_pybind/third_party_lib/pybind11/tools/mkdoc.py
  rocAL/rocAL_pybind/third_party_lib/pybind11/tools/pybind11Config.cmake.in
  rocAL/rocAL_pybind/third_party_lib/pybind11/tools/pybind11Tools.cmake
Labels: enhancement, bugfix

#1100 mv_compile - update
  model_compiler/python/nnef_to_nnir.py
  model_compiler/python/nnir_to_clib.py
  utilities/mv_deploy/CMakeLists.txt
  utilities/mv_deploy/README.md
  utilities/mv_deploy/mv_compile.cpp
Labels: enhancement, bugfix

#1109 NNIR-CLIB - Fix
  README.md
  model_compiler/python/nnir_to_clib.py
Labels: bugfix

#1110 CentOS 7 - Fix
  model_compiler/python/nnir_to_clib.py
  tests/vision_tests/runVisionTests.py
Labels: bugfix

#1111 NNIR_CLIB - Fix
  model_compiler/python/nnir_to_clib.py
  utilities/mv_deploy/CMakeLists.txt
Labels: bugfix

#1115 rocAL - RapidJSON Updates
  CHANGELOG.md
  MIVisionX-setup.py
  README.md
  amd_openvx/cmake/FindLMDB.cmake
  docker/archive/mivisionx-opencl-on-ubuntu20.dockerfile
  docker/linux/mivisionx-on-rhel-8.dockerfile
  docker/linux/mivisionx-on-rhel-9.dockerfile
  docker/linux/mivisionx-on-sles-15.dockerfile
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/mivisionx-on-ubuntu22.dockerfile
  docker/pytorch/mivisionx-with-pytorch-with-mesa.dockerfile
  docker/pytorch/mivisionx-with-pytorch.dockerfile
  docker/tensorflow/mivisionx-with-tensorflow.dockerfile
  docker/ubuntu20/level-3.dockerfile
  docker/ubuntu20/level-4.dockerfile
  docker/ubuntu20/level-5.dockerfile
  docker/ubuntu22/level-3.dockerfile
  docker/ubuntu22/level-4.dockerfile
  docker/ubuntu22/level-5.dockerfile
  rocAL/README.md
  rocAL/rocAL/CMakeLists.txt
  rocAL/rocAL_pybind/CMakeLists.txt
  rocAL/third_party/rapidjson/include/rapidjson/allocators.h
  rocAL/third_party/rapidjson/include/rapidjson/cursorstreamwrapper.h
  rocAL/third_party/rapidjson/include/rapidjson/document.h
  rocAL/third_party/rapidjson/include/rapidjson/encodedstream.h
  rocAL/third_party/rapidjson/include/rapidjson/encodings.h
  rocAL/third_party/rapidjson/include/rapidjson/error/en.h
  rocAL/third_party/rapidjson/include/rapidjson/error/error.h
  rocAL/third_party/rapidjson/include/rapidjson/filereadstream.h
  rocAL/third_party/rapidjson/include/rapidjson/filewritestream.h
  rocAL/third_party/rapidjson/include/rapidjson/fwd.h
  rocAL/third_party/rapidjson/include/rapidjson/internal/biginteger.h
  rocAL/third_party/rapidjson/include/rapidjson/internal/clzll.h
  rocAL/third_party/rapidjson/include/rapidjson/internal/diyfp.h
  rocAL/third_party/rapidjson/include/rapidjson/internal/dtoa.h
  rocAL/third_party/rapidjson/include/rapidjson/internal/ieee754.h
  rocAL/third_party/rapidjson/include/rapidjson/internal/itoa.h
  rocAL/third_party/rapidjson/include/rapidjson/internal/meta.h
  rocAL/third_party/rapidjson/include/rapidjson/internal/pow10.h
  rocAL/third_party/rapidjson/include/rapidjson/internal/regex.h
  rocAL/third_party/rapidjson/include/rapidjson/internal/stack.h
  rocAL/third_party/rapidjson/include/rapidjson/internal/strfunc.h
  rocAL/third_party/rapidjson/include/rapidjson/internal/strtod.h
  rocAL/third_party/rapidjson/include/rapidjson/internal/swap.h
  rocAL/third_party/rapidjson/include/rapidjson/istreamwrapper.h
  rocAL/third_party/rapidjson/include/rapidjson/memorybuffer.h
  rocAL/third_party/rapidjson/include/rapidjson/memorystream.h
  rocAL/third_party/rapidjson/include/rapidjson/msinttypes/inttypes.h
  rocAL/third_party/rapidjson/include/rapidjson/msinttypes/stdint.h
  rocAL/third_party/rapidjson/include/rapidjson/ostreamwrapper.h
  rocAL/third_party/rapidjson/include/rapidjson/pointer.h
  rocAL/third_party/rapidjson/include/rapidjson/prettywriter.h
  rocAL/third_party/rapidjson/include/rapidjson/rapidjson.h
  rocAL/third_party/rapidjson/include/rapidjson/reader.h
  rocAL/third_party/rapidjson/include/rapidjson/schema.h
  rocAL/third_party/rapidjson/include/rapidjson/stream.h
  rocAL/third_party/rapidjson/include/rapidjson/stringbuffer.h
  rocAL/third_party/rapidjson/include/rapidjson/uri.h
  rocAL/third_party/rapidjson/include/rapidjson/writer.h
Labels: enhancement, bugfix

#1118 rocAL - Readme Updates
  rocAL/README.md
Labels: enhancement

#1119 Docker - rocAL Updates
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/mivisionx-on-ubuntu22.dockerfile
  docker/pytorch/mivisionx-with-pytorch-with-mesa.dockerfile
  docker/pytorch/mivisionx-with-pytorch.dockerfile
  docker/tensorflow/mivisionx-with-tensorflow.dockerfile
  docker/ubuntu20/level-5.dockerfile
  docker/ubuntu22/level-5.dockerfile
Labels: bugfix
