Repository ROCm/MIVisionX, pull requests merged in 2023-07, with the labels that each got.

#1126 Version 2.5.0 - Updates
  CHANGELOG.md
  MIVisionX-setup.py
  README.md
  docker/archive/mivisionx-opencl-on-ubuntu20.dockerfile
  docker/linux/mivisionx-on-rhel-8.dockerfile
  docker/linux/mivisionx-on-rhel-9.dockerfile
  docker/linux/mivisionx-on-sles-15.dockerfile
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/mivisionx-on-ubuntu22.dockerfile
  docker/pytorch/mivisionx-with-pytorch-with-mesa.dockerfile
  docker/pytorch/mivisionx-with-pytorch.dockerfile
  docker/tensorflow/mivisionx-with-tensorflow.dockerfile
  docker/ubuntu20/level-5.dockerfile
  docker/ubuntu22/level-5.dockerfile
Labels: enhancement

#1129 SLES - Updates
  CHANGELOG.md
  MIVisionX-setup.py
  README.md
  utilities/mv_deploy/mv_compile.cpp
Labels: bugfix

#1131 VX_RPP - Fix
  amd_openvx_extensions/amd_rpp/source/kernel_rpp.cpp
Labels: bugfix

#1136 SWDEV-351540 - ASAN packaging for MIvisionX
  CMakeLists.txt
  utilities/mv_deploy/CMakeLists.txt
  utilities/runvx/CMakeLists.txt
Labels: enhancement

#1138 Documentation - Doxygen updates
  .gitignore
  Doxygen.txt
  README.md
  amd_openvx/openvx/include/vx_ext_amd.h
  amd_openvx_extensions/amd_custom/include/vx_amd_custom.h
  amd_openvx_extensions/amd_media/include/vx_amd_media.h
  amd_openvx_extensions/amd_migraphx/include/vx_amd_migraphx.h
  amd_openvx_extensions/amd_nn/include/vx_amd_nn.h
  amd_openvx_extensions/amd_opencv/include/vx_ext_opencv.h
  amd_openvx_extensions/amd_rpp/include/vx_ext_rpp.h
  amd_openvx_extensions/amd_winml/include/vx_ext_winml.h
  docs/data/AMD-Logo-Doxygen.png
Labels: enhancement

#1141 AMD RPP extension - doc update
  amd_openvx_extensions/amd_rpp/include/vx_ext_rpp.h
Labels: enhancement, bugfix

#1135 rocAL - Python Unit Test Fix PR
  rocAL/rocAL_pybind/amd/rocal/fn.py
  rocAL/rocAL_pybind/amd/rocal/plugin/tf.py
  rocAL/rocAL_pybind/examples/READERS_TEST_FILE.sh
  rocAL/rocAL_pybind/examples/rocAL_api_python_unittest.py
  rocAL/rocAL_pybind/examples/rocAL_api_tf_classification_reader.py
  rocAL/rocAL_pybind/examples/rocAL_api_tf_detection_pipeline.py
Labels: bug

#1144 VX_RPP Fix build issues
  amd_openvx_extensions/amd_rpp/include/vx_ext_rpp.h
Labels: enhancement, bugfix

#1142 vx_ext_amd - updates & cleanup
  amd_openvx/openvx/include/vx_ext_amd.h
  amd_openvx_extensions/amd_custom/include/vx_amd_custom.h
  amd_openvx_extensions/amd_media/include/vx_amd_media.h
  amd_openvx_extensions/amd_migraphx/include/vx_amd_migraphx.h
  amd_openvx_extensions/amd_nn/include/vx_amd_nn.h
  amd_openvx_extensions/amd_opencv/include/internal_publishKernels.h
  amd_openvx_extensions/amd_opencv/include/vx_ext_opencv.h
  amd_openvx_extensions/amd_opencv/source/internal_publishKernels.cpp
  amd_openvx_extensions/amd_opencv/source/internal_vxNodes.cpp
  amd_openvx_extensions/amd_rpp/include/internal_publishKernels.h
  amd_openvx_extensions/amd_rpp/include/vx_ext_rpp.h
  amd_openvx_extensions/amd_winml/include/vx_ext_winml.h
Labels: enhancement

#1132 Documentation - Add Doxygen to Read the Docs site
  .readthedocs.yaml
  README.md
  amd_openvx_extensions/amd_rpp/include/vx_ext_rpp.h
  apps/mivisionx_winml_classifier/README.md
  docs/.sphinx/_toc.yml.in
  docs/.sphinx/requirements.in
  docs/.sphinx/requirements.txt
  docs/conf.py
  docs/doxygen/Doxyfile
Labels: docs, ci:docs-only

#1152 Documentation - Updates & Fix
  .Doxyfile
  .DoxygenLayout.xml
  amd_openvx/README.md
  docs/.sphinx/_toc.yml.in
  docs/doxygen/.DoxygenLayout.xml
  docs/doxygen/Doxyfile
  utilities/rocAL/README.md
Labels: enhancement, bugfix
