Repository ROCm/MIVisionX, pull requests merged in 2024-11, with the labels that each got.

#1444 CMakeLists - Default GPU List Updates
  CMakeLists.txt
Labels: enhancement, ci:precheckin

#1438 fixed documentation to say how to use frames option in runvx
  utilities/runvx/README.md
  utilities/runvx/runvx.cpp
Labels: bugfix, ci:precheckin

#1445 Fix pkg version headings in CHANGELOG.md
  CHANGELOG.md
Labels: ci:docs-only, Documentation

#1442 Update OpenCL LUT type to uchar buffer
  amd_openvx/openvx/ago/ago_drama_alloc.cpp
  amd_openvx/openvx/ago/ago_interface.cpp
  amd_openvx/openvx/ago/ago_kernel_api.cpp
  amd_openvx/openvx/ago/ago_util_opencl.cpp
  amd_openvx/openvx/include/vx_ext_amd.h
Labels: enhancement, bugfix, ci:precheckin

#1448 ROCm 6.3 cherry pick - GFX
  CMakeLists.txt
Labels: enhancement

#1449 ROCm 6.3 - Cherry-pick - NN Dependencies - Bump future package from 0.18.2 to 1.0.0 (#1436)
  MIVisionX-setup.py
  docs/install/model-compiler-install.rst
  model_compiler/README.md
  tests/neural_network_tests/runNeuralNetworkTests.py
Labels: enhancement

#1451 Build and package - updates
  CHANGELOG.md
  CMakeLists.txt
  MIVisionX-setup.py
  README.md
  amd_openvx/CMakeLists.txt
  amd_openvx/openvx/CMakeLists.txt
  amd_openvx/openvx/hipvx/CMakeLists.txt
  amd_openvx_extensions/CMakeLists.txt
  amd_openvx_extensions/amd_custom/CMakeLists.txt
  amd_openvx_extensions/amd_custom/custom_lib/CMakeLists.txt
  amd_openvx_extensions/amd_loomsl/CMakeLists.txt
  amd_openvx_extensions/amd_media/CMakeLists.txt
  amd_openvx_extensions/amd_migraphx/CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  amd_openvx_extensions/amd_nn/nn_hip/CMakeLists.txt
  amd_openvx_extensions/amd_opencv/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  apps/CMakeLists.txt
  apps/bubble_pop/CMakeLists.txt
  apps/cloud_inference/server_app/CMakeLists.txt
  apps/dg_test/CMakeLists.txt
  apps/mivisionx_openvx_classifier/CMakeLists.txt
  apps/optical_flow/CMakeLists.txt
  docs/install/installation.rst
  model_compiler/python/nnir_to_clib.py
  model_compiler/python/nnir_to_openvx.py
  model_compiler/python/nnir_to_zendnn.py
  samples/c_samples/canny/CMakeLists.txt
  samples/c_samples/opencv_orb/CMakeLists.txt
  samples/model_compiler_samples/CMakeLists.txt
  samples/mv_objdetect/CMakeLists.txt
  tests/CMakeLists.txt
  tests/amd_migraphx_tests/mnist/CMakeLists.txt
  tests/amd_migraphx_tests/resnet50/CMakeLists.txt
  tests/amd_migraphx_tests/runMIGraphXTests/CMakeLists.txt
  tests/openvx_api_tests/canny/CMakeLists.txt
  tests/openvx_api_tests/channel_extract/CMakeLists.txt
  tests/openvx_api_tests/color_convert/CMakeLists.txt
  tests/zen_dnn_tests/conv/CMakeLists.txt
  tests/zen_dnn_tests/mnist/CMakeLists.txt
  tests/zen_dnn_tests/mnist_app/CMakeLists.txt
  utilities/CMakeLists.txt
  utilities/loom_io_media/CMakeLists.txt
  utilities/loom_shell/CMakeLists.txt
  utilities/mv_deploy/CMakeLists.txt
  utilities/runcl/CMakeLists.txt
  utilities/runvx/CMakeLists.txt
Labels: bugfix, ci:precheckin

#1450 OpenVX - GFX942: Fix canny test case
  amd_openvx/openvx/ago/ago_haf_cpu_canny.cpp
  amd_openvx/openvx/hipvx/vision_kernels.cpp
Labels: bugfix, ci:precheckin

#1454 Compiler - Set AMD clang++ as default compiler for HIP
  CHANGELOG.md
  CMakeLists.txt
  README.md
  amd_openvx/README.md
  amd_openvx/openvx/hipvx/CMakeLists.txt
  amd_openvx_extensions/amd_custom/CMakeLists.txt
  amd_openvx_extensions/amd_custom/custom_lib/CMakeLists.txt
  amd_openvx_extensions/amd_nn/nn_hip/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/README.md
  docs/install/amd_openvx-install.rst
  docs/install/installation.rst
  model_compiler/python/nnir_to_zendnn.py
  tests/zen_dnn_tests/conv/CMakeLists.txt
  tests/zen_dnn_tests/mnist/CMakeLists.txt
  tests/zen_dnn_tests/mnist_app/CMakeLists.txt
Labels: enhancement, bugfix, ci:precheckin
