Repository ROCm/MIVisionX, pull requests merged in 2024-12, with the labels that each got.

#1464 AMD Clang Warning Fix
  amd_openvx/openvx/ago/ago_drama_alloc.cpp
  amd_openvx/openvx/ago/ago_interface.cpp
Labels: bugfix, ci:precheckin

#1460 VX_AMD_MEDIA - support for ffmpeg version 4 and above
  amd_openvx_extensions/CMakeLists.txt
  amd_openvx_extensions/amd_media/CMakeLists.txt
  amd_openvx_extensions/amd_media/decoder.cpp
  amd_openvx_extensions/amd_media/kernels.cpp
Labels: enhancement, bugfix, ci:precheckin

#1457 Cherry-pick - GFX942 Fix & Ubuntu 24.04 Failures Fix (#1450)
  CHANGELOG.md
  CMakeLists.txt
  README.md
  amd_openvx/openvx/ago/ago_haf_cpu_canny.cpp
  amd_openvx/openvx/hipvx/CMakeLists.txt
  amd_openvx/openvx/hipvx/vision_kernels.cpp
  amd_openvx_extensions/amd_custom/CMakeLists.txt
  amd_openvx_extensions/amd_custom/custom_lib/CMakeLists.txt
  amd_openvx_extensions/amd_nn/nn_hip/CMakeLists.txt
  docs/install/installation.rst
  model_compiler/python/nnir_to_zendnn.py
  tests/zen_dnn_tests/conv/CMakeLists.txt
  tests/zen_dnn_tests/mnist/CMakeLists.txt
  tests/zen_dnn_tests/mnist_app/CMakeLists.txt
Labels: bugfix, ci:precheckin

#1456 Fix exposure compensation kernel
  amd_openvx_extensions/amd_loomsl/kernels/exposure_compensation.cpp
Labels: bugfix, ci:precheckin

#1467 OpenVX - gpu_buffer_offset fix
  amd_openvx/openvx/ago/ago_drama_alloc.cpp
  amd_openvx/openvx/ago/ago_haf_cpu_canny.cpp
  amd_openvx/openvx/hipvx/vision_kernels.cpp
Labels: bugfix, ci:precheckin, ci:hip-backend

#1469 VX_EXT_AMD - Fix AgoTargetAffinityInfo
  amd_openvx/openvx/include/vx_ext_amd.h
Labels: bugfix, ci:precheckin, ci:hip-backend
