Repository ROCm/MIVisionX, pull requests merged in 2024-05, with the labels that each got.

#1341 Find Half - Fix
  cmake/FindHALF.cmake
Labels: bugfix

#1343 MIVisionX Setup - Updates
  CHANGELOG.md
  MIVisionX-setup.py
  README.md
  docs/install/installation.rst
Labels: bugfix

#1319 Audio PR - Augmentation support [ Spectrogram ]
  CHANGELOG.md
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/include/internal_publishKernels.h
  amd_openvx_extensions/amd_rpp/include/kernels_rpp.h
  amd_openvx_extensions/amd_rpp/include/vx_ext_rpp.h
  amd_openvx_extensions/amd_rpp/source/internal_publishKernels.cpp
  amd_openvx_extensions/amd_rpp/source/kernel_rpp.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/Spectrogram.cpp
Labels: enhancement

#1348 Leo's edits
  .gitignore
  docs/index.rst
  docs/install/amd_openvx-install.rst
  docs/install/model-compiler-install.rst
  docs/sphinx/_toc.yml.in
Labels: docs, ci:docs-only

#1347 Introduce Audio Layout and fix Spectrogram
  amd_openvx_extensions/amd_rpp/include/internal_rpp.h
  amd_openvx_extensions/amd_rpp/source/kernel_rpp.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/Spectrogram.cpp
Labels: enhancement

#1349 CMakeList Updates - ROCm 6.2 Updates
  CHANGELOG.md
  CMakeLists.txt
  MIVisionX-setup.py
  README.md
  amd_openvx/CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  docker/README.md
  docker/conformance/openvx-1-3-on-centos7.dockerfile
  docker/conformance/openvx-1-3-on-centos8.dockerfile
  docker/conformance/openvx-1-3-on-ubuntu18.dockerfile
  docker/conformance/openvx-1-3-on-ubuntu20.dockerfile
  docker/linux/mivisionx-on-rhel-8.dockerfile
  docker/linux/mivisionx-on-rhel-9.dockerfile
  docker/linux/mivisionx-on-sles-15.dockerfile
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/mivisionx-on-ubuntu22.dockerfile
  docker/mivisionx-release-ubuntu20.dockerfile
  docker/mivisionx-release-ubuntu22.dockerfile
  docker/ubuntu20/level-2.dockerfile
  docker/ubuntu20/level-3.dockerfile
  docker/ubuntu20/level-4.dockerfile
  docker/ubuntu20/level-5.dockerfile
  docker/ubuntu22/level-2.dockerfile
  docker/ubuntu22/level-3.dockerfile
  docker/ubuntu22/level-4.dockerfile
  docker/ubuntu22/level-5.dockerfile
  docker/zenDNN/zenDNN-gpu-hip.dockerfile
  docs/how-to/mivisionx-docker.rst
Labels: enhancement, bugfix

#1353 vx_rpp - Versioning
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/include/vx_ext_rpp_version.h
  cmake/FindAMDRPP.cmake
Labels: enhancement

#1356 Fixing HIP CMake issue
  CMakeLists.txt
Labels: enhancement

#1360 Port doc reorg to 6.1.1
  .gitignore
  README.md
  amd_openvx_extensions/amd_migraphx/README.md
  amd_openvx_extensions/amd_winml/samples/README.md
  apps/README.md
  apps/dg_test/README.md
  apps/mivisionx_winml_classifier/README.md
  docs/conf.py
  docs/doxygen/Doxyfile
  docs/how-to/amd_openvx.rst
  docs/how-to/mivisionx-docker.rst
  docs/how-to/model-compiler.rst
  docs/index.rst
  docs/install/amd_openvx-install.rst
  docs/install/installation.rst
  docs/install/model-compiler-install.rst
  docs/license.rst
  docs/reference/toolkit.rst
  docs/reference/utilities-loom_shell.rst
  docs/reference/utilities-mv_deploy.rst
  docs/reference/utilities-runcl.rst
  docs/reference/utilities-runvx.rst
  docs/reference/utilities.rst
  docs/sphinx/_toc.yml.in
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
  docs/tutorials/mivisionx-apps.rst
  docs/tutorials/mivisionx-samples.rst
  docs/tutorials/mivisionx-tests.rst
  docs/what-is-mivisionx.rst
  samples/loom_360_stitch/README.md
  utilities/runvx/README.md
Labels: ci:docs-only

#1361 Fix SoftMaxWithLoss in table
  docs/how-to/model-compiler.rst
Labels: ci:docs-only

#1363 CMakeLists - Find HIP rocm 6.1.X updates
  CHANGELOG.md
  CMakeLists.txt
  README.md
  amd_openvx_extensions/CMakeLists.txt
  amd_openvx_extensions/amd_custom/CMakeLists.txt
  amd_openvx_extensions/amd_custom/custom_lib/CMakeLists.txt
  amd_openvx_extensions/amd_media/CMakeLists.txt
  amd_openvx_extensions/amd_migraphx/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  apps/cloud_inference/server_app/CMakeLists.txt
  utilities/CMakeLists.txt
  utilities/runvx/CMakeLists.txt
Labels: enhancement, bugfix

#1320 Audio PR - Augmentation support [ Downmix and ToDecibels ]
  CHANGELOG.md
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/include/internal_publishKernels.h
  amd_openvx_extensions/amd_rpp/include/internal_rpp.h
  amd_openvx_extensions/amd_rpp/include/kernels_rpp.h
  amd_openvx_extensions/amd_rpp/include/vx_ext_rpp.h
  amd_openvx_extensions/amd_rpp/source/internal_publishKernels.cpp
  amd_openvx_extensions/amd_rpp/source/kernel_rpp.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/Downmix.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/ToDecibels.cpp
Labels: enhancement

#1323 Audio PR - Augmentation support [ Resample and Operator Overloading nodes ]
  CHANGELOG.md
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/include/internal_publishKernels.h
  amd_openvx_extensions/amd_rpp/include/kernels_rpp.h
  amd_openvx_extensions/amd_rpp/include/vx_ext_rpp.h
  amd_openvx_extensions/amd_rpp/source/internal_publishKernels.cpp
  amd_openvx_extensions/amd_rpp/source/kernel_rpp.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/Resample.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/TensorAddTensor.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/TensorMulScalar.cpp
Labels: enhancement
