Repository ROCm/MIVisionX, pull requests merged in 2024-07, with the labels that each got.

#1390 CMakeLists - Set AMDGPU_TARGETS
  CMakeLists.txt
  amd_openvx/CMakeLists.txt
  amd_openvx_extensions/CMakeLists.txt
  amd_openvx_extensions/amd_custom/CMakeLists.txt
  amd_openvx_extensions/amd_custom/custom_lib/CMakeLists.txt
  amd_openvx_extensions/amd_media/CMakeLists.txt
  amd_openvx_extensions/amd_migraphx/CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  apps/cloud_inference/server_app/CMakeLists.txt
  utilities/CMakeLists.txt
  utilities/runvx/CMakeLists.txt
Labels: enhancement, bugfix

#1393 Update CODEOWNERS for documentation
  .github/CODEOWNERS
Labels: docs, ci:docs-only

#1387 Packaging - Remove package provides field from RPM and DEB package (#1381)
  CMakeLists.txt
Labels: bugfix

#1394 Ubuntu 24.04 - Support Updates
  CHANGELOG.md
  MIVisionX-setup.py
  README.md
  tests/neural_network_tests/runNeuralNetworkTests.py
Labels: enhancement

#1395 Audio PR: Todecibels Fix for dst roi updation
  amd_openvx_extensions/amd_rpp/source/tensor/ToDecibels.cpp
Labels: bugfix
