Repository ROCm/MIVisionX, pull requests merged in 2024-01, with the labels that each got.

#1261 MV_DEPLOY:Find Half - Fix
  samples/mv_objdetect/CMakeLists.txt
Labels: bugfix

#1265 ONNX Link Updates
  apps/mivisionx_winml_yolov2/README.md
  tests/amd_migraphx_tests/gdf/README.md
  tests/amd_migraphx_tests/mnist/README.md
  tests/amd_migraphx_tests/resnet50/README.md
Labels: bugfix

#1263 Fixed a resource leak and uninitialized variable
  amd_openvx/openvx/ago/ago_drama_divide.cpp
  utilities/loom_shell/loom_shell_util.cpp
Labels: bugfix

#1260 Linting fixes for PEP-8 conformance.
  MIVisionX-setup.py
  apps/mivisionx_inference_analyzer/mivisionx_inference_analyzer.py
  apps/mivisionx_validation_tool/inference_setup.py
  apps/mivisionx_validation_tool/inference_viewer.py
  model_compiler/python/nnir.py
  model_compiler/python/nnir_to_clib.py
Labels: enhancement

#1272 ROCm 6.1 - Updates
  CMakeLists.txt
  README.md
  cmake/FindFFmpeg.cmake
  docker/README.md
  docs/sphinx/_toc.yml.in
Labels: enhancement, bugfix

#1273 Cleanup and fixes for pep-8 conformance - II
  model_compiler/python/nnir_to_openvx.py
  model_compiler/python/nnir_to_zendnn.py
  model_compiler/python/onnx_to_nnir.py
  rocAL/docs/examples/image_processing/inference_pipeline.py
  rocAL/rocAL_pybind/amd/rocal/fn.py
  tests/library_tests/runLibraryTests.py
  tests/neural_network_tests/runNeuralNetworkTests.py
  tests/smoke_tests/Inference/inference-measure-accuracy.py
Labels: enhancement
