Repository ROCm/MIVisionX, pull requests merged in 2024-03, with the labels that each got.

#1295 NN Test - Fix for ONNX failure
  MIVisionX-setup.py
  model_compiler/README.md
  tests/neural_network_tests/runNeuralNetworkTests.py
Labels: bugfix

#1294 NN Inference Setup - Use ONNX 1.12.0
  MIVisionX-setup.py
  model_compiler/README.md
  tests/neural_network_tests/runNeuralNetworkTests.py
Labels: bugfix

#1307 CMakeLists - Build for advanced GPUs fix
  CHANGELOG.md
  CMakeLists.txt
  MIVisionX-setup.py
  README.md
  apps/mivisionx_inference_analyzer/mivisionx_inference_analyzer.py
  cmake/FindHALF.cmake
  docker/conformance/system_info.py
  tests/amd_opencv_tests/runOpenCVTests.py
  tests/conformance_tests/runConformanceTests.py
  tests/library_tests/runLibraryTests.py
  tests/neural_network_tests/runNeuralNetworkTests.py
  tests/vision_tests/runVisionTests.py
  toolkit/amd_data_analysis_toolkit/classification/generate-visualization.py
  toolkit/amd_data_analysis_toolkit/object_detection/generate-visualization.py
Labels: enhancement, bugfix

#1308 Fix broken links
  README.md
  amd_openvx_extensions/amd_migraphx/README.md
  amd_openvx_extensions/amd_winml/samples/README.md
  apps/README.md
  apps/dg_test/README.md
  apps/mivisionx_winml_classifier/README.md
  docs/doxygen/Doxyfile
  docs/sphinx/_toc.yml.in
  samples/loom_360_stitch/README.md
  utilities/runvx/README.md
Labels: docs, ci:docs-only

#1312 Fix broken links for 6.0.2
  README.md
  amd_openvx_extensions/amd_migraphx/README.md
  amd_openvx_extensions/amd_winml/samples/README.md
  apps/README.md
  apps/dg_test/README.md
  apps/mivisionx_winml_classifier/README.md
  docs/.sphinx/_toc.yml.in
  docs/doxygen/Doxyfile
  samples/loom_360_stitch/README.md
  utilities/runvx/README.md
Labels: docs, ci:docs-only

#1318 Setup - updates & enhancements
  CMakeLists.txt
  MIVisionX-setup.py
  cmake/FindFFmpeg.cmake
Labels: enhancement, bugfix

#1315 ADAT - Updates & improvements
  amd_openvx_extensions/CMakeLists.txt
  apps/mivisionx_inference_analyzer/data/images/MIVisionX-logo.png
  apps/mivisionx_inference_analyzer/inference_control.py
  apps/mivisionx_inference_analyzer/mivisionx_inference_analyzer.py
Labels: enhancement
