Repository ROCm/MIVisionX, pull requests merged in 2024-08, with the labels that each got.

#1400 Setup - SLES 15 SP5 Updates
  CHANGELOG.md
  MIVisionX-setup.py
  tests/neural_network_tests/runNeuralNetworkTests.py
Labels: enhancement, bugfix

#1401 SLES - pip updates
  MIVisionX-setup.py
  tests/neural_network_tests/runNeuralNetworkTests.py
Labels: bugfix

#1402 Update documentation requirements
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
Labels: docs, ci:docs-only, Documentation

#1406 Test Package Updates
  CMakeLists.txt
  amd_openvx/openvx/CMakeLists.txt
  amd_openvx_extensions/amd_loomsl/CMakeLists.txt
  amd_openvx_extensions/amd_nn/CMakeLists.txt
  amd_openvx_extensions/amd_opencv/CMakeLists.txt
  cmake/FindMIVISIONX.cmake
  cmake/FindMIVisionX.cmake
  tests/CMakeLists.txt
  tests/amd_opencv_tests/README.md
  tests/amd_opencv_tests/runOpenCVTests.py
  tests/ctest_cmakelists/CMakeLists.txt
  tests/vision_tests/gdfs/openvx_test_results/.gitkeep
  utilities/runvx/CMakeLists.txt
Labels: enhancement, bugfix

#1408 VX_RPP - test
  CMakeLists.txt
  amd_openvx_extensions/amd_media/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  tests/CMakeLists.txt
  tests/amd_media_tests/gdf/decoder_test.gdf
  tests/vx_rpp_tests/README.md
  tests/vx_rpp_tests/gdf/test_vx_rpp.gdf
Labels: enhancement, bugfix

#1409 Find Modules - Cleanup
  CHANGELOG.md
  cmake/FindAMDRPP.cmake
  cmake/FindFFmpeg.cmake
  cmake/FindHALF.cmake
  cmake/FindLMDB.cmake
  cmake/FindMIVISIONX.cmake
  cmake/FindTurboJpeg.cmake
  tests/CMakeLists.txt
  tests/amd_opencv_tests/gdfs/absdiff_test.gdf
Labels: enhancement

#1411 Test - All modules test
  amd_openvx_extensions/amd_media/CMakeLists.txt
  amd_openvx_extensions/amd_migraphx/CMakeLists.txt
  cmake/FindMIVISIONX.cmake
  tests/CMakeLists.txt
  tests/amd_migraphx_tests/gdf/mnist-8.onnx
  tests/amd_migraphx_tests/gdf/vx_migraphx_test.gdf
  tests/neural_network_tests/gdf/test_vx_nn.gdf
  tests/vision_tests/gdfs/00_absDiff_test.gdf
  tests/vision_tests/gdfs/00_harrisCorners_test.gdf
Labels: enhancement

#1416 Fixing Resample build issue
  amd_openvx_extensions/amd_rpp/source/tensor/Resample.cpp
Labels: bugfix

#1417 Revert "Fixing Resample build issue"
  amd_openvx_extensions/amd_rpp/source/tensor/Resample.cpp
Labels: bugfix
