Repository ROCm/MIVisionX, pull requests merged in 2024-06, with the labels that each got.

#1370 NNEF - Use V1.0.0 Branch
  MIVisionX-setup.py
  docker/mivisionx-on-ubuntu20.dockerfile
  docker/ubuntu20/level-5.dockerfile
  docker/ubuntu22/level-5.dockerfile
  docs/install/model-compiler-install.rst
  model_compiler/README.md
  tests/neural_network_tests/runNeuralNetworkTests.py
Labels: bugfix

#1371 RHEL 8 - Fix PIP package
  MIVisionX-setup.py
  tests/neural_network_tests/runNeuralNetworkTests.py
Labels: bugfix

#1324 Audio PR - Augmentation support [ Non Silent Region Detection and Slice ]
  CHANGELOG.md
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/include/internal_publishKernels.h
  amd_openvx_extensions/amd_rpp/include/internal_rpp.h
  amd_openvx_extensions/amd_rpp/include/kernels_rpp.h
  amd_openvx_extensions/amd_rpp/include/vx_ext_rpp.h
  amd_openvx_extensions/amd_rpp/source/internal_publishKernels.cpp
  amd_openvx_extensions/amd_rpp/source/kernel_rpp.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/NonSilentRegionDetection.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/Slice.cpp
Labels: enhancement

#1374 VX_RPP - update patch for audio support
  amd_openvx_extensions/amd_rpp/include/vx_ext_rpp_version.h
Labels: enhancement

#1326 Audio PR - Augmentation support [ Mel-Filter Bank and Normalize ]
  CHANGELOG.md
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/include/internal_publishKernels.h
  amd_openvx_extensions/amd_rpp/include/kernels_rpp.h
  amd_openvx_extensions/amd_rpp/include/vx_ext_rpp.h
  amd_openvx_extensions/amd_rpp/source/internal_publishKernels.cpp
  amd_openvx_extensions/amd_rpp/source/kernel_rpp.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/MelFilterBank.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/Normalize.cpp
Labels: enhancement

#1373 Update installation.rst
  docs/install/installation.rst
Labels: docs, ci:docs-only

#1379 Update installation.rst (#1373)
  docs/install/installation.rst
Labels: docs, ci:docs-only

#1380 Update installation.rst (#1373)
  docs/install/installation.rst
Labels: docs, ci:docs-only

#1386 Centos 7 - Support Updates
  CHANGELOG.md
  MIVisionX-setup.py
  README.md
Labels: enhancement, bugfix
