Repository ROCm/MIVisionX, pull requests merged in 2024-10, with the labels that each got.

#1435 Test - Updates
  tests/CMakeLists.txt
  tests/openvx_api_tests/canny/canny.cpp
  tests/vision_tests/gdfs/00_canny.gdf
Labels: bugfix, ci:precheckin

#1436 NN Dependencies - Bump future package from 0.18.2 to 1.0.0
  MIVisionX-setup.py
  docs/install/model-compiler-install.rst
  model_compiler/README.md
  tests/neural_network_tests/runNeuralNetworkTests.py
Labels: enhancement, bugfix, ci:precheckin

#1434 CMakeLists - clang path updates to reflect packaging
  amd_openvx/openvx/hipvx/CMakeLists.txt
  amd_openvx_extensions/amd_nn/nn_hip/CMakeLists.txt
Labels: ci:precheckin

#1432 GPU Targets - Updates
  CMakeLists.txt
Labels: enhancement, ci:precheckin

#1440 added link to documentation
  README.md
Labels: docs, ci:docs-only, Documentation
