Repository ROCm/MIVisionX, pull requests merged in 2025-06, with the labels that each got.

#1507 VX_RPP - RPP_LEGACY_SUPPORT - changes & updates
  CHANGELOG.md
  README.md
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/include/internal_publishKernels.h
  amd_openvx_extensions/amd_rpp/include/internal_rpp.h
  amd_openvx_extensions/amd_rpp/include/kernels_rpp.h
  amd_openvx_extensions/amd_rpp/include/vx_ext_rpp.h
  amd_openvx_extensions/amd_rpp/include/vx_ext_rpp_version.h
  amd_openvx_extensions/amd_rpp/source/internal_publishKernels.cpp
  amd_openvx_extensions/amd_rpp/source/kernel_rpp.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/Blur.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/ColorTemperature.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/Fog.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/Jitter.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/LensCorrection.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/Pixelate.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/Rain.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/ResizeCrop.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/Vignette.cpp
Labels: enhancement, bugfix, ci:precheckin

#1517 Adding missed #ENABLE_HIP checks
  amd_openvx_extensions/amd_rpp/source/tensor/Fog.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/Jitter.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/LensCorrection.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/Pixelate.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/Rain.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/Vignette.cpp
Labels: bugfix, ci:precheckin

#1520 VX_RPP - Fix build warnings
  amd_openvx_extensions/amd_rpp/include/internal_rpp.h
  amd_openvx_extensions/amd_rpp/source/image/CopybatchPD.cpp
  amd_openvx_extensions/amd_rpp/source/image/ResizeMirrorNormalizeTensor.cpp
  amd_openvx_extensions/amd_rpp/source/image/Resizetensor.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/Copy.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/Fog.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/Jitter.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/LensCorrection.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/Log1p.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/Pixelate.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/Rain.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/Resize.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/ResizeCrop.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/ResizeCropMirror.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/ResizeMirrorNormalize.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/Vignette.cpp
Labels: ci:precheckin

#1524 CTest - Capture OCL Failures
  CMakeLists.txt
  tests/amd_openvx_gdfs/cpu/hidden/GPU_FAILURE_OCL_Convolve_S16_U8_9x9.gdf
  tests/amd_openvx_gdfs/cpu/hidden/GPU_FAILURE_OCL_Convolve_U8_U8_9x9.gdf
  tests/amd_openvx_gdfs/cpu/hidden/GPU_FAILURE_OCL_Dilate_U1_U1_3x3.gdf
  tests/amd_openvx_gdfs/cpu/hidden/GPU_FAILURE_OCL_Dilate_U8_U1_3x3.gdf
  tests/amd_openvx_gdfs/cpu/hidden/GPU_FAILURE_OCL_Erode_U1_U1_3x3.gdf
  tests/amd_openvx_gdfs/cpu/hidden/GPU_FAILURE_OCL_Erode_U8_U1_3x3.gdf
  tests/amd_openvx_gdfs/cpu/hidden/GPU_FAILURE_OCL_WarpPerspective_U8_U8_Bilinear.gdf
  tests/amd_openvx_gdfs/cpu/hidden/GPU_FAILURE_OCL_WarpPerspective_U8_U8_Nearest.gdf
  tests/amd_openvx_gdfs/runOpenVX.py
Labels: enhancement, ci:precheckin
