Repository ROCm/MIVisionX, pull requests merged in 2025-08, with the labels that each got.

#1537 AMD Custom - Fix
  CHANGELOG.md
  MIVisionX-setup.py
  amd_openvx_extensions/amd_custom/CMakeLists.txt
  amd_openvx_extensions/amd_custom/README.md
  amd_openvx_extensions/amd_custom/custom_lib/CMakeLists.txt
  amd_openvx_extensions/amd_custom/custom_lib/custom_copy_impl.cpp
  apps/mivisionx_validation_tool/README.md
Labels: bugfix, ci:precheckin

#1530 VX includes - Update Half
  amd_openvx/openvx/include/vx_ext_amd.h
Labels: enhancement, ci:precheckin

#1545 Docs - fixed some broken links from the original PR
  docs/index.rst
  docs/install/MIVisionX-prerequisites.rst
  docs/tutorials/MIVisionX-apps-samples.rst
Labels: docs, ci:docs-only, Documentation

#1544 VX_RPP - Updates and Fix
  amd_openvx_extensions/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/include/internal_rpp.h
  apps/cloud_inference/server_app/CMakeLists.txt
  cmake/FindAMDRPP.cmake
  cmake/FindMIVISIONX.cmake
Labels: enhancement, bugfix, ci:precheckin

#1543 VX_RPP - Fix memory leak
  amd_openvx_extensions/amd_rpp/source/kernel_rpp.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/LensCorrection.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/Rain.cpp
Labels: enhancement, bugfix, ci:precheckin
