Repository ROCm/MIVisionX, pull requests merged in 2025-03, with the labels that each got.

#1493 ROCm 6.4 - Cherrypick: updated changelog
  CHANGELOG.md
Labels: ci:docs-only, Documentation

#1491 Adding Audio CMake fix for RPP v2.0
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
Labels: bugfix, ci:precheckin

#1496 VX_RPP - Transpose and normalize augmentation support
  amd_openvx_extensions/amd_rpp/CMakeLists.txt
  amd_openvx_extensions/amd_rpp/include/internal_publishKernels.h
  amd_openvx_extensions/amd_rpp/include/kernels_rpp.h
  amd_openvx_extensions/amd_rpp/include/vx_ext_rpp.h
  amd_openvx_extensions/amd_rpp/source/internal_publishKernels.cpp
  amd_openvx_extensions/amd_rpp/source/kernel_rpp.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/Normalize.cpp
  amd_openvx_extensions/amd_rpp/source/tensor/Transpose.cpp
Labels: enhancement, ci:precheckin
